C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVS1P1N_3(F1, F2, S4, COUP,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 TMP7
      COMPLEX*16 V3(6)
      P4(0) = DBLE(S4(1))
      P4(1) = DBLE(S4(2))
      P4(2) = DIMAG(S4(2))
      P4(3) = DIMAG(S4(1))
      TMP7 = (F2(3)*F1(3)+F2(4)*F1(4))
      V3(3)= COUP*(-CI )* TMP7*P4(0)*S4(3)
      V3(4)= COUP*CI * TMP7*P4(1)*S4(3)
      V3(5)= COUP*CI * TMP7*P4(2)*S4(3)
      V3(6)= COUP*CI * TMP7*P4(3)*S4(3)
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVS1_2_3_7P1N_3(F1, F2, S4, COUP1, COUP2, COUP3,
     $  COUP4,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 V3(6)
      COMPLEX*16 VTMP(6)
      INTEGER*4 I
      CALL FFVS1P1N_3(F1,F2,S4,COUP1,V3)
      CALL FFVS2P1N_3(F1,F2,S4,COUP2,VTMP)
      DO I = 3, 6
        V3(I) = V3(I) + VTMP(I)
      ENDDO
      CALL FFVS3P1N_3(F1,F2,S4,COUP3,VTMP)
      DO I = 3, 6
        V3(I) = V3(I) + VTMP(I)
      ENDDO
      CALL FFVS7P1N_3(F1,F2,S4,COUP4,VTMP)
      DO I = 3, 6
        V3(I) = V3(I) + VTMP(I)
      ENDDO
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVS1_2_3_7_9P1N_3(F1, F2, S4, COUP1, COUP2, COUP3,
     $  COUP4, COUP5,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 V3(6)
      COMPLEX*16 VTMP(6)
      INTEGER*4 I
      CALL FFVS1P1N_3(F1,F2,S4,COUP1,V3)
      CALL FFVS2P1N_3(F1,F2,S4,COUP2,VTMP)
      DO I = 3, 6
        V3(I) = V3(I) + VTMP(I)
      ENDDO
      CALL FFVS3P1N_3(F1,F2,S4,COUP3,VTMP)
      DO I = 3, 6
        V3(I) = V3(I) + VTMP(I)
      ENDDO
      CALL FFVS7P1N_3(F1,F2,S4,COUP4,VTMP)
      DO I = 3, 6
        V3(I) = V3(I) + VTMP(I)
      ENDDO
      CALL FFVS9P1N_3(F1,F2,S4,COUP5,VTMP)
      DO I = 3, 6
        V3(I) = V3(I) + VTMP(I)
      ENDDO
      END


