C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVS3P1N_4(F1, F2, V3, COUP,S4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(3)
      COMPLEX*16 TMP24
      COMPLEX*16 TMP8
      COMPLEX*16 V3(*)
      S4(1) = +F1(1)+F2(1)+V3(1)
      S4(2) = +F1(2)+F2(2)+V3(2)
      P4(0) = -DBLE(S4(1))
      P4(1) = -DBLE(S4(2))
      P4(2) = -DIMAG(S4(2))
      P4(3) = -DIMAG(S4(1))
      TMP24 = (V3(3)*P4(0)-V3(4)*P4(1)-V3(5)*P4(2)-V3(6)*P4(3))
      TMP8 = (F2(5)*F1(5)+F2(6)*F1(6))
      S4(3)= COUP*(-CI )* TMP24*TMP8
      END


