C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjM(2,1) - P(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVS4P1N_1(F2, V3, S4, COUP,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 TMP13
      COMPLEX*16 V3(*)
      P4(0) = DBLE(S4(1))
      P4(1) = DBLE(S4(2))
      P4(2) = DIMAG(S4(2))
      P4(3) = DIMAG(S4(1))
      TMP13 = (V3(3)*P4(0)-V3(4)*P4(1)-V3(5)*P4(2)-V3(6)*P4(3))
      F1(3)= COUP*(-CI )* TMP13*F2(3)*S4(3)
      F1(4)= COUP*(-CI )* TMP13*F2(4)*S4(3)
      F1(5)= COUP*CI * TMP13*F2(5)*S4(3)
      F1(6)= COUP*CI * TMP13*F2(6)*S4(3)
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjM(2,1) - P(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVS4_5_6_8P1N_1(F2, V3, S4, COUP1, COUP2, COUP3,
     $  COUP4,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      COMPLEX*16 FTMP(6)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 V3(*)
      INTEGER*4 I
      CALL FFVS4P1N_1(F2,V3,S4,COUP1,F1)
      CALL FFVS5P1N_1(F2,V3,S4,COUP2,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVS6P1N_1(F2,V3,S4,COUP3,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVS8P1N_1(F2,V3,S4,COUP4,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjM(2,1) - P(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVS4_8_10P1N_1(F2, V3, S4, COUP1, COUP2, COUP3,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      COMPLEX*16 FTMP(6)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 V3(*)
      INTEGER*4 I
      CALL FFVS4P1N_1(F2,V3,S4,COUP1,F1)
      CALL FFVS8P1N_1(F2,V3,S4,COUP2,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVS10P1N_1(F2,V3,S4,COUP3,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      END


