C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVS1P1N_4(F1, F2, V3, COUP,S4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(3)
      COMPLEX*16 TMP13
      COMPLEX*16 TMP14
      COMPLEX*16 V3(*)
      S4(1) = +F1(1)+F2(1)+V3(1)
      S4(2) = +F1(2)+F2(2)+V3(2)
      P4(0) = -DBLE(S4(1))
      P4(1) = -DBLE(S4(2))
      P4(2) = -DIMAG(S4(2))
      P4(3) = -DIMAG(S4(1))
      TMP13 = (V3(3)*P4(0)-V3(4)*P4(1)-V3(5)*P4(2)-V3(6)*P4(3))
      TMP14 = (F1(3)*F2(3)+F1(4)*F2(4))
      S4(3)= COUP*(-CI )* TMP13*TMP14
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVS1_2_3_7P1N_4(F1, F2, V3, COUP1, COUP2, COUP3,
     $  COUP4,S4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(3)
      COMPLEX*16 STMP(3)
      COMPLEX*16 V3(*)
      INTEGER*4 I
      CALL FFVS1P1N_4(F1,F2,V3,COUP1,S4)
      CALL FFVS2P1N_4(F1,F2,V3,COUP2,STMP)
      DO I = 3, 3
        S4(I) = S4(I) + STMP(I)
      ENDDO
      CALL FFVS3P1N_4(F1,F2,V3,COUP3,STMP)
      DO I = 3, 3
        S4(I) = S4(I) + STMP(I)
      ENDDO
      CALL FFVS7P1N_4(F1,F2,V3,COUP4,STMP)
      DO I = 3, 3
        S4(I) = S4(I) + STMP(I)
      ENDDO
      END


