C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjM(2,1) - P(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVS4P1N_3(F1, F2, S4, COUP,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 TMP7
      COMPLEX*16 TMP8
      COMPLEX*16 V3(6)
      P4(0) = DBLE(S4(1))
      P4(1) = DBLE(S4(2))
      P4(2) = DIMAG(S4(2))
      P4(3) = DIMAG(S4(1))
      TMP7 = (F2(3)*F1(3)+F2(4)*F1(4))
      TMP8 = (F2(5)*F1(5)+F2(6)*F1(6))
      V3(3)= COUP*P4(0)*S4(3)*(-CI*(TMP7)+CI*(TMP8))
      V3(4)= COUP*P4(1)*S4(3)*(+CI*(TMP7)-CI*(TMP8))
      V3(5)= COUP*P4(2)*S4(3)*(+CI*(TMP7)-CI*(TMP8))
      V3(6)= COUP*P4(3)*S4(3)*(+CI*(TMP7)-CI*(TMP8))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjM(2,1) - P(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVS4_5_6_8P1N_3(F1, F2, S4, COUP1, COUP2, COUP3,
     $  COUP4,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 V3(6)
      COMPLEX*16 VTMP(6)
      INTEGER*4 I
      CALL FFVS4P1N_3(F1,F2,S4,COUP1,V3)
      CALL FFVS5P1N_3(F1,F2,S4,COUP2,VTMP)
      DO I = 3, 6
        V3(I) = V3(I) + VTMP(I)
      ENDDO
      CALL FFVS6P1N_3(F1,F2,S4,COUP3,VTMP)
      DO I = 3, 6
        V3(I) = V3(I) + VTMP(I)
      ENDDO
      CALL FFVS8P1N_3(F1,F2,S4,COUP4,VTMP)
      DO I = 3, 6
        V3(I) = V3(I) + VTMP(I)
      ENDDO
      END


