C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVS1P1N_1(F2, V3, S4, COUP,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 TMP24
      COMPLEX*16 V3(*)
      P4(0) = DBLE(S4(1))
      P4(1) = DBLE(S4(2))
      P4(2) = DIMAG(S4(2))
      P4(3) = DIMAG(S4(1))
      TMP24 = (V3(3)*P4(0)-V3(4)*P4(1)-V3(5)*P4(2)-V3(6)*P4(3))
      F1(3)= COUP*(-CI )* TMP24*F2(3)*S4(3)
      F1(4)= COUP*(-CI )* TMP24*F2(4)*S4(3)
      F1(5)= COUP*0D0
      F1(6)= COUP*0D0
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVS1_2_3_7P1N_1(F2, V3, S4, COUP1, COUP2, COUP3,
     $  COUP4,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      COMPLEX*16 FTMP(6)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 V3(*)
      INTEGER*4 I
      CALL FFVS1P1N_1(F2,V3,S4,COUP1,F1)
      CALL FFVS2P1N_1(F2,V3,S4,COUP2,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVS3P1N_1(F2,V3,S4,COUP3,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVS7P1N_1(F2,V3,S4,COUP4,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVS1_2_3_7_9P1N_1(F2, V3, S4, COUP1, COUP2, COUP3,
     $  COUP4, COUP5,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      COMPLEX*16 FTMP(6)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 V3(*)
      INTEGER*4 I
      CALL FFVS1P1N_1(F2,V3,S4,COUP1,F1)
      CALL FFVS2P1N_1(F2,V3,S4,COUP2,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVS3P1N_1(F2,V3,S4,COUP3,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVS7P1N_1(F2,V3,S4,COUP4,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVS9P1N_1(F2,V3,S4,COUP5,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      END


