C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjM(2,1) + P(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVS5P1N_3(F1, F2, S4, COUP,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 TMP14
      COMPLEX*16 TMP3
      COMPLEX*16 V3(6)
      P4(0) = DBLE(S4(1))
      P4(1) = DBLE(S4(2))
      P4(2) = DIMAG(S4(2))
      P4(3) = DIMAG(S4(1))
      TMP14 = (F1(3)*F2(3)+F1(4)*F2(4))
      TMP3 = (F1(5)*F2(5)+F1(6)*F2(6))
      V3(3)= COUP*(-P4(0))*S4(3)*(+CI*(TMP14+TMP3))
      V3(4)= COUP*P4(1)*S4(3)*(+CI*(TMP14+TMP3))
      V3(5)= COUP*P4(2)*S4(3)*(+CI*(TMP14+TMP3))
      V3(6)= COUP*P4(3)*S4(3)*(+CI*(TMP14+TMP3))
      END


