C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjM(2,1) + P(3,4)*ProjP(2,1) +
C      -(P(-1,4)*Gamma(-1,2,-3)*Gamma(3,-3,-2)*ProjM(-2,1)) +
C      P(-1,4)*Gamma(-1,-3,-2)*Gamma(3,2,-3)*ProjM(-2,1) +
C      P(-1,4)*Gamma(-1,2,-3)*Gamma(3,-3,-2)*ProjP(-2,1) -
C      P(-1,4)*Gamma(-1,-3,-2)*Gamma(3,2,-3)*ProjP(-2,1)
C     
      SUBROUTINE FFVS10P1N_1(F2, V3, S4, COUP,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 TMP13
      COMPLEX*16 V3(*)
      P4(0) = DBLE(S4(1))
      P4(1) = DBLE(S4(2))
      P4(2) = DIMAG(S4(2))
      P4(3) = DIMAG(S4(1))
      TMP13 = (V3(3)*P4(0)-V3(4)*P4(1)-V3(5)*P4(2)-V3(6)*P4(3))
      F1(3)= COUP*2D0 * CI * S4(3)*(F2(4)*(P4(0)*(V3(4)+CI*(V3(5)))
     $ +(P4(1)*(-1D0)*(V3(3)+V3(6))+(P4(2)*(-1D0)*(+CI*(V3(3)+V3(6)))
     $ +P4(3)*(V3(4)+CI*(V3(5))))))-F2(3)*(V3(3)*P4(3)-CI*(V3(4)*P4(2))
     $ +CI*(V3(5)*P4(1))-V3(6)*P4(0)+1D0/2D0*(TMP13)))
      F1(4)= COUP*2D0 * CI * S4(3)*(F2(3)*(P4(0)*(V3(4)-CI*(V3(5)))
     $ +(P4(1)*(-V3(3)+V3(6))+(P4(2)*(+CI*(V3(3))-CI*(V3(6)))+P4(3)*(
     $ -V3(4)+CI*(V3(5))))))-F2(4)*(-V3(3)*P4(3)+CI*(V3(4)*P4(2))-CI
     $ *(V3(5)*P4(1))+V3(6)*P4(0)+1D0/2D0*(TMP13)))
      F1(5)= COUP*(-2D0 )* CI * S4(3)*(F2(6)*(P4(0)*(-1D0)*(V3(4)+CI
     $ *(V3(5)))+(P4(1)*(V3(3)-V3(6))+(P4(2)*(+CI*(V3(3))-CI*(V3(6)))
     $ +P4(3)*(V3(4)+CI*(V3(5))))))+F2(5)*(V3(3)*P4(3)+CI*(V3(4)*P4(2))
     $ -CI*(V3(5)*P4(1))-V3(6)*P4(0)+1D0/2D0*(TMP13)))
      F1(6)= COUP*(-2D0 )* CI * S4(3)*(F2(5)*(P4(0)*(-V3(4)+CI*(V3(5)))
     $ +(P4(1)*(V3(3)+V3(6))+(P4(2)*(-1D0)*(+CI*(V3(3)+V3(6)))+P4(3)*(
     $ -V3(4)+CI*(V3(5))))))+F2(6)*(-V3(3)*P4(3)-CI*(V3(4)*P4(2))+CI
     $ *(V3(5)*P4(1))+V3(6)*P4(0)+1D0/2D0*(TMP13)))
      END


