C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjM(2,1) - P(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVS4_0(F1, F2, V3, S4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 TMP24
      COMPLEX*16 TMP7
      COMPLEX*16 TMP8
      COMPLEX*16 V3(*)
      COMPLEX*16 VERTEX
      P4(0) = DBLE(S4(1))
      P4(1) = DBLE(S4(2))
      P4(2) = DIMAG(S4(2))
      P4(3) = DIMAG(S4(1))
      TMP24 = (V3(3)*P4(0)-V3(4)*P4(1)-V3(5)*P4(2)-V3(6)*P4(3))
      TMP7 = (F2(3)*F1(3)+F2(4)*F1(4))
      TMP8 = (F2(5)*F1(5)+F2(6)*F1(6))
      VERTEX = COUP*S4(3)*TMP24*(-CI*(TMP7)+CI*(TMP8))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,4)*ProjM(2,1) - P(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVS4_5_6_8_0(F1, F2, V3, S4, COUP1, COUP2, COUP3,
     $  COUP4,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 TMP
      COMPLEX*16 VERTEX
      CALL FFVS4_0(F1,F2,V3,S4,COUP1,VERTEX)
      CALL FFVS5_0(F1,F2,V3,S4,COUP2,TMP)
      VERTEX = VERTEX + TMP
      CALL FFVS6_0(F1,F2,V3,S4,COUP3,TMP)
      VERTEX = VERTEX + TMP
      CALL FFVS8_0(F1,F2,V3,S4,COUP4,TMP)
      VERTEX = VERTEX + TMP
      END


