C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -(P(-1,4)*Gamma(-1,2,-3)*Gamma(3,-3,-2)*ProjP(-2,1)) +
C      P(-1,4)*Gamma(-1,-3,-2)*Gamma(3,2,-3)*ProjP(-2,1)
C     
      SUBROUTINE FFVS7P1N_3(F1, F2, S4, COUP,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 P4(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 V3(6)
      P4(0) = DBLE(S4(1))
      P4(1) = DBLE(S4(2))
      P4(2) = DIMAG(S4(2))
      P4(3) = DIMAG(S4(1))
      V3(3)= COUP*2D0 * CI * S4(3)*(F1(5)*(F2(6)*(P4(1)+CI*(P4(2)))
     $ +F2(5)*P4(3))+F1(6)*(F2(5)*(P4(1)-CI*(P4(2)))-F2(6)*P4(3)))
      V3(4)= COUP*(-2D0 )* CI * S4(3)*(F1(5)*(F2(6)*(P4(0)-P4(3))-CI
     $ *(F2(5)*P4(2)))+F1(6)*(F2(5)*(P4(0)+P4(3))+CI*(F2(6)*P4(2))))
      V3(5)= COUP*(-2D0 )* S4(3)*(F1(5)*(F2(6)*(-P4(0)+P4(3))-F2(5)
     $ *P4(1))+F1(6)*(F2(5)*(P4(0)+P4(3))+F2(6)*P4(1)))
      V3(6)= COUP*(-2D0 )* CI * S4(3)*(F1(5)*(F2(6)*(P4(1)+CI*(P4(2)))
     $ +F2(5)*P4(0))+F1(6)*(F2(5)*(-P4(1)+CI*(P4(2)))-F2(6)*P4(0)))
      END


