C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -(P(-1,3)*Gamma(-1,2,-2)*Metric(3,4)*ProjP(-2,1)) +
C      P(4,3)*Gamma(3,2,-1)*ProjP(-1,1)
C     
      SUBROUTINE FFVV18P1N_1(F2, V3, V4, COUP,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      REAL*8 P3(0:3)
      COMPLEX*16 TMP11
      COMPLEX*16 TMP2
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      P3(0) = DBLE(V3(1))
      P3(1) = DBLE(V3(2))
      P3(2) = DIMAG(V3(2))
      P3(3) = DIMAG(V3(1))
      TMP11 = (V4(3)*P3(0)-V4(4)*P3(1)-V4(5)*P3(2)-V4(6)*P3(3))
      TMP2 = (V4(3)*V3(3)-V4(4)*V3(4)-V4(5)*V3(5)-V4(6)*V3(6))
      F1(3)= COUP*0D0
      F1(4)= COUP*0D0
      F1(5)= COUP*CI*(F2(3)*(TMP11*(-V3(3)+V3(6))+TMP2*(P3(0)-P3(3)))
     $ +F2(4)*(TMP11*(V3(4)+CI*(V3(5)))-TMP2*(P3(1)+CI*(P3(2)))))
      F1(6)= COUP*CI*(F2(3)*(TMP11*(V3(4)-CI*(V3(5)))+TMP2*(-P3(1)+CI
     $ *(P3(2))))+F2(4)*(TMP11*(-1D0)*(V3(3)+V3(6))+TMP2*(P3(0)+P3(3)))
     $ )
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -(P(-1,3)*Gamma(-1,2,-2)*Metric(3,4)*ProjP(-2,1)) +
C      P(4,3)*Gamma(3,2,-1)*ProjP(-1,1)
C     
      SUBROUTINE FFVV18_7P1N_1(F2, V3, V4, COUP1, COUP2,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      COMPLEX*16 FTMP(6)
      REAL*8 P3(0:3)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      INTEGER*4 I
      CALL FFVV18P1N_1(F2,V3,V4,COUP1,F1)
      CALL FFVV7P1N_1(F2,V3,V4,COUP2,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      END


