C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-2)*Gamma(4,-2,-1)*ProjP(-1,1) -
C      Gamma(3,-2,-1)*Gamma(4,2,-2)*ProjP(-1,1)
C     
      SUBROUTINE FFVV16P1N_4(F1, F2, V3, COUP,V4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(6)
      V4(3)= COUP*(-2D0 * CI)*(F1(5)*(F2(6)*(V3(4)+CI*(V3(5)))+F2(5)
     $ *V3(6))+F1(6)*(F2(5)*(V3(4)-CI*(V3(5)))-F2(6)*V3(6)))
      V4(4)= COUP*2D0 * CI*(F1(5)*(F2(6)*(V3(3)-V3(6))-CI*(F2(5)*V3(5))
     $ )+F1(6)*(F2(5)*(V3(3)+V3(6))+CI*(F2(6)*V3(5))))
      V4(5)= COUP*2D0*(F1(5)*(F2(6)*(-V3(3)+V3(6))-F2(5)*V3(4))+F1(6)
     $ *(F2(5)*(V3(3)+V3(6))+F2(6)*V3(4)))
      V4(6)= COUP*2D0 * CI*(F1(5)*(F2(6)*(V3(4)+CI*(V3(5)))+F2(5)*V3(3)
     $ )+F1(6)*(F2(5)*(-V3(4)+CI*(V3(5)))-F2(6)*V3(3)))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-2)*Gamma(4,-2,-1)*ProjP(-1,1) -
C      Gamma(3,-2,-1)*Gamma(4,2,-2)*ProjP(-1,1)
C     
      SUBROUTINE FFVV16_9P1N_4(F1, F2, V3, COUP1, COUP2,V4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(6)
      COMPLEX*16 VTMP(6)
      INTEGER*4 I
      CALL FFVV16P1N_4(F1,F2,V3,COUP1,V4)
      CALL FFVV9P1N_4(F1,F2,V3,COUP2,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      END


