C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1) - Metric(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVV10P1N_4(F1, F2, V3, COUP,V4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP7
      COMPLEX*16 TMP8
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(6)
      TMP7 = (F2(3)*F1(3)+F2(4)*F1(4))
      TMP8 = (F2(5)*F1(5)+F2(6)*F1(6))
      V4(3)= COUP*V3(3)*(-CI*(TMP7)+CI*(TMP8))
      V4(4)= COUP*V3(4)*(+CI*(TMP7)-CI*(TMP8))
      V4(5)= COUP*V3(5)*(+CI*(TMP7)-CI*(TMP8))
      V4(6)= COUP*V3(6)*(+CI*(TMP7)-CI*(TMP8))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1) - Metric(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVV10_11_15_17_19_8P1N_4(F1, F2, V3, COUP1, COUP2,
     $  COUP3, COUP4, COUP5, COUP6,V4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 COUP6
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(6)
      COMPLEX*16 VTMP(6)
      INTEGER*4 I
      CALL FFVV10P1N_4(F1,F2,V3,COUP1,V4)
      CALL FFVV11P1N_4(F1,F2,V3,COUP2,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      CALL FFVV15P1N_4(F1,F2,V3,COUP3,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      CALL FFVV17P1N_4(F1,F2,V3,COUP4,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      CALL FFVV19P1N_4(F1,F2,V3,COUP5,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      CALL FFVV8P1N_4(F1,F2,V3,COUP6,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      END


