C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVV1P1N_1(F2, V3, V4, COUP,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP18
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      TMP18 = (V3(3)*V4(3)-V3(4)*V4(4)-V3(5)*V4(5)-V3(6)*V4(6))
      F1(3)= COUP*(-CI )* TMP18*F2(3)
      F1(4)= COUP*(-CI )* TMP18*F2(4)
      F1(5)= COUP*0D0
      F1(6)= COUP*0D0
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVV1_16_19_5_8_9P1N_1(F2, V3, V4, COUP1, COUP2,
     $  COUP3, COUP4, COUP5, COUP6,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 COUP6
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      COMPLEX*16 FTMP(6)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      INTEGER*4 I
      CALL FFVV1P1N_1(F2,V3,V4,COUP1,F1)
      CALL FFVV16P1N_1(F2,V3,V4,COUP2,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVV19P1N_1(F2,V3,V4,COUP3,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVV5P1N_1(F2,V3,V4,COUP4,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVV8P1N_1(F2,V3,V4,COUP5,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVV9P1N_1(F2,V3,V4,COUP6,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVV1_14_4_6_9P1N_1(F2, V3, V4, COUP1, COUP2, COUP3,
     $  COUP4, COUP5,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 COUP6
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      COMPLEX*16 FTMP(6)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      INTEGER*4 I
      CALL FFVV1P1N_1(F2,V3,V4,COUP1,F1)
      CALL FFVV14P1N_1(F2,V3,V4,COUP2,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVV4P1N_1(F2,V3,V4,COUP3,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVV6P1N_1(F2,V3,V4,COUP4,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVV9P1N_1(F2,V3,V4,COUP5,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVV1_14_4_5_6_9P1N_1(F2, V3, V4, COUP1, COUP2, COUP3
     $ , COUP4, COUP5, COUP6,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 COUP6
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      COMPLEX*16 FTMP(6)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      INTEGER*4 I
      CALL FFVV1P1N_1(F2,V3,V4,COUP1,F1)
      CALL FFVV14P1N_1(F2,V3,V4,COUP2,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVV4P1N_1(F2,V3,V4,COUP3,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVV5P1N_1(F2,V3,V4,COUP4,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVV6P1N_1(F2,V3,V4,COUP5,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVV9P1N_1(F2,V3,V4,COUP6,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVV1_16_5_9P1N_1(F2, V3, V4, COUP1, COUP2, COUP3,
     $  COUP4,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 COUP6
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      COMPLEX*16 FTMP(6)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      INTEGER*4 I
      CALL FFVV1P1N_1(F2,V3,V4,COUP1,F1)
      CALL FFVV16P1N_1(F2,V3,V4,COUP2,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVV5P1N_1(F2,V3,V4,COUP3,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFVV9P1N_1(F2,V3,V4,COUP4,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVV1_5P1N_1(F2, V3, V4, COUP1, COUP2,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 COUP6
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      COMPLEX*16 FTMP(6)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      INTEGER*4 I
      CALL FFVV1P1N_1(F2,V3,V4,COUP1,F1)
      CALL FFVV5P1N_1(F2,V3,V4,COUP2,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      END


