C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVV9P1N_4(F1, F2, V3, COUP,V4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP3
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(6)
      TMP3 = (F1(5)*F2(5)+F1(6)*F2(6))
      V4(3)= COUP*(-CI )* V3(3)*TMP3
      V4(4)= COUP*CI * V3(4)*TMP3
      V4(5)= COUP*CI * V3(5)*TMP3
      V4(6)= COUP*CI * V3(6)*TMP3
      END


