C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -(P(-1,4)*Gamma(-1,2,-2)*Metric(3,4)*ProjP(-2,1)) +
C      P(3,4)*Gamma(4,2,-1)*ProjP(-1,1)
C     
      SUBROUTINE FFVV19_0(F1, F2, V3, V4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 P4(0:3)
      COMPLEX*16 TMP13
      COMPLEX*16 TMP2
      COMPLEX*16 TMP34
      COMPLEX*16 TMP35
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      COMPLEX*16 VERTEX
      P4(0) = DBLE(V4(1))
      P4(1) = DBLE(V4(2))
      P4(2) = DIMAG(V4(2))
      P4(3) = DIMAG(V4(1))
      TMP13 = (V3(3)*P4(0)-V3(4)*P4(1)-V3(5)*P4(2)-V3(6)*P4(3))
      TMP2 = (V4(3)*V3(3)-V4(4)*V3(4)-V4(5)*V3(5)-V4(6)*V3(6))
      TMP34 = (F1(5)*(F2(3)*(P4(0)-P4(3))-F2(4)*(P4(1)+CI*(P4(2))))
     $ +F1(6)*(F2(3)*(-P4(1)+CI*(P4(2)))+F2(4)*(P4(0)+P4(3))))
      TMP35 = (F1(5)*(F2(3)*(V4(3)-V4(6))-F2(4)*(V4(4)+CI*(V4(5))))
     $ +F1(6)*(F2(3)*(-V4(4)+CI*(V4(5)))+F2(4)*(V4(3)+V4(6))))
      VERTEX = COUP*(+CI*(TMP2*TMP34)-CI*(TMP13*TMP35))
      END


