C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVV9P1N_1(F2, V3, V4, COUP,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP2
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      TMP2 = (V4(3)*V3(3)-V4(4)*V3(4)-V4(5)*V3(5)-V4(6)*V3(6))
      F1(3)= COUP*0D0
      F1(4)= COUP*0D0
      F1(5)= COUP*(-CI )* TMP2*F2(5)
      F1(6)= COUP*(-CI )* TMP2*F2(6)
      END


