C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -(P(-1,3)*Gamma(-1,2,-2)*Metric(3,4)*ProjM(-2,1)) +
C      P(4,3)*Gamma(3,2,-1)*ProjM(-1,1)
C     
      SUBROUTINE FFVV7P1N_3(F1, F2, V4, COUP,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 P3(0:3)
      COMPLEX*16 TMP10
      COMPLEX*16 TMP11
      COMPLEX*16 V3(6)
      COMPLEX*16 V4(*)
      V3(1) = +F1(1)+F2(1)+V4(1)
      V3(2) = +F1(2)+F2(2)+V4(2)
      P3(0) = -DBLE(V3(1))
      P3(1) = -DBLE(V3(2))
      P3(2) = -DIMAG(V3(2))
      P3(3) = -DIMAG(V3(1))
      TMP10 = (F1(3)*(F2(5)*(P3(0)+P3(3))+F2(6)*(P3(1)+CI*(P3(2))))
     $ +F1(4)*(F2(5)*(P3(1)-CI*(P3(2)))+F2(6)*(P3(0)-P3(3))))
      TMP11 = (V4(3)*P3(0)-V4(4)*P3(1)-V4(5)*P3(2)-V4(6)*P3(3))
      V3(3)= COUP*(-CI)*(TMP11*(F1(3)*F2(5)+F1(4)*F2(6))-V4(3)*TMP10)
      V3(4)= COUP*(-CI)*(TMP11*(F1(3)*F2(6)+F1(4)*F2(5))+V4(4)*TMP10)
      V3(5)= COUP*(-CI)*(TMP11*(+CI*(F1(3)*F2(6))-CI*(F1(4)*F2(5)))
     $ +V4(5)*TMP10)
      V3(6)= COUP*(-CI)*(TMP11*(F1(3)*F2(5)-F1(4)*F2(6))+V4(6)*TMP10)
      END


