C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-2)*Gamma(4,-2,-1)*ProjP(-1,1) -
C      Gamma(3,-2,-1)*Gamma(4,2,-2)*ProjP(-1,1)
C     
      SUBROUTINE FFVV16P1N_1(F2, V3, V4, COUP,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      F1(3)= COUP*0D0
      F1(4)= COUP*0D0
      F1(5)= COUP*(-2D0 * CI)*(F2(6)*(V3(3)*(-1D0)*(V4(4)+CI*(V4(5)))
     $ +(V3(4)*(V4(3)-V4(6))+(V3(5)*(+CI*(V4(3))-CI*(V4(6)))+V3(6)
     $ *(V4(4)+CI*(V4(5))))))+F2(5)*(-V4(6)*V3(3)-CI*(V4(5)*V3(4))+CI
     $ *(V4(4)*V3(5))+V4(3)*V3(6)))
      F1(6)= COUP*(-2D0 * CI)*(F2(5)*(V3(3)*(-V4(4)+CI*(V4(5)))+(V3(4)
     $ *(V4(3)+V4(6))+(V3(5)*(-1D0)*(+CI*(V4(3)+V4(6)))+V3(6)*(-V4(4)
     $ +CI*(V4(5))))))+F2(6)*(V4(6)*V3(3)+CI*(V4(5)*V3(4))-CI*(V4(4)
     $ *V3(5))-V4(3)*V3(6)))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-2)*Gamma(4,-2,-1)*ProjP(-1,1) -
C      Gamma(3,-2,-1)*Gamma(4,2,-2)*ProjP(-1,1)
C     
      SUBROUTINE FFVV16_9P1N_1(F2, V3, V4, COUP1, COUP2,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      COMPLEX*16 FTMP(6)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      INTEGER*4 I
      CALL FFVV16P1N_1(F2,V3,V4,COUP1,F1)
      CALL FFVV9P1N_1(F2,V3,V4,COUP2,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      END


