C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1) - Metric(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVV10_0(F1, F2, V3, V4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP14
      COMPLEX*16 TMP2
      COMPLEX*16 TMP3
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      COMPLEX*16 VERTEX
      TMP14 = (F1(3)*F2(3)+F1(4)*F2(4))
      TMP2 = (V4(3)*V3(3)-V4(4)*V3(4)-V4(5)*V3(5)-V4(6)*V3(6))
      TMP3 = (F1(5)*F2(5)+F1(6)*F2(6))
      VERTEX = COUP*TMP2*(-CI*(TMP14)+CI*(TMP3))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1) - Metric(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVV10_11_15_17_19_8_0(F1, F2, V3, V4, COUP1, COUP2,
     $  COUP3, COUP4, COUP5, COUP6,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 COUP6
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      COMPLEX*16 TMP
      COMPLEX*16 VERTEX
      CALL FFVV10_0(F1,F2,V3,V4,COUP1,VERTEX)
      CALL FFVV11_0(F1,F2,V3,V4,COUP2,TMP)
      VERTEX = VERTEX + TMP
      CALL FFVV15_0(F1,F2,V3,V4,COUP3,TMP)
      VERTEX = VERTEX + TMP
      CALL FFVV17_0(F1,F2,V3,V4,COUP4,TMP)
      VERTEX = VERTEX + TMP
      CALL FFVV19_0(F1,F2,V3,V4,COUP5,TMP)
      VERTEX = VERTEX + TMP
      CALL FFVV8_0(F1,F2,V3,V4,COUP6,TMP)
      VERTEX = VERTEX + TMP
      END


