C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1) + Metric(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVV11P1N_3(F1, F2, V4, COUP,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP7
      COMPLEX*16 TMP8
      COMPLEX*16 V3(6)
      COMPLEX*16 V4(*)
      TMP7 = (F2(3)*F1(3)+F2(4)*F1(4))
      TMP8 = (F2(5)*F1(5)+F2(6)*F1(6))
      V3(3)= COUP*(-V4(3))*(+CI*(TMP7+TMP8))
      V3(4)= COUP*V4(4)*(+CI*(TMP7+TMP8))
      V3(5)= COUP*V4(5)*(+CI*(TMP7+TMP8))
      V3(6)= COUP*V4(6)*(+CI*(TMP7+TMP8))
      END


