C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVV1P1N_4(F1, F2, V3, COUP,V4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP14
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(6)
      TMP14 = (F1(3)*F2(3)+F1(4)*F2(4))
      V4(3)= COUP*(-CI )* V3(3)*TMP14
      V4(4)= COUP*CI * V3(4)*TMP14
      V4(5)= COUP*CI * V3(5)*TMP14
      V4(6)= COUP*CI * V3(6)*TMP14
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVV1_16_5_9P1N_4(F1, F2, V3, COUP1, COUP2, COUP3,
     $  COUP4,V4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(6)
      COMPLEX*16 VTMP(6)
      INTEGER*4 I
      CALL FFVV1P1N_4(F1,F2,V3,COUP1,V4)
      CALL FFVV16P1N_4(F1,F2,V3,COUP2,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      CALL FFVV5P1N_4(F1,F2,V3,COUP3,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      CALL FFVV9P1N_4(F1,F2,V3,COUP4,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVV1_16_19_5_8_9P1N_4(F1, F2, V3, COUP1, COUP2,
     $  COUP3, COUP4, COUP5, COUP6,V4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 COUP6
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(6)
      COMPLEX*16 VTMP(6)
      INTEGER*4 I
      CALL FFVV1P1N_4(F1,F2,V3,COUP1,V4)
      CALL FFVV16P1N_4(F1,F2,V3,COUP2,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      CALL FFVV19P1N_4(F1,F2,V3,COUP3,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      CALL FFVV5P1N_4(F1,F2,V3,COUP4,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      CALL FFVV8P1N_4(F1,F2,V3,COUP5,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      CALL FFVV9P1N_4(F1,F2,V3,COUP6,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVV1_14_4_6_9P1N_4(F1, F2, V3, COUP1, COUP2, COUP3,
     $  COUP4, COUP5,V4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 COUP6
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(6)
      COMPLEX*16 VTMP(6)
      INTEGER*4 I
      CALL FFVV1P1N_4(F1,F2,V3,COUP1,V4)
      CALL FFVV14P1N_4(F1,F2,V3,COUP2,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      CALL FFVV4P1N_4(F1,F2,V3,COUP3,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      CALL FFVV6P1N_4(F1,F2,V3,COUP4,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      CALL FFVV9P1N_4(F1,F2,V3,COUP5,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1)
C     
      SUBROUTINE FFVV1_5P1N_4(F1, F2, V3, COUP1, COUP2,V4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 COUP6
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(6)
      COMPLEX*16 VTMP(6)
      INTEGER*4 I
      CALL FFVV1P1N_4(F1,F2,V3,COUP1,V4)
      CALL FFVV5P1N_4(F1,F2,V3,COUP2,VTMP)
      DO I = 3, 6
        V4(I) = V4(I) + VTMP(I)
      ENDDO
      END


