C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -(P(-1,4)*Gamma(-1,2,-2)*Metric(3,4)*ProjM(-2,1)) +
C      P(3,4)*Gamma(4,2,-1)*ProjM(-1,1)
C     
      SUBROUTINE FFVV8P1N_4(F1, F2, V3, COUP,V4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 P4(0:3)
      COMPLEX*16 TMP24
      COMPLEX*16 TMP26
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(6)
      V4(1) = +F1(1)+F2(1)+V3(1)
      V4(2) = +F1(2)+F2(2)+V3(2)
      P4(0) = -DBLE(V4(1))
      P4(1) = -DBLE(V4(2))
      P4(2) = -DIMAG(V4(2))
      P4(3) = -DIMAG(V4(1))
      TMP24 = (V3(3)*P4(0)-V3(4)*P4(1)-V3(5)*P4(2)-V3(6)*P4(3))
      TMP26 = (F1(3)*(F2(5)*(P4(0)+P4(3))+F2(6)*(P4(1)+CI*(P4(2))))
     $ +F1(4)*(F2(5)*(P4(1)-CI*(P4(2)))+F2(6)*(P4(0)-P4(3))))
      V4(3)= COUP*(-CI)*(TMP24*(F2(5)*F1(3)+F2(6)*F1(4))-V3(3)*TMP26)
      V4(4)= COUP*CI*(TMP24*(-1D0)*(F2(6)*F1(3)+F2(5)*F1(4))-V3(4)
     $ *TMP26)
      V4(5)= COUP*CI*(TMP24*(-CI*(F2(6)*F1(3))+CI*(F2(5)*F1(4)))-V3(5)
     $ *TMP26)
      V4(6)= COUP*CI*(TMP24*(-F2(5)*F1(3)+F2(6)*F1(4))-V3(6)*TMP26)
      END


