C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1) + Metric(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVV11P1N_2(F1, V3, V4, COUP,F2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(6)
      COMPLEX*16 TMP2
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      TMP2 = (V4(3)*V3(3)-V4(4)*V3(4)-V4(5)*V3(5)-V4(6)*V3(6))
      F2(3)= COUP*(-CI )* TMP2*F1(3)
      F2(4)= COUP*(-CI )* TMP2*F1(4)
      F2(5)= COUP*(-CI )* TMP2*F1(5)
      F2(6)= COUP*(-CI )* TMP2*F1(6)
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(3,4)*ProjM(2,1) + Metric(3,4)*ProjP(2,1)
C     
      SUBROUTINE FFVV11_15_19_8_110P1N_2(F1, V3, V4, COUP1, COUP2,
     $  COUP3, COUP4, COUP5,F2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(6)
      COMPLEX*16 FTMP(6)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      INTEGER*4 I
      CALL FFVV11P1N_2(F1,V3,V4,COUP1,F2)
      CALL FFVV15P1N_2(F1,V3,V4,COUP2,FTMP)
      DO I = 3, 6
        F2(I) = F2(I) + FTMP(I)
      ENDDO
      CALL FFVV19P1N_2(F1,V3,V4,COUP3,FTMP)
      DO I = 3, 6
        F2(I) = F2(I) + FTMP(I)
      ENDDO
      CALL FFVV8P1N_2(F1,V3,V4,COUP4,FTMP)
      DO I = 3, 6
        F2(I) = F2(I) + FTMP(I)
      ENDDO
      CALL FFVV110P1N_2(F1,V3,V4,COUP5,FTMP)
      DO I = 3, 6
        F2(I) = F2(I) + FTMP(I)
      ENDDO
      END


