C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,2)*P(2,3) - P(-1,2)*P(-1,3)*Metric(1,2)
C     
      SUBROUTINE VVS3_1(V2, S3, COUP, M1, W1,V1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 M1
      REAL*8 OM1
      REAL*8 P1(0:3)
      REAL*8 P2(0:3)
      REAL*8 P3(0:3)
      COMPLEX*16 S3(*)
      COMPLEX*16 TMP0
      COMPLEX*16 TMP11
      COMPLEX*16 TMP32
      COMPLEX*16 TMP9
      COMPLEX*16 V1(6)
      COMPLEX*16 V2(*)
      REAL*8 W1
      COMPLEX*16 DENOM
      OM1 = 0D0
      IF (M1.NE.0D0) OM1=1D0/M1**2
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      P3(0) = DBLE(S3(1))
      P3(1) = DBLE(S3(2))
      P3(2) = DIMAG(S3(2))
      P3(3) = DIMAG(S3(1))
      V1(1) = +V2(1)+S3(1)
      V1(2) = +V2(2)+S3(2)
      P1(0) = -DBLE(V1(1))
      P1(1) = -DBLE(V1(2))
      P1(2) = -DIMAG(V1(2))
      P1(3) = -DIMAG(V1(1))
      TMP0 = (V2(3)*P1(0)-V2(4)*P1(1)-V2(5)*P1(2)-V2(6)*P1(3))
      TMP11 = (P2(0)*P3(0)-P2(1)*P3(1)-P2(2)*P3(2)-P2(3)*P3(3))
      TMP32 = (P1(0)*P2(0)-P1(1)*P2(1)-P1(2)*P2(2)-P1(3)*P2(3))
      TMP9 = (V2(3)*P3(0)-V2(4)*P3(1)-V2(5)*P3(2)-V2(6)*P3(3))
      DENOM = COUP/(P1(0)**2-P1(1)**2-P1(2)**2-P1(3)**2 - M1 * (M1 -CI
     $ * W1))
      V1(3)= DENOM*S3(3)*(OM1*P1(0)*(+CI*(TMP9*TMP32)-CI*(TMP0*TMP11))
     $ +(-CI*(P2(0)*TMP9)+CI*(V2(3)*TMP11)))
      V1(4)= DENOM*S3(3)*(OM1*P1(1)*(+CI*(TMP9*TMP32)-CI*(TMP0*TMP11))
     $ +(-CI*(P2(1)*TMP9)+CI*(V2(4)*TMP11)))
      V1(5)= DENOM*S3(3)*(OM1*P1(2)*(+CI*(TMP9*TMP32)-CI*(TMP0*TMP11))
     $ +(-CI*(P2(2)*TMP9)+CI*(V2(5)*TMP11)))
      V1(6)= DENOM*S3(3)*(OM1*P1(3)*(+CI*(TMP9*TMP32)-CI*(TMP0*TMP11))
     $ +(-CI*(P2(3)*TMP9)+CI*(V2(6)*TMP11)))
      END


