C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,2)*P(2,3) - P(-1,2)*P(-1,3)*Metric(1,2)
C     
      SUBROUTINE VVS3P1N_1(V2, S3, COUP,V1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 P2(0:3)
      REAL*8 P3(0:3)
      COMPLEX*16 S3(*)
      COMPLEX*16 TMP4
      COMPLEX*16 TMP8
      COMPLEX*16 V1(6)
      COMPLEX*16 V2(*)
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      P3(0) = DBLE(S3(1))
      P3(1) = DBLE(S3(2))
      P3(2) = DIMAG(S3(2))
      P3(3) = DIMAG(S3(1))
      TMP4 = (V2(3)*P3(0)-V2(4)*P3(1)-V2(5)*P3(2)-V2(6)*P3(3))
      TMP8 = (P3(0)*P2(0)-P3(1)*P2(1)-P3(2)*P2(2)-P3(3)*P2(3))
      V1(3)= COUP*S3(3)*(-CI*(P2(0)*TMP4)+CI*(V2(3)*TMP8))
      V1(4)= COUP*S3(3)*(+CI*(P2(1)*TMP4)-CI*(V2(4)*TMP8))
      V1(5)= COUP*S3(3)*(+CI*(P2(2)*TMP4)-CI*(V2(5)*TMP8))
      V1(6)= COUP*S3(3)*(+CI*(P2(3)*TMP4)-CI*(V2(6)*TMP8))
      END


