C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,3)*P(2,1) + P(1,4)*P(2,1) - P(-1,1)*P(-1,3)*Metric(1,2) -
C      P(-1,1)*P(-1,4)*Metric(1,2)
C     
      SUBROUTINE VVSS2_0(V1, V2, S3, S4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 P1(0:3)
      REAL*8 P3(0:3)
      REAL*8 P4(0:3)
      COMPLEX*16 S3(*)
      COMPLEX*16 S4(*)
      COMPLEX*16 TMP0
      COMPLEX*16 TMP1
      COMPLEX*16 TMP13
      COMPLEX*16 TMP14
      COMPLEX*16 TMP15
      COMPLEX*16 TMP16
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      COMPLEX*16 VERTEX
      P1(0) = DBLE(V1(1))
      P1(1) = DBLE(V1(2))
      P1(2) = DIMAG(V1(2))
      P1(3) = DIMAG(V1(1))
      P3(0) = DBLE(S3(1))
      P3(1) = DBLE(S3(2))
      P3(2) = DIMAG(S3(2))
      P3(3) = DIMAG(S3(1))
      P4(0) = DBLE(S4(1))
      P4(1) = DBLE(S4(2))
      P4(2) = DIMAG(S4(2))
      P4(3) = DIMAG(S4(1))
      TMP0 = (V2(3)*P1(0)-V2(4)*P1(1)-V2(5)*P1(2)-V2(6)*P1(3))
      TMP1 = (V2(3)*V1(3)-V2(4)*V1(4)-V2(5)*V1(5)-V2(6)*V1(6))
      TMP13 = (V1(3)*P3(0)-V1(4)*P3(1)-V1(5)*P3(2)-V1(6)*P3(3))
      TMP14 = (P1(0)*P3(0)-P1(1)*P3(1)-P1(2)*P3(2)-P1(3)*P3(3))
      TMP15 = (V1(3)*P4(0)-V1(4)*P4(1)-V1(5)*P4(2)-V1(6)*P4(3))
      TMP16 = (P1(0)*P4(0)-P1(1)*P4(1)-P1(2)*P4(2)-P1(3)*P4(3))
      VERTEX = COUP*S3(3)*S4(3)*(TMP0*(-1D0)*(+CI*(TMP13+TMP15))+TMP1
     $ *(+CI*(TMP14+TMP16)))
      END


