C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,1)*Metric(1,2) - P(2,1)*Metric(1,3)
C     
      SUBROUTINE VVV1P1N_2(V1, V3, COUP,V2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 P1(0:3)
      COMPLEX*16 TMP2
      COMPLEX*16 TMP4
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(6)
      COMPLEX*16 V3(*)
      P1(0) = DBLE(V1(1))
      P1(1) = DBLE(V1(2))
      P1(2) = DIMAG(V1(2))
      P1(3) = DIMAG(V1(1))
      TMP2 = (P1(0)*V3(3)-P1(1)*V3(4)-P1(2)*V3(5)-P1(3)*V3(6))
      TMP4 = (V1(3)*V3(3)-V1(4)*V3(4)-V1(5)*V3(5)-V1(6)*V3(6))
      V2(3)= COUP*(-CI*(V1(3)*TMP2)+CI*(P1(0)*TMP4))
      V2(4)= COUP*(+CI*(V1(4)*TMP2)-CI*(P1(1)*TMP4))
      V2(5)= COUP*(+CI*(V1(5)*TMP2)-CI*(P1(2)*TMP4))
      V2(6)= COUP*(+CI*(V1(6)*TMP2)-CI*(P1(3)*TMP4))
      END


