C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,1)*Metric(1,2) - P(2,1)*Metric(1,3)
C     
      SUBROUTINE VVVS1P1N_1(V2, V3, S4, COUP,V1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 P1(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 TMP19
      COMPLEX*16 TMP21
      COMPLEX*16 V1(6)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      V1(1) = +V2(1)+V3(1)+S4(1)
      V1(2) = +V2(2)+V3(2)+S4(2)
      P1(0) = -DBLE(V1(1))
      P1(1) = -DBLE(V1(2))
      P1(2) = -DIMAG(V1(2))
      P1(3) = -DIMAG(V1(1))
      TMP19 = (V3(3)*P1(0)-V3(4)*P1(1)-V3(5)*P1(2)-V3(6)*P1(3))
      TMP21 = (V2(3)*P1(0)-V2(4)*P1(1)-V2(5)*P1(2)-V2(6)*P1(3))
      V1(3)= COUP*S4(3)*(-CI*(V2(3)*TMP19)+CI*(V3(3)*TMP21))
      V1(4)= COUP*S4(3)*(+CI*(V2(4)*TMP19)-CI*(V3(4)*TMP21))
      V1(5)= COUP*S4(3)*(+CI*(V2(5)*TMP19)-CI*(V3(5)*TMP21))
      V1(6)= COUP*S4(3)*(+CI*(V2(6)*TMP19)-CI*(V3(6)*TMP21))
      END


