ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_general_MwScheme_UFO-zfac'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_6361 = ', GC_6361
      WRITE(*,2) 'GC_6504 = ', GC_6504
      WRITE(*,2) 'GC_6506 = ', GC_6506
      WRITE(*,2) 'GC_6738 = ', GC_6738
      WRITE(*,2) 'GC_7005 = ', GC_7005
      WRITE(*,2) 'GC_7007 = ', GC_7007
      WRITE(*,2) 'GC_6204 = ', GC_6204
      WRITE(*,2) 'GC_6206 = ', GC_6206
