ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of VectorSinglet_d6_UFO_HC_extended-Zfac'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_179 = ', GC_179
      WRITE(*,2) 'GC_184 = ', GC_184
      WRITE(*,2) 'GC_246 = ', GC_246
      WRITE(*,2) 'GC_248 = ', GC_248
