ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_general_MwScheme_UFO-zfac'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_6361 = ', GC_6361
      WRITE(*,2) 'GC_6528 = ', GC_6528
      WRITE(*,2) 'GC_6530 = ', GC_6530
      WRITE(*,2) 'GC_6738 = ', GC_6738
      WRITE(*,2) 'GC_7029 = ', GC_7029
      WRITE(*,2) 'GC_7031 = ', GC_7031
      WRITE(*,2) 'GC_5264 = ', GC_5264
      WRITE(*,2) 'GC_5266 = ', GC_5266
