      SUBROUTINE SMATRIX(P, RHEL, RCOL, DUM, IVEC, ANS, SELECTED_HEL,
     $  SELECTED_COL)
C     
C     Generated by MadGraph5_aMC@NLO v. 3.6.3, 2025-06-12
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO for Madevent Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: z > w+ ve~ e- @1
C     *   Decay: w+ > mu+ vm NPcHe=0 NPcHl1=0 NPcHl3=0 NPceB=0 NPceH=0
C      NPceW<=1
C     
      USE DISCRETESAMPLER
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE '../../Source/vector.inc'
      INCLUDE 'genps.inc'
      INCLUDE 'maxconfigs.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      INCLUDE 'run.inc'
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=48)
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=130)
      INTEGER    NDIAGS
      PARAMETER (NDIAGS=130)
      INTEGER    THEL
      PARAMETER (THEL=NCOMB)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      REAL*8 RHEL, RCOL
      INTEGER DUM, SELECTED_HEL, SELECTED_COL, IVEC
C     
C     global (due to reading writting)
C     
      LOGICAL GOODHEL(NCOMB)
      INTEGER NTRY
      COMMON/BLOCK_GOODHEL/NTRY,GOODHEL
      INTEGER NB_SPIN_STATE(2)
      DATA  NB_SPIN_STATE /3,0/
      COMMON /NB_HEL_STATE/ NB_SPIN_STATE
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB)
      REAL*8 T,MATRIX
      REAL*8 R,SUMHEL,TS(NCOMB)
      INTEGER I,IDEN
      INTEGER IPROC,JC(NEXTERNAL),II
      REAL*8 HWGT, XTOT, XTRY, XREJ, XR, YFRAC(0:NCOMB)
      INTEGER IDUM, NGOOD, J, JJ
      REAL     XRAN1
      EXTERNAL XRAN1

C     
C     GLOBAL VARIABLES
C     
      DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)
      COMMON/TO_AMPS/  AMP2,       JAMP2

C     CHARACTER*101        HEL_BUFF
C     COMMON/TO_HELICITY/  HEL_BUFF

      REAL*8 POL(2)
      COMMON/TO_POLARIZATION/ POL

      INTEGER          ISUM_HEL
      LOGICAL                    MULTI_CHANNEL
      COMMON/TO_MATRIX/ISUM_HEL, MULTI_CHANNEL
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      COMMON/TO_MCONFIGS/MAPCONFIG, ICONFIG
      DATA IDUM /-1/
      DATA XTRY, XREJ, NGOOD /0,0,0/
      SAVE YFRAC

      DATA (NHEL(I,   1),I=1,5) /-1, 1,-1, 1,-1/
      DATA (NHEL(I,   2),I=1,5) /-1, 1,-1, 1, 1/
      DATA (NHEL(I,   3),I=1,5) /-1, 1,-1,-1,-1/
      DATA (NHEL(I,   4),I=1,5) /-1, 1,-1,-1, 1/
      DATA (NHEL(I,   5),I=1,5) /-1, 1, 1, 1,-1/
      DATA (NHEL(I,   6),I=1,5) /-1, 1, 1, 1, 1/
      DATA (NHEL(I,   7),I=1,5) /-1, 1, 1,-1,-1/
      DATA (NHEL(I,   8),I=1,5) /-1, 1, 1,-1, 1/
      DATA (NHEL(I,   9),I=1,5) /-1,-1,-1, 1,-1/
      DATA (NHEL(I,  10),I=1,5) /-1,-1,-1, 1, 1/
      DATA (NHEL(I,  11),I=1,5) /-1,-1,-1,-1,-1/
      DATA (NHEL(I,  12),I=1,5) /-1,-1,-1,-1, 1/
      DATA (NHEL(I,  13),I=1,5) /-1,-1, 1, 1,-1/
      DATA (NHEL(I,  14),I=1,5) /-1,-1, 1, 1, 1/
      DATA (NHEL(I,  15),I=1,5) /-1,-1, 1,-1,-1/
      DATA (NHEL(I,  16),I=1,5) /-1,-1, 1,-1, 1/
      DATA (NHEL(I,  17),I=1,5) / 0, 1,-1, 1,-1/
      DATA (NHEL(I,  18),I=1,5) / 0, 1,-1, 1, 1/
      DATA (NHEL(I,  19),I=1,5) / 0, 1,-1,-1,-1/
      DATA (NHEL(I,  20),I=1,5) / 0, 1,-1,-1, 1/
      DATA (NHEL(I,  21),I=1,5) / 0, 1, 1, 1,-1/
      DATA (NHEL(I,  22),I=1,5) / 0, 1, 1, 1, 1/
      DATA (NHEL(I,  23),I=1,5) / 0, 1, 1,-1,-1/
      DATA (NHEL(I,  24),I=1,5) / 0, 1, 1,-1, 1/
      DATA (NHEL(I,  25),I=1,5) / 0,-1,-1, 1,-1/
      DATA (NHEL(I,  26),I=1,5) / 0,-1,-1, 1, 1/
      DATA (NHEL(I,  27),I=1,5) / 0,-1,-1,-1,-1/
      DATA (NHEL(I,  28),I=1,5) / 0,-1,-1,-1, 1/
      DATA (NHEL(I,  29),I=1,5) / 0,-1, 1, 1,-1/
      DATA (NHEL(I,  30),I=1,5) / 0,-1, 1, 1, 1/
      DATA (NHEL(I,  31),I=1,5) / 0,-1, 1,-1,-1/
      DATA (NHEL(I,  32),I=1,5) / 0,-1, 1,-1, 1/
      DATA (NHEL(I,  33),I=1,5) / 1, 1,-1, 1,-1/
      DATA (NHEL(I,  34),I=1,5) / 1, 1,-1, 1, 1/
      DATA (NHEL(I,  35),I=1,5) / 1, 1,-1,-1,-1/
      DATA (NHEL(I,  36),I=1,5) / 1, 1,-1,-1, 1/
      DATA (NHEL(I,  37),I=1,5) / 1, 1, 1, 1,-1/
      DATA (NHEL(I,  38),I=1,5) / 1, 1, 1, 1, 1/
      DATA (NHEL(I,  39),I=1,5) / 1, 1, 1,-1,-1/
      DATA (NHEL(I,  40),I=1,5) / 1, 1, 1,-1, 1/
      DATA (NHEL(I,  41),I=1,5) / 1,-1,-1, 1,-1/
      DATA (NHEL(I,  42),I=1,5) / 1,-1,-1, 1, 1/
      DATA (NHEL(I,  43),I=1,5) / 1,-1,-1,-1,-1/
      DATA (NHEL(I,  44),I=1,5) / 1,-1,-1,-1, 1/
      DATA (NHEL(I,  45),I=1,5) / 1,-1, 1, 1,-1/
      DATA (NHEL(I,  46),I=1,5) / 1,-1, 1, 1, 1/
      DATA (NHEL(I,  47),I=1,5) / 1,-1, 1,-1,-1/
      DATA (NHEL(I,  48),I=1,5) / 1,-1, 1,-1, 1/
      DATA IDEN/ 3/
C     ----------
C     BEGIN CODE
C     ----------
      NTRY=NTRY+1
      DO I=1,NEXTERNAL
        JC(I) = +1
      ENDDO

      IF (MULTI_CHANNEL) THEN
        DO I=1,NDIAGS
          AMP2(I)=0D0
        ENDDO
      ENDIF
      JAMP2(0)=1
      DO I=1,INT(JAMP2(0))
        JAMP2(I)=0D0
      ENDDO
      ANS = 0D0
C     WRITE(HEL_BUFF,'(20I5)') (0,I=1,NEXTERNAL)
      DO I=1,NCOMB
        TS(I)=0D0
      ENDDO

C     If the helicity grid status is 0, this means that it is not yet
C      initialized.
      IF (ISUM_HEL.EQ.0.OR.(DS_GET_DIM_STATUS('Helicity').EQ.0)) THEN
        DO I=1,NCOMB
          IF (GOODHEL(I) .OR. NTRY .LE. MAXTRIES.OR.(ISUM_HEL.NE.0))
     $      THEN
            T=MATRIX(P ,NHEL(1,I),JC(1), IVEC)

C           handling only one beam polarization here. Second beam can
C            be handle via the pdf.
            IF(POL(2).NE.1D0.AND.NHEL(2,I).EQ.INT(SIGN(1D0,POL(2))))
     $        THEN
              T=T*ABS(POL(2))
            ELSE IF(POL(2).NE.1D0)THEN
              T=T*(2D0-ABS(POL(2)))
            ENDIF
            IF (ISUM_HEL.NE.0) THEN
              CALL DS_ADD_ENTRY('Helicity',I,T)
            ENDIF
            ANS=ANS+DABS(T)
            TS(I)=T
          ENDIF
        ENDDO
        IF(NTRY.EQ.(MAXTRIES+1)) THEN
          CALL RESET_CUMULATIVE_VARIABLE()  ! avoid biais of the initialization
        ENDIF
        IF (ISUM_HEL.NE.0) THEN
C         We set HEL_PICKED to -HEL_PICKED here so that later on, the
C          call to DS_add_point in dsample.f does not add anything to
C          the grid since it was already done here.
          HEL_PICKED = -IABS(HEL_PICKED)
C         For safety, hardset the helicity sampling jacobian to 0.0d0
C          to make sure it is not .
          HEL_JACOBIAN   = 1.0D0
          IF(DS_GET_DIM_STATUS('Helicity').EQ.1) THEN
C           If we finished the initialization we can update the grid
C            so as to start sampling over it.
C           However the grid will now be filled by dsample with
C            different kind of weights (including pdf, flux, etc...)
C            so by setting the grid_mode of the reference grid to
C            'initialization' we make sure it will be overwritten (as
C            opposed to 'combined') by the running grid at the next
C            update.
            CALL DS_UPDATE_GRID('Helicity')
            CALL DS_SET_GRID_MODE('Helicity','init')
          ENDIF
        ELSE
          IF(NTRY.LE.MAXTRIES)THEN
            DO I=1,NCOMB
              IF (.NOT.GOODHEL(I) .AND. (DABS(TS(I)).GT.ANS*LIMHEL
     $         /NCOMB)) THEN
                GOODHEL(I)=.TRUE.
                NGOOD = NGOOD +1
                PRINT *,'Adding good helicity ',I,TS(I)/ANS
              ENDIF
            ENDDO
          ENDIF
          IF(NTRY.EQ.MAXTRIES)THEN
            ISUM_HEL=MIN(ISUM_HEL,NGOOD)
          ENDIF
        ENDIF
      ELSE  !RANDOM HELICITY

C       The helicity configuration was chosen already by genps and put
C        in a common block defined in genps.inc.
        I = HEL_PICKED

        T=MATRIX(P ,NHEL(1,I),JC(1), IVEC)

C       handling only one beam polarization here. Second beam can be
C        handle via the pdf.
        IF(POL(2).NE.1D0.AND.NHEL(2,I).EQ.INT(SIGN(1D0,POL(2)))) THEN
          T=T*ABS(POL(2))
        ELSE IF(POL(2).NE.1D0)THEN
          T=T*(2D0-ABS(POL(2)))
        ENDIF
C       Always one helicity at a time
        ANS = T
C       Include the Jacobian from helicity sampling
        ANS = ANS * HEL_JACOBIAN
        SELECTED_HEL = I
C       WRITE(HEL_BUFF,'(20i5)')(NHEL(II,I),II=1,NEXTERNAL)  
      ENDIF
      IF (ISUM_HEL .NE. 1.OR.(HEL_PICKED.LE.0)) THEN
        R=XRAN1(IDUM)*ANS
        SUMHEL=0D0
        DO I=1,NCOMB
          SUMHEL=SUMHEL+DABS(TS(I))
          IF(R.LT.SUMHEL)THEN
            SELECTED_HEL = I
C           WRITE(HEL_BUFF,'(20i5)')(NHEL(II,I),II=1,NEXTERNAL)
            ANS=DSIGN(ANS,TS(I))
            GOTO 10
          ENDIF
        ENDDO
 10     CONTINUE
      ENDIF
      IF (MULTI_CHANNEL) THEN
        XTOT=0D0
        DO I=1,NDIAGS
          XTOT=XTOT+AMP2(I)
        ENDDO
        IF (XTOT.NE.0D0) THEN
          ANS=ANS*AMP2(MAPCONFIG(ICONFIG))/XTOT
        ELSE IF(ANS.NE.0D0) THEN
          WRITE(*,*) 'Problem in the multi-channeling. All amp2 are'
     $     //' zero but not the total matrix-element'
          STOP 1
        ENDIF
      ENDIF
      ANS=ANS/DBLE(IDEN)

      CALL SELECT_COLOR(RCOL, JAMP2, ICONFIG, 1,  SELECTED_COL)

      END


      REAL*8 FUNCTION MATRIX(P,NHEL,IC, IVEC)
C     
C     Generated by MadGraph5_aMC@NLO v. 3.6.3, 2025-06-12
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared -- no average over initial
C      state/symmetry factor
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: z > w+ ve~ e- @1
C     *   Decay: w+ > mu+ vm NPcHe=0 NPcHl1=0 NPcHl3=0 NPceB=0 NPceH=0
C      NPceW<=1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=130)
      INCLUDE '../../Source/vector.inc'
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      INTEGER    NWAVEFUNCS,     NCOLOR
      PARAMETER (NWAVEFUNCS=8, NCOLOR=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      LOGICAL CHOSEN_SO_CONFIGS(NSQAMPSO)
      DATA CHOSEN_SO_CONFIGS/.TRUE./
      SAVE CHOSEN_SO_CONFIGS
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
      INTEGER IVEC
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,M,N
      COMPLEX*16 ZTEMP, TMP_JAMP(0)
      INTEGER CF(NCOLOR*(NCOLOR+1))
      INTEGER CF_INDEX,DENOM
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR,NAMPSO)
      COMPLEX*16 W(18,NWAVEFUNCS)
C     Needed for v4 models
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/

      DOUBLE PRECISION FK_MDL_WW
      DOUBLE PRECISION FK_ZERO
      DOUBLE PRECISION FK_MDL_WZ
      SAVE FK_MDL_WW
      SAVE FK_ZERO
      SAVE FK_MDL_WZ

      LOGICAL FIRST
      DATA FIRST /.TRUE./
      SAVE FIRST
C     
C     FUNCTION
C     
      INTEGER SQSOINDEX
C     
C     GLOBAL VARIABLES
C     
      DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)
      COMMON/TO_AMPS/  AMP2,       JAMP2
      INCLUDE 'coupl.inc'

      DOUBLE PRECISION SMALL_WIDTH_TREATMENT
      COMMON/NARROW_WIDTH/SMALL_WIDTH_TREATMENT
C     
C     COLOR DATA
C     
      DATA DENOM/1/
      DATA (CF(I),I=  1,  1) /1/
C     1 ColorOne()
C     ----------
C     BEGIN CODE
C     ----------
      IF (FIRST) THEN
        FIRST=.FALSE.
        FK_ZERO = 0D0
        IF(MDL_WW.NE.0D0) THEN
          FK_MDL_WW = SIGN(MAX(ABS(MDL_WW), ABS(MDL_MW
     $     *SMALL_WIDTH_TREATMENT)), MDL_WW)
        ELSE
          FK_MDL_WW = 0D0
        ENDIF

        IF(MDL_WZ.NE.0D0) THEN
          FK_MDL_WZ = SIGN(MAX(ABS(MDL_WZ), ABS(MDL_MZ
     $     *SMALL_WIDTH_TREATMENT)), MDL_WZ)
        ELSE
          FK_MDL_WZ = 0D0
        ENDIF

      ENDIF

      CALL VXXXXX(P(0,1),MDL_MZ,NHEL(1),-1*IC(1),W(1,1))
      CALL IXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))
      CALL OXXXXX(P(0,3),ZERO,NHEL(3),+1*IC(3),W(1,3))
      CALL FFV3_3(W(1,2),W(1,3),GC_5899,MDL_MW, FK_MDL_WW,W(1,4))
      CALL IXXXXX(P(0,4),ZERO,NHEL(4),-1*IC(4),W(1,5))
      CALL OXXXXX(P(0,5),ZERO,NHEL(5),+1*IC(5),W(1,6))
      CALL FFV3_2(W(1,5),W(1,4),GC_5899,ZERO, FK_ZERO,W(1,7))
C     Amplitude(s) for diagram number 1
      CALL FFV1_3_0(W(1,7),W(1,6),W(1,1),GC_6187,-GC_5909,AMP(1))
      CALL FFV11_3(W(1,2),W(1,3),GC_6468,MDL_MW, FK_MDL_WW,W(1,8))
      CALL FFV3_2(W(1,5),W(1,8),GC_5899,ZERO, FK_ZERO,W(1,3))
C     Amplitude(s) for diagram number 2
      CALL FFV1_3_0(W(1,3),W(1,6),W(1,1),GC_6187,-GC_5909,AMP(2))
C     Amplitude(s) for diagram number 3
      CALL FFV6_0(W(1,7),W(1,6),W(1,1),GC_7256,AMP(3))
C     Amplitude(s) for diagram number 4
      CALL FFV6_0(W(1,3),W(1,6),W(1,1),GC_7256,AMP(4))
C     Amplitude(s) for diagram number 5
      CALL FFV10_0(W(1,7),W(1,6),W(1,1),GC_6527,AMP(5))
C     Amplitude(s) for diagram number 6
      CALL FFV10_0(W(1,3),W(1,6),W(1,1),GC_6527,AMP(6))
C     Amplitude(s) for diagram number 7
      CALL FFV3_0(W(1,7),W(1,6),W(1,1),GC_7268,AMP(7))
C     Amplitude(s) for diagram number 8
      CALL FFV3_0(W(1,3),W(1,6),W(1,1),GC_7268,AMP(8))
C     Amplitude(s) for diagram number 9
      CALL FFV10_0(W(1,7),W(1,6),W(1,1),GC_7004,AMP(9))
C     Amplitude(s) for diagram number 10
      CALL FFV10_0(W(1,3),W(1,6),W(1,1),GC_7004,AMP(10))
C     Amplitude(s) for diagram number 11
      CALL FFV3_0(W(1,7),W(1,6),W(1,1),GC_7675,AMP(11))
C     Amplitude(s) for diagram number 12
      CALL FFV3_0(W(1,3),W(1,6),W(1,1),GC_7675,AMP(12))
C     Amplitude(s) for diagram number 13
      CALL FFV1_0(W(1,7),W(1,6),W(1,1),GC_7695,AMP(13))
C     Amplitude(s) for diagram number 14
      CALL FFV1_0(W(1,3),W(1,6),W(1,1),GC_7695,AMP(14))
      CALL FFV4_2(W(1,5),W(1,4),GC_6464,ZERO, FK_ZERO,W(1,3))
C     Amplitude(s) for diagram number 15
      CALL FFV1_3_0(W(1,3),W(1,6),W(1,1),GC_6187,-GC_5909,AMP(15))
      CALL FFV4_2(W(1,5),W(1,8),GC_6464,ZERO, FK_ZERO,W(1,7))
C     Amplitude(s) for diagram number 16
      CALL FFV1_3_0(W(1,7),W(1,6),W(1,1),GC_6187,-GC_5909,AMP(16))
C     Amplitude(s) for diagram number 17
      CALL FFV6_0(W(1,3),W(1,6),W(1,1),GC_7256,AMP(17))
C     Amplitude(s) for diagram number 18
      CALL FFV6_0(W(1,7),W(1,6),W(1,1),GC_7256,AMP(18))
C     Amplitude(s) for diagram number 19
      CALL FFV10_0(W(1,3),W(1,6),W(1,1),GC_6527,AMP(19))
C     Amplitude(s) for diagram number 20
      CALL FFV10_0(W(1,7),W(1,6),W(1,1),GC_6527,AMP(20))
C     Amplitude(s) for diagram number 21
      CALL FFV3_0(W(1,3),W(1,6),W(1,1),GC_7268,AMP(21))
C     Amplitude(s) for diagram number 22
      CALL FFV3_0(W(1,7),W(1,6),W(1,1),GC_7268,AMP(22))
C     Amplitude(s) for diagram number 23
      CALL FFV10_0(W(1,3),W(1,6),W(1,1),GC_7004,AMP(23))
C     Amplitude(s) for diagram number 24
      CALL FFV10_0(W(1,7),W(1,6),W(1,1),GC_7004,AMP(24))
C     Amplitude(s) for diagram number 25
      CALL FFV3_0(W(1,3),W(1,6),W(1,1),GC_7675,AMP(25))
C     Amplitude(s) for diagram number 26
      CALL FFV3_0(W(1,7),W(1,6),W(1,1),GC_7675,AMP(26))
C     Amplitude(s) for diagram number 27
      CALL FFV1_0(W(1,3),W(1,6),W(1,1),GC_7695,AMP(27))
C     Amplitude(s) for diagram number 28
      CALL FFV1_0(W(1,7),W(1,6),W(1,1),GC_7695,AMP(28))
      CALL FFV3_2(W(1,5),W(1,4),-GC_7639,ZERO, FK_ZERO,W(1,7))
C     Amplitude(s) for diagram number 29
      CALL FFV1_3_0(W(1,7),W(1,6),W(1,1),GC_6187,-GC_5909,AMP(29))
      CALL FFV3_2(W(1,5),W(1,8),-GC_7639,ZERO, FK_ZERO,W(1,3))
C     Amplitude(s) for diagram number 30
      CALL FFV1_3_0(W(1,3),W(1,6),W(1,1),GC_6187,-GC_5909,AMP(30))
C     Amplitude(s) for diagram number 31
      CALL FFV6_0(W(1,7),W(1,6),W(1,1),GC_7256,AMP(31))
C     Amplitude(s) for diagram number 32
      CALL FFV6_0(W(1,3),W(1,6),W(1,1),GC_7256,AMP(32))
C     Amplitude(s) for diagram number 33
      CALL FFV10_0(W(1,7),W(1,6),W(1,1),GC_6527,AMP(33))
C     Amplitude(s) for diagram number 34
      CALL FFV10_0(W(1,3),W(1,6),W(1,1),GC_6527,AMP(34))
C     Amplitude(s) for diagram number 35
      CALL FFV3_0(W(1,7),W(1,6),W(1,1),GC_7268,AMP(35))
C     Amplitude(s) for diagram number 36
      CALL FFV3_0(W(1,3),W(1,6),W(1,1),GC_7268,AMP(36))
C     Amplitude(s) for diagram number 37
      CALL FFV10_0(W(1,7),W(1,6),W(1,1),GC_7004,AMP(37))
C     Amplitude(s) for diagram number 38
      CALL FFV10_0(W(1,3),W(1,6),W(1,1),GC_7004,AMP(38))
C     Amplitude(s) for diagram number 39
      CALL FFV3_0(W(1,7),W(1,6),W(1,1),GC_7675,AMP(39))
C     Amplitude(s) for diagram number 40
      CALL FFV3_0(W(1,3),W(1,6),W(1,1),GC_7675,AMP(40))
C     Amplitude(s) for diagram number 41
      CALL FFV1_0(W(1,7),W(1,6),W(1,1),GC_7695,AMP(41))
C     Amplitude(s) for diagram number 42
      CALL FFV1_0(W(1,3),W(1,6),W(1,1),GC_7695,AMP(42))
      CALL FFV4_2(W(1,5),W(1,4),GC_6465,ZERO, FK_ZERO,W(1,3))
C     Amplitude(s) for diagram number 43
      CALL FFV3_0(W(1,3),W(1,6),W(1,1),GC_7269,AMP(43))
      CALL FFV4_2(W(1,5),W(1,8),GC_6465,ZERO, FK_ZERO,W(1,7))
C     Amplitude(s) for diagram number 44
      CALL FFV3_0(W(1,7),W(1,6),W(1,1),GC_7269,AMP(44))
C     Amplitude(s) for diagram number 45
      CALL FFV6_0(W(1,3),W(1,6),W(1,1),GC_7257,AMP(45))
C     Amplitude(s) for diagram number 46
      CALL FFV6_0(W(1,7),W(1,6),W(1,1),GC_7257,AMP(46))
C     Amplitude(s) for diagram number 47
      CALL FFV11_4_0(W(1,3),W(1,6),W(1,1),GC_6528,GC_6530,AMP(47))
C     Amplitude(s) for diagram number 48
      CALL FFV11_4_0(W(1,7),W(1,6),W(1,1),GC_6528,GC_6530,AMP(48))
C     Amplitude(s) for diagram number 49
      CALL FFV3_0(W(1,3),W(1,6),W(1,1),-GC_7280,AMP(49))
C     Amplitude(s) for diagram number 50
      CALL FFV3_0(W(1,7),W(1,6),W(1,1),-GC_7280,AMP(50))
C     Amplitude(s) for diagram number 51
      CALL FFV11_4_0(W(1,3),W(1,6),W(1,1),GC_7005,GC_7007,AMP(51))
C     Amplitude(s) for diagram number 52
      CALL FFV11_4_0(W(1,7),W(1,6),W(1,1),GC_7005,GC_7007,AMP(52))
      CALL FFV3_2(W(1,5),W(1,4),GC_7194,ZERO, FK_ZERO,W(1,7))
C     Amplitude(s) for diagram number 53
      CALL FFV3_0(W(1,7),W(1,6),W(1,1),GC_7269,AMP(53))
      CALL FFV3_2(W(1,5),W(1,8),GC_7194,ZERO, FK_ZERO,W(1,3))
C     Amplitude(s) for diagram number 54
      CALL FFV3_0(W(1,3),W(1,6),W(1,1),GC_7269,AMP(54))
C     Amplitude(s) for diagram number 55
      CALL FFV6_0(W(1,7),W(1,6),W(1,1),GC_7257,AMP(55))
C     Amplitude(s) for diagram number 56
      CALL FFV6_0(W(1,3),W(1,6),W(1,1),GC_7257,AMP(56))
C     Amplitude(s) for diagram number 57
      CALL FFV11_4_0(W(1,7),W(1,6),W(1,1),GC_6528,GC_6530,AMP(57))
C     Amplitude(s) for diagram number 58
      CALL FFV11_4_0(W(1,3),W(1,6),W(1,1),GC_6528,GC_6530,AMP(58))
C     Amplitude(s) for diagram number 59
      CALL FFV3_0(W(1,7),W(1,6),W(1,1),-GC_7280,AMP(59))
C     Amplitude(s) for diagram number 60
      CALL FFV3_0(W(1,3),W(1,6),W(1,1),-GC_7280,AMP(60))
C     Amplitude(s) for diagram number 61
      CALL FFV11_4_0(W(1,7),W(1,6),W(1,1),GC_7005,GC_7007,AMP(61))
C     Amplitude(s) for diagram number 62
      CALL FFV11_4_0(W(1,3),W(1,6),W(1,1),GC_7005,GC_7007,AMP(62))
      CALL FFV4_2(W(1,5),W(1,4),GC_6466,MDL_MTA, FK_ZERO,W(1,3))
C     Amplitude(s) for diagram number 63
      CALL FFV3_0(W(1,3),W(1,6),W(1,1),GC_7270,AMP(63))
      CALL FFV4_2(W(1,5),W(1,8),GC_6466,MDL_MTA, FK_ZERO,W(1,7))
C     Amplitude(s) for diagram number 64
      CALL FFV3_0(W(1,7),W(1,6),W(1,1),GC_7270,AMP(64))
C     Amplitude(s) for diagram number 65
      CALL FFV6_0(W(1,3),W(1,6),W(1,1),GC_7258,AMP(65))
C     Amplitude(s) for diagram number 66
      CALL FFV6_0(W(1,7),W(1,6),W(1,1),GC_7258,AMP(66))
C     Amplitude(s) for diagram number 67
      CALL FFV11_4_0(W(1,3),W(1,6),W(1,1),GC_6529,GC_6533,AMP(67))
C     Amplitude(s) for diagram number 68
      CALL FFV11_4_0(W(1,7),W(1,6),W(1,1),GC_6529,GC_6533,AMP(68))
C     Amplitude(s) for diagram number 69
      CALL FFV3_0(W(1,3),W(1,6),W(1,1),-GC_7282,AMP(69))
C     Amplitude(s) for diagram number 70
      CALL FFV3_0(W(1,7),W(1,6),W(1,1),-GC_7282,AMP(70))
C     Amplitude(s) for diagram number 71
      CALL FFV11_4_0(W(1,3),W(1,6),W(1,1),GC_7006,GC_7010,AMP(71))
C     Amplitude(s) for diagram number 72
      CALL FFV11_4_0(W(1,7),W(1,6),W(1,1),GC_7006,GC_7010,AMP(72))
      CALL FFV3_2(W(1,5),W(1,4),GC_7195,MDL_MTA, FK_ZERO,W(1,7))
C     Amplitude(s) for diagram number 73
      CALL FFV3_0(W(1,7),W(1,6),W(1,1),GC_7270,AMP(73))
      CALL FFV3_2(W(1,5),W(1,8),GC_7195,MDL_MTA, FK_ZERO,W(1,3))
C     Amplitude(s) for diagram number 74
      CALL FFV3_0(W(1,3),W(1,6),W(1,1),GC_7270,AMP(74))
C     Amplitude(s) for diagram number 75
      CALL FFV6_0(W(1,7),W(1,6),W(1,1),GC_7258,AMP(75))
C     Amplitude(s) for diagram number 76
      CALL FFV6_0(W(1,3),W(1,6),W(1,1),GC_7258,AMP(76))
C     Amplitude(s) for diagram number 77
      CALL FFV11_4_0(W(1,7),W(1,6),W(1,1),GC_6529,GC_6533,AMP(77))
C     Amplitude(s) for diagram number 78
      CALL FFV11_4_0(W(1,3),W(1,6),W(1,1),GC_6529,GC_6533,AMP(78))
C     Amplitude(s) for diagram number 79
      CALL FFV3_0(W(1,7),W(1,6),W(1,1),-GC_7282,AMP(79))
C     Amplitude(s) for diagram number 80
      CALL FFV3_0(W(1,3),W(1,6),W(1,1),-GC_7282,AMP(80))
C     Amplitude(s) for diagram number 81
      CALL FFV11_4_0(W(1,7),W(1,6),W(1,1),GC_7006,GC_7010,AMP(81))
C     Amplitude(s) for diagram number 82
      CALL FFV11_4_0(W(1,3),W(1,6),W(1,1),GC_7006,GC_7010,AMP(82))
      CALL FFV3_1(W(1,6),W(1,4),GC_5899,ZERO, FK_ZERO,W(1,3))
C     Amplitude(s) for diagram number 83
      CALL FFV3_0(W(1,5),W(1,3),W(1,1),GC_5909,AMP(83))
      CALL FFV3_1(W(1,6),W(1,8),GC_5899,ZERO, FK_ZERO,W(1,7))
C     Amplitude(s) for diagram number 84
      CALL FFV3_0(W(1,5),W(1,7),W(1,1),GC_5909,AMP(84))
C     Amplitude(s) for diagram number 85
      CALL FFV3_0(W(1,5),W(1,3),W(1,1),GC_7268,AMP(85))
C     Amplitude(s) for diagram number 86
      CALL FFV3_0(W(1,5),W(1,7),W(1,1),GC_7268,AMP(86))
C     Amplitude(s) for diagram number 87
      CALL FFV3_0(W(1,5),W(1,3),W(1,1),-GC_7675,AMP(87))
C     Amplitude(s) for diagram number 88
      CALL FFV3_0(W(1,5),W(1,7),W(1,1),-GC_7675,AMP(88))
      CALL FFV4_1(W(1,6),W(1,4),GC_6464,ZERO, FK_ZERO,W(1,7))
C     Amplitude(s) for diagram number 89
      CALL FFV3_0(W(1,5),W(1,7),W(1,1),GC_5909,AMP(89))
      CALL FFV4_1(W(1,6),W(1,8),GC_6464,ZERO, FK_ZERO,W(1,3))
C     Amplitude(s) for diagram number 90
      CALL FFV3_0(W(1,5),W(1,3),W(1,1),GC_5909,AMP(90))
C     Amplitude(s) for diagram number 91
      CALL FFV3_0(W(1,5),W(1,7),W(1,1),GC_7268,AMP(91))
C     Amplitude(s) for diagram number 92
      CALL FFV3_0(W(1,5),W(1,3),W(1,1),GC_7268,AMP(92))
C     Amplitude(s) for diagram number 93
      CALL FFV3_0(W(1,5),W(1,7),W(1,1),-GC_7675,AMP(93))
C     Amplitude(s) for diagram number 94
      CALL FFV3_0(W(1,5),W(1,3),W(1,1),-GC_7675,AMP(94))
      CALL FFV3_1(W(1,6),W(1,4),-GC_7639,ZERO, FK_ZERO,W(1,3))
C     Amplitude(s) for diagram number 95
      CALL FFV3_0(W(1,5),W(1,3),W(1,1),GC_5909,AMP(95))
      CALL FFV3_1(W(1,6),W(1,8),-GC_7639,ZERO, FK_ZERO,W(1,7))
C     Amplitude(s) for diagram number 96
      CALL FFV3_0(W(1,5),W(1,7),W(1,1),GC_5909,AMP(96))
C     Amplitude(s) for diagram number 97
      CALL FFV3_0(W(1,5),W(1,3),W(1,1),GC_7268,AMP(97))
C     Amplitude(s) for diagram number 98
      CALL FFV3_0(W(1,5),W(1,7),W(1,1),GC_7268,AMP(98))
C     Amplitude(s) for diagram number 99
      CALL FFV3_0(W(1,5),W(1,3),W(1,1),-GC_7675,AMP(99))
C     Amplitude(s) for diagram number 100
      CALL FFV3_0(W(1,5),W(1,7),W(1,1),-GC_7675,AMP(100))
      CALL FFV4_1(W(1,6),W(1,4),GC_6467,ZERO, FK_ZERO,W(1,7))
C     Amplitude(s) for diagram number 101
      CALL FFV3_0(W(1,5),W(1,7),W(1,1),GC_7269,AMP(101))
      CALL FFV4_1(W(1,6),W(1,8),GC_6467,ZERO, FK_ZERO,W(1,3))
C     Amplitude(s) for diagram number 102
      CALL FFV3_0(W(1,5),W(1,3),W(1,1),GC_7269,AMP(102))
C     Amplitude(s) for diagram number 103
      CALL FFV3_0(W(1,5),W(1,7),W(1,1),GC_7280,AMP(103))
C     Amplitude(s) for diagram number 104
      CALL FFV3_0(W(1,5),W(1,3),W(1,1),GC_7280,AMP(104))
      CALL FFV3_1(W(1,6),W(1,4),GC_7194,ZERO, FK_ZERO,W(1,3))
C     Amplitude(s) for diagram number 105
      CALL FFV3_0(W(1,5),W(1,3),W(1,1),GC_7269,AMP(105))
      CALL FFV3_1(W(1,6),W(1,8),GC_7194,ZERO, FK_ZERO,W(1,7))
C     Amplitude(s) for diagram number 106
      CALL FFV3_0(W(1,5),W(1,7),W(1,1),GC_7269,AMP(106))
C     Amplitude(s) for diagram number 107
      CALL FFV3_0(W(1,5),W(1,3),W(1,1),GC_7280,AMP(107))
C     Amplitude(s) for diagram number 108
      CALL FFV3_0(W(1,5),W(1,7),W(1,1),GC_7280,AMP(108))
      CALL FFV4_1(W(1,6),W(1,4),GC_6470,ZERO, FK_ZERO,W(1,7))
C     Amplitude(s) for diagram number 109
      CALL FFV3_0(W(1,5),W(1,7),W(1,1),GC_7270,AMP(109))
      CALL FFV4_1(W(1,6),W(1,8),GC_6470,ZERO, FK_ZERO,W(1,3))
C     Amplitude(s) for diagram number 110
      CALL FFV3_0(W(1,5),W(1,3),W(1,1),GC_7270,AMP(110))
C     Amplitude(s) for diagram number 111
      CALL FFV3_0(W(1,5),W(1,7),W(1,1),GC_7282,AMP(111))
C     Amplitude(s) for diagram number 112
      CALL FFV3_0(W(1,5),W(1,3),W(1,1),GC_7282,AMP(112))
      CALL FFV3_1(W(1,6),W(1,4),GC_7195,ZERO, FK_ZERO,W(1,3))
C     Amplitude(s) for diagram number 113
      CALL FFV3_0(W(1,5),W(1,3),W(1,1),GC_7270,AMP(113))
      CALL FFV3_1(W(1,6),W(1,8),GC_7195,ZERO, FK_ZERO,W(1,7))
C     Amplitude(s) for diagram number 114
      CALL FFV3_0(W(1,5),W(1,7),W(1,1),GC_7270,AMP(114))
C     Amplitude(s) for diagram number 115
      CALL FFV3_0(W(1,5),W(1,3),W(1,1),GC_7282,AMP(115))
C     Amplitude(s) for diagram number 116
      CALL FFV3_0(W(1,5),W(1,7),W(1,1),GC_7282,AMP(116))
      CALL FFV3_3(W(1,5),W(1,6),GC_5899,MDL_MW, FK_MDL_WW,W(1,7))
C     Amplitude(s) for diagram number 117
      CALL VVV5_0(W(1,7),W(1,4),W(1,1),GC_5911,AMP(117))
C     Amplitude(s) for diagram number 118
      CALL VVV5_0(W(1,7),W(1,8),W(1,1),GC_5911,AMP(118))
C     Amplitude(s) for diagram number 119
      CALL VVV5_0(W(1,7),W(1,4),W(1,1),GC_7690,AMP(119))
C     Amplitude(s) for diagram number 120
      CALL VVV5_0(W(1,7),W(1,8),W(1,1),GC_7690,AMP(120))
      CALL FFV4_3(W(1,5),W(1,6),GC_6464,MDL_MW, FK_MDL_WW,W(1,7))
C     Amplitude(s) for diagram number 121
      CALL VVV5_0(W(1,7),W(1,4),W(1,1),GC_5911,AMP(121))
C     Amplitude(s) for diagram number 122
      CALL VVV5_0(W(1,7),W(1,8),W(1,1),GC_5911,AMP(122))
C     Amplitude(s) for diagram number 123
      CALL VVV5_0(W(1,7),W(1,4),W(1,1),GC_7690,AMP(123))
C     Amplitude(s) for diagram number 124
      CALL VVV5_0(W(1,7),W(1,8),W(1,1),GC_7690,AMP(124))
      CALL FFV3_3(W(1,5),W(1,6),-GC_7639,MDL_MW, FK_MDL_WW,W(1,7))
C     Amplitude(s) for diagram number 125
      CALL VVV5_0(W(1,7),W(1,4),W(1,1),GC_5911,AMP(125))
C     Amplitude(s) for diagram number 126
      CALL VVV5_0(W(1,7),W(1,8),W(1,1),GC_5911,AMP(126))
C     Amplitude(s) for diagram number 127
      CALL VVV5_0(W(1,7),W(1,4),W(1,1),GC_7690,AMP(127))
C     Amplitude(s) for diagram number 128
      CALL VVV5_0(W(1,7),W(1,8),W(1,1),GC_7690,AMP(128))
C     Amplitude(s) for diagram number 129
      CALL FFVV2_0(W(1,5),W(1,6),W(1,4),W(1,1),GC_6942,AMP(129))
C     Amplitude(s) for diagram number 130
      CALL FFVV2_0(W(1,5),W(1,6),W(1,8),W(1,1),GC_6942,AMP(130))
C     JAMPs contributing to orders ALL_ORDERS=1
      JAMP(1,1) = AMP(1)+AMP(2)+AMP(3)+AMP(4)+AMP(5)+AMP(6)+AMP(7)
     $ +AMP(8)+AMP(9)+AMP(10)+AMP(11)+AMP(12)+AMP(13)+AMP(14)+AMP(15)
     $ +AMP(16)+AMP(17)+AMP(18)+AMP(19)+AMP(20)+AMP(21)+AMP(22)+AMP(23)
     $ +AMP(24)+AMP(25)+AMP(26)+AMP(27)+AMP(28)+AMP(29)+AMP(30)+AMP(31)
     $ +AMP(32)+AMP(33)+AMP(34)+AMP(35)+AMP(36)+AMP(37)+AMP(38)+AMP(39)
     $ +AMP(40)+AMP(41)+AMP(42)+AMP(43)+AMP(44)+AMP(45)+AMP(46)+AMP(47)
     $ +AMP(48)+AMP(49)+AMP(50)+AMP(51)+AMP(52)+AMP(53)+AMP(54)+AMP(55)
     $ +AMP(56)+AMP(57)+AMP(58)+AMP(59)+AMP(60)+AMP(61)+AMP(62)+AMP(63)
     $ +AMP(64)+AMP(65)+AMP(66)+AMP(67)+AMP(68)+AMP(69)+AMP(70)+AMP(71)
     $ +AMP(72)+AMP(73)+AMP(74)+AMP(75)+AMP(76)+AMP(77)+AMP(78)+AMP(79)
     $ +AMP(80)+AMP(81)+AMP(82)+AMP(83)+AMP(84)+AMP(85)+AMP(86)+AMP(87)
     $ +AMP(88)+AMP(89)+AMP(90)+AMP(91)+AMP(92)+AMP(93)+AMP(94)+AMP(95)
     $ +AMP(96)+AMP(97)+AMP(98)+AMP(99)+AMP(100)+AMP(101)+AMP(102)
     $ +AMP(103)+AMP(104)+AMP(105)+AMP(106)+AMP(107)+AMP(108)+AMP(109)
     $ +AMP(110)+AMP(111)+AMP(112)+AMP(113)+AMP(114)+AMP(115)+AMP(116)
     $ +AMP(117)+AMP(118)+AMP(119)+AMP(120)+AMP(121)+AMP(122)+AMP(123)
     $ +AMP(124)+AMP(125)+AMP(126)+AMP(127)+AMP(128)+AMP(129)+AMP(130)

      MATRIX = 0.D0
      DO M = 1, NAMPSO
        CF_INDEX = 0
        DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = I, NCOLOR
            CF_INDEX = CF_INDEX +1
            ZTEMP = ZTEMP + CF(CF_INDEX)*JAMP(J,M)
          ENDDO
          DO N = 1, NAMPSO
            IF (CHOSEN_SO_CONFIGS(SQSOINDEX(M,N))) THEN
              MATRIX = MATRIX + ZTEMP*DCONJG(JAMP(I,N))
            ENDIF
          ENDDO
        ENDDO
      ENDDO
      MATRIX = MATRIX / DENOM

      AMP2(1)=AMP2(1)+AMP(1)*DCONJG(AMP(1))
      AMP2(2)=AMP2(2)+AMP(2)*DCONJG(AMP(2))
      AMP2(3)=AMP2(3)+AMP(3)*DCONJG(AMP(3))
      AMP2(4)=AMP2(4)+AMP(4)*DCONJG(AMP(4))
      AMP2(5)=AMP2(5)+AMP(5)*DCONJG(AMP(5))
      AMP2(6)=AMP2(6)+AMP(6)*DCONJG(AMP(6))
      AMP2(7)=AMP2(7)+AMP(7)*DCONJG(AMP(7))
      AMP2(8)=AMP2(8)+AMP(8)*DCONJG(AMP(8))
      AMP2(9)=AMP2(9)+AMP(9)*DCONJG(AMP(9))
      AMP2(10)=AMP2(10)+AMP(10)*DCONJG(AMP(10))
      AMP2(11)=AMP2(11)+AMP(11)*DCONJG(AMP(11))
      AMP2(12)=AMP2(12)+AMP(12)*DCONJG(AMP(12))
      AMP2(13)=AMP2(13)+AMP(13)*DCONJG(AMP(13))
      AMP2(14)=AMP2(14)+AMP(14)*DCONJG(AMP(14))
      AMP2(15)=AMP2(15)+AMP(15)*DCONJG(AMP(15))
      AMP2(16)=AMP2(16)+AMP(16)*DCONJG(AMP(16))
      AMP2(17)=AMP2(17)+AMP(17)*DCONJG(AMP(17))
      AMP2(18)=AMP2(18)+AMP(18)*DCONJG(AMP(18))
      AMP2(19)=AMP2(19)+AMP(19)*DCONJG(AMP(19))
      AMP2(20)=AMP2(20)+AMP(20)*DCONJG(AMP(20))
      AMP2(21)=AMP2(21)+AMP(21)*DCONJG(AMP(21))
      AMP2(22)=AMP2(22)+AMP(22)*DCONJG(AMP(22))
      AMP2(23)=AMP2(23)+AMP(23)*DCONJG(AMP(23))
      AMP2(24)=AMP2(24)+AMP(24)*DCONJG(AMP(24))
      AMP2(25)=AMP2(25)+AMP(25)*DCONJG(AMP(25))
      AMP2(26)=AMP2(26)+AMP(26)*DCONJG(AMP(26))
      AMP2(27)=AMP2(27)+AMP(27)*DCONJG(AMP(27))
      AMP2(28)=AMP2(28)+AMP(28)*DCONJG(AMP(28))
      AMP2(29)=AMP2(29)+AMP(29)*DCONJG(AMP(29))
      AMP2(30)=AMP2(30)+AMP(30)*DCONJG(AMP(30))
      AMP2(31)=AMP2(31)+AMP(31)*DCONJG(AMP(31))
      AMP2(32)=AMP2(32)+AMP(32)*DCONJG(AMP(32))
      AMP2(33)=AMP2(33)+AMP(33)*DCONJG(AMP(33))
      AMP2(34)=AMP2(34)+AMP(34)*DCONJG(AMP(34))
      AMP2(35)=AMP2(35)+AMP(35)*DCONJG(AMP(35))
      AMP2(36)=AMP2(36)+AMP(36)*DCONJG(AMP(36))
      AMP2(37)=AMP2(37)+AMP(37)*DCONJG(AMP(37))
      AMP2(38)=AMP2(38)+AMP(38)*DCONJG(AMP(38))
      AMP2(39)=AMP2(39)+AMP(39)*DCONJG(AMP(39))
      AMP2(40)=AMP2(40)+AMP(40)*DCONJG(AMP(40))
      AMP2(41)=AMP2(41)+AMP(41)*DCONJG(AMP(41))
      AMP2(42)=AMP2(42)+AMP(42)*DCONJG(AMP(42))
      AMP2(43)=AMP2(43)+AMP(43)*DCONJG(AMP(43))
      AMP2(44)=AMP2(44)+AMP(44)*DCONJG(AMP(44))
      AMP2(45)=AMP2(45)+AMP(45)*DCONJG(AMP(45))
      AMP2(46)=AMP2(46)+AMP(46)*DCONJG(AMP(46))
      AMP2(47)=AMP2(47)+AMP(47)*DCONJG(AMP(47))
      AMP2(48)=AMP2(48)+AMP(48)*DCONJG(AMP(48))
      AMP2(49)=AMP2(49)+AMP(49)*DCONJG(AMP(49))
      AMP2(50)=AMP2(50)+AMP(50)*DCONJG(AMP(50))
      AMP2(51)=AMP2(51)+AMP(51)*DCONJG(AMP(51))
      AMP2(52)=AMP2(52)+AMP(52)*DCONJG(AMP(52))
      AMP2(53)=AMP2(53)+AMP(53)*DCONJG(AMP(53))
      AMP2(54)=AMP2(54)+AMP(54)*DCONJG(AMP(54))
      AMP2(55)=AMP2(55)+AMP(55)*DCONJG(AMP(55))
      AMP2(56)=AMP2(56)+AMP(56)*DCONJG(AMP(56))
      AMP2(57)=AMP2(57)+AMP(57)*DCONJG(AMP(57))
      AMP2(58)=AMP2(58)+AMP(58)*DCONJG(AMP(58))
      AMP2(59)=AMP2(59)+AMP(59)*DCONJG(AMP(59))
      AMP2(60)=AMP2(60)+AMP(60)*DCONJG(AMP(60))
      AMP2(61)=AMP2(61)+AMP(61)*DCONJG(AMP(61))
      AMP2(62)=AMP2(62)+AMP(62)*DCONJG(AMP(62))
      AMP2(63)=AMP2(63)+AMP(63)*DCONJG(AMP(63))
      AMP2(64)=AMP2(64)+AMP(64)*DCONJG(AMP(64))
      AMP2(65)=AMP2(65)+AMP(65)*DCONJG(AMP(65))
      AMP2(66)=AMP2(66)+AMP(66)*DCONJG(AMP(66))
      AMP2(67)=AMP2(67)+AMP(67)*DCONJG(AMP(67))
      AMP2(68)=AMP2(68)+AMP(68)*DCONJG(AMP(68))
      AMP2(69)=AMP2(69)+AMP(69)*DCONJG(AMP(69))
      AMP2(70)=AMP2(70)+AMP(70)*DCONJG(AMP(70))
      AMP2(71)=AMP2(71)+AMP(71)*DCONJG(AMP(71))
      AMP2(72)=AMP2(72)+AMP(72)*DCONJG(AMP(72))
      AMP2(73)=AMP2(73)+AMP(73)*DCONJG(AMP(73))
      AMP2(74)=AMP2(74)+AMP(74)*DCONJG(AMP(74))
      AMP2(75)=AMP2(75)+AMP(75)*DCONJG(AMP(75))
      AMP2(76)=AMP2(76)+AMP(76)*DCONJG(AMP(76))
      AMP2(77)=AMP2(77)+AMP(77)*DCONJG(AMP(77))
      AMP2(78)=AMP2(78)+AMP(78)*DCONJG(AMP(78))
      AMP2(79)=AMP2(79)+AMP(79)*DCONJG(AMP(79))
      AMP2(80)=AMP2(80)+AMP(80)*DCONJG(AMP(80))
      AMP2(81)=AMP2(81)+AMP(81)*DCONJG(AMP(81))
      AMP2(82)=AMP2(82)+AMP(82)*DCONJG(AMP(82))
      AMP2(83)=AMP2(83)+AMP(83)*DCONJG(AMP(83))
      AMP2(84)=AMP2(84)+AMP(84)*DCONJG(AMP(84))
      AMP2(85)=AMP2(85)+AMP(85)*DCONJG(AMP(85))
      AMP2(86)=AMP2(86)+AMP(86)*DCONJG(AMP(86))
      AMP2(87)=AMP2(87)+AMP(87)*DCONJG(AMP(87))
      AMP2(88)=AMP2(88)+AMP(88)*DCONJG(AMP(88))
      AMP2(89)=AMP2(89)+AMP(89)*DCONJG(AMP(89))
      AMP2(90)=AMP2(90)+AMP(90)*DCONJG(AMP(90))
      AMP2(91)=AMP2(91)+AMP(91)*DCONJG(AMP(91))
      AMP2(92)=AMP2(92)+AMP(92)*DCONJG(AMP(92))
      AMP2(93)=AMP2(93)+AMP(93)*DCONJG(AMP(93))
      AMP2(94)=AMP2(94)+AMP(94)*DCONJG(AMP(94))
      AMP2(95)=AMP2(95)+AMP(95)*DCONJG(AMP(95))
      AMP2(96)=AMP2(96)+AMP(96)*DCONJG(AMP(96))
      AMP2(97)=AMP2(97)+AMP(97)*DCONJG(AMP(97))
      AMP2(98)=AMP2(98)+AMP(98)*DCONJG(AMP(98))
      AMP2(99)=AMP2(99)+AMP(99)*DCONJG(AMP(99))
      AMP2(100)=AMP2(100)+AMP(100)*DCONJG(AMP(100))
      AMP2(101)=AMP2(101)+AMP(101)*DCONJG(AMP(101))
      AMP2(102)=AMP2(102)+AMP(102)*DCONJG(AMP(102))
      AMP2(103)=AMP2(103)+AMP(103)*DCONJG(AMP(103))
      AMP2(104)=AMP2(104)+AMP(104)*DCONJG(AMP(104))
      AMP2(105)=AMP2(105)+AMP(105)*DCONJG(AMP(105))
      AMP2(106)=AMP2(106)+AMP(106)*DCONJG(AMP(106))
      AMP2(107)=AMP2(107)+AMP(107)*DCONJG(AMP(107))
      AMP2(108)=AMP2(108)+AMP(108)*DCONJG(AMP(108))
      AMP2(109)=AMP2(109)+AMP(109)*DCONJG(AMP(109))
      AMP2(110)=AMP2(110)+AMP(110)*DCONJG(AMP(110))
      AMP2(111)=AMP2(111)+AMP(111)*DCONJG(AMP(111))
      AMP2(112)=AMP2(112)+AMP(112)*DCONJG(AMP(112))
      AMP2(113)=AMP2(113)+AMP(113)*DCONJG(AMP(113))
      AMP2(114)=AMP2(114)+AMP(114)*DCONJG(AMP(114))
      AMP2(115)=AMP2(115)+AMP(115)*DCONJG(AMP(115))
      AMP2(116)=AMP2(116)+AMP(116)*DCONJG(AMP(116))
      AMP2(117)=AMP2(117)+AMP(117)*DCONJG(AMP(117))
      AMP2(118)=AMP2(118)+AMP(118)*DCONJG(AMP(118))
      AMP2(119)=AMP2(119)+AMP(119)*DCONJG(AMP(119))
      AMP2(120)=AMP2(120)+AMP(120)*DCONJG(AMP(120))
      AMP2(121)=AMP2(121)+AMP(121)*DCONJG(AMP(121))
      AMP2(122)=AMP2(122)+AMP(122)*DCONJG(AMP(122))
      AMP2(123)=AMP2(123)+AMP(123)*DCONJG(AMP(123))
      AMP2(124)=AMP2(124)+AMP(124)*DCONJG(AMP(124))
      AMP2(125)=AMP2(125)+AMP(125)*DCONJG(AMP(125))
      AMP2(126)=AMP2(126)+AMP(126)*DCONJG(AMP(126))
      AMP2(127)=AMP2(127)+AMP(127)*DCONJG(AMP(127))
      AMP2(128)=AMP2(128)+AMP(128)*DCONJG(AMP(128))
      DO I = 1, NCOLOR
        DO M = 1, NAMPSO
          DO N = 1, NAMPSO
            IF (CHOSEN_SO_CONFIGS(SQSOINDEX(M,N))) THEN
              JAMP2(I)=JAMP2(I)+DABS(DBLE(JAMP(I,M)*DCONJG(JAMP(I,N))))
            ENDIF
          ENDDO
        ENDDO
      ENDDO

      END

C     Set of functions to handle the array indices of the split orders


      INTEGER FUNCTION SQSOINDEX(ORDERINDEXA, ORDERINDEXB)
C     
C     This functions plays the role of the interference matrix. It can
C      be hardcoded or 
C     made more elegant using hashtables if its execution speed ever
C      becomes a relevant
C     factor. From two split order indices, it return the
C      corresponding index in the squared 
C     order canonical ordering.
C     
C     CONSTANTS
C     

      INTEGER    NSO, NSQUAREDSO, NAMPSO
      PARAMETER (NSO=1, NSQUAREDSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERINDEXA, ORDERINDEXB
C     
C     LOCAL VARIABLES
C     
      INTEGER I, SQORDERS(NSO)
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      DATA (AMPSPLITORDERS(  1,I),I=  1,  1) /    1/
      COMMON/AMPSPLITORDERS/AMPSPLITORDERS
C     
C     FUNCTION
C     
      INTEGER SOINDEX_FOR_SQUARED_ORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSO
        SQORDERS(I)=AMPSPLITORDERS(ORDERINDEXA,I)
     $   +AMPSPLITORDERS(ORDERINDEXB,I)
      ENDDO
      SQSOINDEX=SOINDEX_FOR_SQUARED_ORDERS(SQORDERS)
      END

      INTEGER FUNCTION SOINDEX_FOR_SQUARED_ORDERS(ORDERS)
C     
C     This functions returns the integer index identifying the squared
C      split orders list passed in argument which corresponds to the
C      values of the following list of couplings (and in this order).
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO, NAMPSO
      PARAMETER (NSO=1, NSQSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER SQSPLITORDERS(NSQSO,NSO)
      DATA (SQSPLITORDERS(  1,I),I=  1,  1) /    2/
      COMMON/SQPLITORDERS/SQPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSQSO
        DO J=1,NSO
          IF (ORDERS(J).NE.SQSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_SQUARED_ORDERS = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping in function'
      WRITE(*,*) 'SOINDEX_FOR_SQUARED_ORDERS'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

      SUBROUTINE GET_NSQSO_BORN(NSQSO)
C     
C     Simple subroutine returning the number of squared split order
C     contributions returned when calling smatrix_split_orders 
C     

      INTEGER    NSQUAREDSO
      PARAMETER  (NSQUAREDSO=1)

      INTEGER NSQSO

      NSQSO=NSQUAREDSO

      END

C     This is the inverse subroutine of SOINDEX_FOR_SQUARED_ORDERS.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_SQUARED_ORDERS_FOR_SOINDEX(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the squared
C      split order index in argument. Order values correspond to
C      following list of couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO
      PARAMETER (NSO=1, NSQSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER SQPLITORDERS(NSQSO,NSO)
      COMMON/SQPLITORDERS/SQPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NSQSO) THEN
        DO I=1,NSO
          ORDERS(I) =  SQPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function'
     $ //' GET_SQUARED_ORDERS_FOR_SOINDEX'
      WRITE(*,*) 'Could not find squared orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This is the inverse subroutine of getting amplitude SO orders.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_ORDERS_FOR_AMPSOINDEX(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the split order
C      index in argument. Order values correspond to following list of
C      couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NAMPSO) THEN
        DO I=1,NSO
          ORDERS(I) =  AMPSPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function GET_ORDERS_FOR_AMPSOINDEX'
      WRITE(*,*) 'Could not find amplitude split orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This function is not directly useful, but included for
C      completeness
      INTEGER FUNCTION SOINDEX_FOR_AMPORDERS(ORDERS)
C     
C     This functions returns the integer index identifying the
C      amplitude split orders passed in argument which correspond to
C      the values of the following list of couplings (and in this
C      order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NAMPSO
        DO J=1,NSO
          IF (ORDERS(J).NE.AMPSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_AMPORDERS = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping function SOINDEX_FOR_AMPORDERS'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

