ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_general_MwScheme_UFO-zfac'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_5899 = ', GC_5899
      WRITE(*,2) 'GC_5909 = ', GC_5909
      WRITE(*,2) 'GC_5911 = ', GC_5911
      WRITE(*,2) 'GC_6187 = ', GC_6187
      WRITE(*,2) 'GC_6465 = ', GC_6465
      WRITE(*,2) 'GC_6528 = ', GC_6528
      WRITE(*,2) 'GC_6530 = ', GC_6530
      WRITE(*,2) 'GC_6944 = ', GC_6944
