ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_general_MwScheme_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_6514 = ', GC_6514
      WRITE(*,2) 'GC_6517 = ', GC_6517
      WRITE(*,2) 'GC_6528 = ', GC_6528
      WRITE(*,2) 'GC_6530 = ', GC_6530
      WRITE(*,2) 'GC_6991 = ', GC_6991
      WRITE(*,2) 'GC_6994 = ', GC_6994
      WRITE(*,2) 'GC_7005 = ', GC_7005
      WRITE(*,2) 'GC_7007 = ', GC_7007
      WRITE(*,2) 'GC_7250 = ', GC_7250
      WRITE(*,2) 'GC_7257 = ', GC_7257
      WRITE(*,2) 'GC_7262 = ', GC_7262
      WRITE(*,2) 'GC_7269 = ', GC_7269
      WRITE(*,2) 'GC_7274 = ', GC_7274
      WRITE(*,2) 'GC_7281 = ', GC_7281
