ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP1( )

      IMPLICIT NONE

      INCLUDE 'model_functions.inc'
      INCLUDE '../vector.inc'


      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_6514 = (MDL_CEWIM12*MDL_CTH*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_6517 = -((MDL_CEWIM21*MDL_CTH*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_6528 = -((MDL_CEWRE12*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_6530 = -((MDL_CEWRE21*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_6991 = (MDL_CEBIM12*MDL_STH*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_6994 = -((MDL_CEBIM21*MDL_STH*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_7005 = -((MDL_CEBRE12*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_7007 = -((MDL_CEBRE21*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_7250 = -(MDL_CHEIM12*MDL_EE*MDL_VEVHAT__EXP__2)/(2.000000D+00
     $ *MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_7257 = (MDL_CHERE12*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(2.000000D+00*MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_7262 = -(MDL_CHL1IM12*MDL_EE*MDL_VEVHAT__EXP__2)/(2.000000D
     $ +00*MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_7269 = (MDL_CHL1RE12*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(2.000000D+00*MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_7274 = -(MDL_CHL3IM12*MDL_EE*MDL_VEVHAT__EXP__2)/(2.000000D
     $ +00*MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_7281 = (MDL_CHL3RE12*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(2.000000D+00*MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      END
