ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_general_MwScheme_UFO-zfac'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_5909 = ', GC_5909
      WRITE(*,2) 'GC_6186 = ', GC_6186
      WRITE(*,2) 'GC_6635 = ', GC_6635
      WRITE(*,2) 'GC_6636 = ', GC_6636
      WRITE(*,2) 'GC_6638 = ', GC_6638
      WRITE(*,2) 'GC_7674 = ', GC_7674
      WRITE(*,2) 'GC_7694 = ', GC_7694
