ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP1( )

      IMPLICIT NONE

      INCLUDE 'model_functions.inc'
      INCLUDE '../vector.inc'


      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_5899 = -((MDL_EE*MDL_COMPLEXI)/(MDL_STH*MDL_SQRT__2))
      GC_5909 = -(MDL_EE*MDL_COMPLEXI)/(2.000000D+00*MDL_CTH*MDL_STH)
      GC_5911 = -((MDL_CTH*MDL_EE*MDL_COMPLEXI)/MDL_STH)
      GC_6185 = -(MDL_EE*MDL_COMPLEXI*MDL_STH)/(3.000000D+00*MDL_CTH)
      GC_6186 = (2.000000D+00*MDL_EE*MDL_COMPLEXI*MDL_STH)/(3.000000D
     $ +00*MDL_CTH)
      GC_6637 = (MDL_CTH*MDL_CUWRE13*MDL_COMPLEXI*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_6641 = (MDL_CTH*MDL_CUWRE31*MDL_COMPLEXI*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2)
      GC_7444 = (MDL_CKM1X3*MDL_CUWRE11*MDL_COMPLEXI*MDL_VEVHAT)
     $ /MDL_LAMBDASMEFT__EXP__2+(MDL_CKM2X3*MDL_CUWRE21*MDL_COMPLEXI
     $ *MDL_VEVHAT)/MDL_LAMBDASMEFT__EXP__2+(MDL_CKM3X3*MDL_CUWRE31
     $ *MDL_COMPLEXI*MDL_VEVHAT)/MDL_LAMBDASMEFT__EXP__2
      GC_7557 = (MDL_CKM1X3*MDL_CTH*MDL_CUWRE11*MDL_EE*MDL_COMPLEXI
     $ *MDL_VEVHAT)/(MDL_LAMBDASMEFT__EXP__2*MDL_STH)+(MDL_CKM2X3
     $ *MDL_CTH*MDL_CUWRE21*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_STH)+(MDL_CKM3X3*MDL_CTH
     $ *MDL_CUWRE31*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      END
