ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_general_MwScheme_UFO-zfac'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_5899 = ', GC_5899
      WRITE(*,2) 'GC_5909 = ', GC_5909
      WRITE(*,2) 'GC_5911 = ', GC_5911
      WRITE(*,2) 'GC_6185 = ', GC_6185
      WRITE(*,2) 'GC_6186 = ', GC_6186
      WRITE(*,2) 'GC_6637 = ', GC_6637
      WRITE(*,2) 'GC_6641 = ', GC_6641
      WRITE(*,2) 'GC_7444 = ', GC_7444
      WRITE(*,2) 'GC_7557 = ', GC_7557
