C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -(P(-1,3)*Gamma(-1,2,-3)*Gamma(3,-3,-2)*ProjM(-2,1)) +
C      P(-1,3)*Gamma(-1,-3,-2)*Gamma(3,2,-3)*ProjM(-2,1)
C     
      SUBROUTINE FFV4P1N_3(F1, F2, COUP,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 P3(0:3)
      COMPLEX*16 V3(6)
      V3(1) = +F1(1)+F2(1)
      V3(2) = +F1(2)+F2(2)
      P3(0) = -DBLE(V3(1))
      P3(1) = -DBLE(V3(2))
      P3(2) = -DIMAG(V3(2))
      P3(3) = -DIMAG(V3(1))
      V3(3)= COUP*(-2D0 * CI)*(F1(3)*(F2(4)*(P3(1)+CI*(P3(2)))+P3(3)
     $ *F2(3))+F1(4)*(F2(3)*(P3(1)-CI*(P3(2)))-P3(3)*F2(4)))
      V3(4)= COUP*2D0 * CI*(F1(3)*(F2(4)*(P3(0)+P3(3))+CI*(P3(2)*F2(3))
     $ )+F1(4)*(F2(3)*(P3(0)-P3(3))-CI*(P3(2)*F2(4))))
      V3(5)= COUP*(-2D0)*(F1(3)*(F2(4)*(P3(0)+P3(3))-P3(1)*F2(3))+F1(4)
     $ *(F2(3)*(-P3(0)+P3(3))+P3(1)*F2(4)))
      V3(6)= COUP*(-2D0 * CI)*(F1(3)*(F2(4)*(P3(1)+CI*(P3(2)))-P3(0)
     $ *F2(3))+F1(4)*(F2(3)*(-P3(1)+CI*(P3(2)))+P3(0)*F2(4)))
      END


