ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_general_MwScheme_UFO-zfac'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_5899 = ', GC_5899
      WRITE(*,2) 'GC_5909 = ', GC_5909
      WRITE(*,2) 'GC_5911 = ', GC_5911
      WRITE(*,2) 'GC_6185 = ', GC_6185
      WRITE(*,2) 'GC_6186 = ', GC_6186
      WRITE(*,2) 'GC_6187 = ', GC_6187
      WRITE(*,2) 'GC_6464 = ', GC_6464
      WRITE(*,2) 'GC_6527 = ', GC_6527
      WRITE(*,2) 'GC_6942 = ', GC_6942
