ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP1( )

      IMPLICIT NONE

      INCLUDE 'model_functions.inc'
      INCLUDE '../vector.inc'


      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_5899 = -((MDL_EE*MDL_COMPLEXI)/(MDL_STH*MDL_SQRT__2))
      GC_5909 = -(MDL_EE*MDL_COMPLEXI)/(2.000000D+00*MDL_CTH*MDL_STH)
      GC_5911 = -((MDL_CTH*MDL_EE*MDL_COMPLEXI)/MDL_STH)
      GC_6187 = -((MDL_EE*MDL_COMPLEXI*MDL_STH)/MDL_CTH)
      GC_6464 = (MDL_CEWRE11*MDL_COMPLEXI*MDL_VEVHAT)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_6465 = (MDL_CEWRE12*MDL_COMPLEXI*MDL_VEVHAT)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_6466 = (MDL_CEWRE13*MDL_COMPLEXI*MDL_VEVHAT)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_6467 = (MDL_CEWRE21*MDL_COMPLEXI*MDL_VEVHAT)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_6468 = (MDL_CEWRE22*MDL_COMPLEXI*MDL_VEVHAT)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_6470 = (MDL_CEWRE31*MDL_COMPLEXI*MDL_VEVHAT)
     $ /MDL_LAMBDASMEFT__EXP__2
      GC_6527 = -((MDL_CEWRE11*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_6528 = -((MDL_CEWRE12*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_6529 = -((MDL_CEWRE13*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_6530 = -((MDL_CEWRE21*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_6533 = -((MDL_CEWRE31*MDL_CTH*MDL_COMPLEXI*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_6942 = -((MDL_CEWRE11*MDL_CTH*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_STH))
      GC_7004 = -((MDL_CEBRE11*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_7005 = -((MDL_CEBRE12*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_7006 = -((MDL_CEBRE13*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_7007 = -((MDL_CEBRE21*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_7010 = -((MDL_CEBRE31*MDL_COMPLEXI*MDL_STH*MDL_VEVHAT)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_SQRT__2))
      GC_7194 = -((MDL_CHL3RE12*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_STH*MDL_SQRT__2))
      GC_7195 = -((MDL_CHL3RE13*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(MDL_LAMBDASMEFT__EXP__2*MDL_STH*MDL_SQRT__2))
      GC_7256 = (MDL_CHERE11*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(2.000000D+00*MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_7257 = (MDL_CHERE12*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(2.000000D+00*MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_7258 = (MDL_CHERE13*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(2.000000D+00*MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_7268 = (MDL_CHL1RE11*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(2.000000D+00*MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_7269 = (MDL_CHL1RE12*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(2.000000D+00*MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_7270 = (MDL_CHL1RE13*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(2.000000D+00*MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_7280 = -(MDL_CHL3RE12*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(2.000000D+00*MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_7282 = -(MDL_CHL3RE13*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(2.000000D+00*MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_7639 = (MDL_CHL3RE11*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(2.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_STH*MDL_SQRT__2)
     $ -(MDL_CHL3RE22*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(2.000000D+00*MDL_LAMBDASMEFT__EXP__2*MDL_STH*MDL_SQRT__2)
      GC_7675 = (MDL_CHL3RE11*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(4.000000D+00*MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
     $ -(MDL_CHL3RE22*MDL_EE*MDL_COMPLEXI*MDL_VEVHAT__EXP__2)
     $ /(4.000000D+00*MDL_CTH*MDL_LAMBDASMEFT__EXP__2*MDL_STH)
      GC_7690 = (MDL_CHL3RE11*MDL_CTH*MDL_EE*MDL_COMPLEXI
     $ *MDL_VEVHAT__EXP__2)/(2.000000D+00*MDL_LAMBDASMEFT__EXP__2
     $ *MDL_STH)+(MDL_CHL3RE22*MDL_CTH*MDL_EE*MDL_COMPLEXI
     $ *MDL_VEVHAT__EXP__2)/(2.000000D+00*MDL_LAMBDASMEFT__EXP__2
     $ *MDL_STH)
      GC_7695 = (MDL_CHL3RE11*MDL_EE*MDL_COMPLEXI*MDL_STH
     $ *MDL_VEVHAT__EXP__2)/(2.000000D+00*MDL_CTH
     $ *MDL_LAMBDASMEFT__EXP__2)+(MDL_CHL3RE22*MDL_EE*MDL_COMPLEXI
     $ *MDL_STH*MDL_VEVHAT__EXP__2)/(2.000000D+00*MDL_CTH
     $ *MDL_LAMBDASMEFT__EXP__2)
      END
