ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_general_MwScheme_UFO-zfac'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_5899 = ', GC_5899
      WRITE(*,2) 'GC_5909 = ', GC_5909
      WRITE(*,2) 'GC_5911 = ', GC_5911
      WRITE(*,2) 'GC_6187 = ', GC_6187
      WRITE(*,2) 'GC_6464 = ', GC_6464
      WRITE(*,2) 'GC_6465 = ', GC_6465
      WRITE(*,2) 'GC_6466 = ', GC_6466
      WRITE(*,2) 'GC_6467 = ', GC_6467
      WRITE(*,2) 'GC_6468 = ', GC_6468
      WRITE(*,2) 'GC_6470 = ', GC_6470
      WRITE(*,2) 'GC_6527 = ', GC_6527
      WRITE(*,2) 'GC_6528 = ', GC_6528
      WRITE(*,2) 'GC_6529 = ', GC_6529
      WRITE(*,2) 'GC_6530 = ', GC_6530
      WRITE(*,2) 'GC_6533 = ', GC_6533
      WRITE(*,2) 'GC_6942 = ', GC_6942
      WRITE(*,2) 'GC_7004 = ', GC_7004
      WRITE(*,2) 'GC_7005 = ', GC_7005
      WRITE(*,2) 'GC_7006 = ', GC_7006
      WRITE(*,2) 'GC_7007 = ', GC_7007
      WRITE(*,2) 'GC_7010 = ', GC_7010
      WRITE(*,2) 'GC_7194 = ', GC_7194
      WRITE(*,2) 'GC_7195 = ', GC_7195
      WRITE(*,2) 'GC_7256 = ', GC_7256
      WRITE(*,2) 'GC_7257 = ', GC_7257
      WRITE(*,2) 'GC_7258 = ', GC_7258
      WRITE(*,2) 'GC_7268 = ', GC_7268
      WRITE(*,2) 'GC_7269 = ', GC_7269
      WRITE(*,2) 'GC_7270 = ', GC_7270
      WRITE(*,2) 'GC_7280 = ', GC_7280
      WRITE(*,2) 'GC_7282 = ', GC_7282
      WRITE(*,2) 'GC_7639 = ', GC_7639
      WRITE(*,2) 'GC_7675 = ', GC_7675
      WRITE(*,2) 'GC_7690 = ', GC_7690
      WRITE(*,2) 'GC_7695 = ', GC_7695
