C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -(P(-1,3)*Gamma(-1,2,-3)*Gamma(3,-3,-2)*ProjM(-2,1)) +
C      P(-1,3)*Gamma(-1,-3,-2)*Gamma(3,2,-3)*ProjM(-2,1)
C     
      SUBROUTINE FFVS3P1N_1(F2, V3, S4, COUP,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      REAL*8 P3(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 V3(*)
      P3(0) = DBLE(V3(1))
      P3(1) = DBLE(V3(2))
      P3(2) = DIMAG(V3(2))
      P3(3) = DIMAG(V3(1))
      F1(3)= COUP*2D0 * CI * S4(3)*(F2(4)*(P3(0)*(V3(4)+CI*(V3(5)))
     $ +(P3(1)*(-1D0)*(V3(3)+V3(6))+(P3(2)*(-1D0)*(+CI*(V3(3)+V3(6)))
     $ +P3(3)*(V3(4)+CI*(V3(5))))))+F2(3)*(V3(6)*P3(0)-CI*(V3(5)*P3(1))
     $ +CI*(V3(4)*P3(2))-V3(3)*P3(3)))
      F1(4)= COUP*2D0 * CI * S4(3)*(F2(3)*(P3(0)*(V3(4)-CI*(V3(5)))
     $ +(P3(1)*(-V3(3)+V3(6))+(P3(2)*(+CI*(V3(3))-CI*(V3(6)))+P3(3)*(
     $ -V3(4)+CI*(V3(5))))))+F2(4)*(-V3(6)*P3(0)+CI*(V3(5)*P3(1))-CI
     $ *(V3(4)*P3(2))+V3(3)*P3(3)))
      F1(5)= COUP*0D0
      F1(6)= COUP*0D0
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -(P(-1,3)*Gamma(-1,2,-3)*Gamma(3,-3,-2)*ProjM(-2,1)) +
C      P(-1,3)*Gamma(-1,-3,-2)*Gamma(3,2,-3)*ProjM(-2,1)
C     
      SUBROUTINE FFVS3_7P1N_1(F2, V3, S4, COUP1, COUP2,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      COMPLEX*16 FTMP(6)
      REAL*8 P3(0:3)
      COMPLEX*16 S4(*)
      COMPLEX*16 V3(*)
      INTEGER*4 I
      CALL FFVS3P1N_1(F2,V3,S4,COUP1,F1)
      CALL FFVS7P1N_1(F2,V3,S4,COUP2,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      END


