ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_general_MwScheme_UFO-zfac'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_5909 = ', GC_5909
      WRITE(*,2) 'GC_6187 = ', GC_6187
      WRITE(*,2) 'GC_6361 = ', GC_6361
      WRITE(*,2) 'GC_6527 = ', GC_6527
      WRITE(*,2) 'GC_6738 = ', GC_6738
      WRITE(*,2) 'GC_7028 = ', GC_7028
      WRITE(*,2) 'GC_5263 = ', GC_5263
