C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,1)*Metric(1,2) - P(2,1)*Metric(1,3)
C     
      SUBROUTINE VVV1P1N_1(V2, V3, COUP,V1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 P1(0:3)
      COMPLEX*16 TMP0
      COMPLEX*16 TMP10
      COMPLEX*16 V1(6)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      V1(1) = +V2(1)+V3(1)
      V1(2) = +V2(2)+V3(2)
      P1(0) = -DBLE(V1(1))
      P1(1) = -DBLE(V1(2))
      P1(2) = -DIMAG(V1(2))
      P1(3) = -DIMAG(V1(1))
      TMP0 = (V2(3)*P1(0)-V2(4)*P1(1)-V2(5)*P1(2)-V2(6)*P1(3))
      TMP10 = (P1(0)*V3(3)-P1(1)*V3(4)-P1(2)*V3(5)-P1(3)*V3(6))
      V1(3)= COUP*(-CI*(V2(3)*TMP10)+CI*(TMP0*V3(3)))
      V1(4)= COUP*(+CI*(V2(4)*TMP10)-CI*(TMP0*V3(4)))
      V1(5)= COUP*(+CI*(V2(5)*TMP10)-CI*(TMP0*V3(5)))
      V1(6)= COUP*(+CI*(V2(6)*TMP10)-CI*(TMP0*V3(6)))
      END


