ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_general_MwScheme_UFO-zfac'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_6361 = ', GC_6361
      WRITE(*,2) 'GC_6508 = ', GC_6508
      WRITE(*,2) 'GC_6510 = ', GC_6510
      WRITE(*,2) 'GC_6738 = ', GC_6738
      WRITE(*,2) 'GC_7009 = ', GC_7009
      WRITE(*,2) 'GC_7011 = ', GC_7011
      WRITE(*,2) 'GC_7743 = ', GC_7743
      WRITE(*,2) 'GC_6208 = ', GC_6208
      WRITE(*,2) 'GC_6210 = ', GC_6210
