ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_general_MwScheme_UFO-zfac'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_6361 = ', GC_6361
      WRITE(*,2) 'GC_6529 = ', GC_6529
      WRITE(*,2) 'GC_6533 = ', GC_6533
      WRITE(*,2) 'GC_6738 = ', GC_6738
      WRITE(*,2) 'GC_7030 = ', GC_7030
      WRITE(*,2) 'GC_7034 = ', GC_7034
      WRITE(*,2) 'GC_7743 = ', GC_7743
      WRITE(*,2) 'GC_5265 = ', GC_5265
      WRITE(*,2) 'GC_5269 = ', GC_5269
