ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_general_MwScheme_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_5899 = ', GC_5899
      WRITE(*,2) 'GC_5909 = ', GC_5909
      WRITE(*,2) 'GC_5910 = ', GC_5910
      WRITE(*,2) 'GC_5911 = ', GC_5911
      WRITE(*,2) 'GC_6162 = ', GC_6162
      WRITE(*,2) 'GC_6174 = ', GC_6174
      WRITE(*,2) 'GC_6185 = ', GC_6185
      WRITE(*,2) 'GC_6186 = ', GC_6186
      WRITE(*,2) 'GC_6187 = ', GC_6187
      WRITE(*,2) 'GC_6447 = ', GC_6447
      WRITE(*,2) 'GC_6464 = ', GC_6464
      WRITE(*,2) 'GC_6512 = ', GC_6512
      WRITE(*,2) 'GC_6527 = ', GC_6527
      WRITE(*,2) 'GC_6932 = ', GC_6932
      WRITE(*,2) 'GC_6942 = ', GC_6942
      WRITE(*,2) 'GC_6989 = ', GC_6989
      WRITE(*,2) 'GC_7004 = ', GC_7004
      WRITE(*,2) 'GC_7161 = ', GC_7161
      WRITE(*,2) 'GC_7162 = ', GC_7162
      WRITE(*,2) 'GC_7163 = ', GC_7163
      WRITE(*,2) 'GC_7224 = ', GC_7224
      WRITE(*,2) 'GC_7235 = ', GC_7235
      WRITE(*,2) 'GC_7237 = ', GC_7237
      WRITE(*,2) 'GC_7256 = ', GC_7256
      WRITE(*,2) 'GC_7268 = ', GC_7268
      WRITE(*,2) 'GC_7322 = ', GC_7322
      WRITE(*,2) 'GC_7323 = ', GC_7323
      WRITE(*,2) 'GC_7324 = ', GC_7324
      WRITE(*,2) 'GC_7329 = ', GC_7329
      WRITE(*,2) 'GC_7330 = ', GC_7330
      WRITE(*,2) 'GC_7336 = ', GC_7336
      WRITE(*,2) 'GC_7339 = ', GC_7339
      WRITE(*,2) 'GC_7640 = ', GC_7640
      WRITE(*,2) 'GC_7675 = ', GC_7675
      WRITE(*,2) 'GC_7676 = ', GC_7676
      WRITE(*,2) 'GC_7690 = ', GC_7690
      WRITE(*,2) 'GC_7695 = ', GC_7695
      WRITE(*,2) 'GC_5678 = ', GC_5678
      WRITE(*,2) 'GC_5679 = ', GC_5679
