ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_general_MwScheme_UFO-zfac'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_6361 = ', GC_6361
      WRITE(*,2) 'GC_6505 = ', GC_6505
      WRITE(*,2) 'GC_6509 = ', GC_6509
      WRITE(*,2) 'GC_6738 = ', GC_6738
      WRITE(*,2) 'GC_7006 = ', GC_7006
      WRITE(*,2) 'GC_7010 = ', GC_7010
      WRITE(*,2) 'GC_7743 = ', GC_7743
      WRITE(*,2) 'GC_6205 = ', GC_6205
      WRITE(*,2) 'GC_6209 = ', GC_6209
