C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-2)*Gamma(4,-2,-1)*ProjP(-1,1) -
C      Gamma(3,-2,-1)*Gamma(4,2,-2)*ProjP(-1,1)
C     
      SUBROUTINE FFVV5P1N_3(F1, F2, V4, COUP,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 V3(6)
      COMPLEX*16 V4(*)
      V3(3)= COUP*2D0 * CI*(F1(5)*(F2(6)*(V4(4)+CI*(V4(5)))+F2(5)*V4(6)
     $ )+F1(6)*(F2(5)*(V4(4)-CI*(V4(5)))-F2(6)*V4(6)))
      V3(4)= COUP*(-2D0 * CI)*(F1(5)*(F2(6)*(V4(3)-V4(6))-CI*(F2(5)
     $ *V4(5)))+F1(6)*(F2(5)*(V4(3)+V4(6))+CI*(F2(6)*V4(5))))
      V3(5)= COUP*(-2D0)*(F1(5)*(F2(6)*(-V4(3)+V4(6))-F2(5)*V4(4))
     $ +F1(6)*(F2(5)*(V4(3)+V4(6))+F2(6)*V4(4)))
      V3(6)= COUP*(-2D0 * CI)*(F1(5)*(F2(6)*(V4(4)+CI*(V4(5)))+F2(5)
     $ *V4(3))+F1(6)*(F2(5)*(-V4(4)+CI*(V4(5)))-F2(6)*V4(3)))
      END


