      SUBROUTINE SMATRIX1(P, RHEL, RCOL, channel, IVEC, ANS, IHEL,
     $  ICOL)
C     
C     Generated by MadGraph5_aMC@NLO v. 3.6.3, 2025-06-12
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO for Madevent Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     potentially times multi-channel weight
C     
C     Process: c c~ > z WEIGHTED<=2 @1
C     *   Decay: z > e- w+ ve~ NP<=1 NPceW<=1
C     *     Decay: w+ > mu+ vm WEIGHTED<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      Include 'genps.inc'
      Include 'maxconfigs.inc'
      Include 'nexternal.inc'
      Include 'maxamps.inc'
      INTEGER                 NCOMB         
      PARAMETER (             NCOMB=8)
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=43) 
      INTEGER    NDIAGS
      PARAMETER (NDIAGS=43) 
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      double precision RHEL    !  random number for selecting helicity
      double precision RCOL    !  random number for selecting helicity
      integer channel    !  channel to keep for the multi-channel
      integer ivec    !  for using the correct coupling
C     
C     output argument
C     
      integer ihel, icol    !  selected helicity/color
      double precision ans 
C     
C     LOCAL VARIABLES 
C     
      INTEGER CONFSUB(MAXSPROC,LMAXCONFIGS)
      INCLUDE 'config_subproc_map.inc'
      INTEGER NHEL(0:NEXTERNAL,NCOMB)
      REAL*8 T
      REAL*8 R,SUMHEL,TS(NCOMB)
      INTEGER I,IDEN
      INTEGER JC(NEXTERNAL),II
      REAL*8 XTOT
      INTEGER  J, JJ
      double precision get_channel_cut
      external get_channel_cut

C     
C     GLOBAL VARIABLES
C     
      include '../../Source/vector.inc'    !  defines VECSIZE_MEMMAX
      DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)


C     
C     INFORMATION TO WRITE THE HELICITY IN THE EVENT --not memory
C      efficient--
C     
      INTEGER NB_SPIN_STATE_in(2)
      common /nb_hel_state/ nb_spin_state_in

      REAL*8 POL(2)

      COMMON/TO_POLARIZATION/ POL
      double precision tmin_for_channel
      integer sde_strat    !  1 means standard single diagram enhancement strategy,
C     2 means approximation by the	denominator of the propagator
      common/TO_CHANNEL_STRAT/tmin_for_channel,	sde_strat

      INTEGER          ISUM_HEL
      LOGICAL                    MULTI_CHANNEL
      COMMON/TO_MATRIX/ISUM_HEL, MULTI_CHANNEL
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      COMMON/TO_MCONFIGS/MAPCONFIG, ICONFIG
      
      DATA (NHEL(I,1),I=0,6) /1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,2),I=0,6) /5, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,3),I=0,6) /9, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,4),I=0,6) /17, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,5),I=0,6) /33,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,6),I=0,6) /49,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,7),I=0,6) /53,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,8),I=0,6) /57,-1, 1, 1, 1,-1, 1/
      DATA IDEN/36/

C     ----------
C     BEGIN CODE
C     ----------

      DO I=1,NEXTERNAL
        JC(I) = +1
      ENDDO

      IF (multi_channel) THEN
        DO I=1,NDIAGS
          AMP2(I)=0D0
        ENDDO
      ENDIF
      JAMP2(0)=1
      DO I=1,INT(JAMP2(0))
        JAMP2(I)=0D0
      ENDDO


      ANS = 0D0

      TS(:) = 0d0

      call MATRIX1(P ,JC(1), TS, AMP2, JAMP2, IVEC)
      DO I=1,NCOMB     
        T=TS(I)  
        DO JJ=1,nincoming
          IF(POL(JJ).NE.1d0.AND.NHEL(JJ,I).EQ.INT(SIGN(1d0,POL(JJ))))
     $      THEN
            T=T*ABS(POL(JJ))*NB_SPIN_STATE_IN(JJ)/2d0    !  NB_SPIN_STATE(JJ)/2d0 is added for polarised beam
          ELSE IF(POL(JJ).NE.1d0)THEN
            T=T*(2d0-ABS(POL(JJ)))*NB_SPIN_STATE_IN(JJ)/2d0
          ENDIF
        ENDDO
        ANS=ANS+DABS(T)
        TS(I)=T
      ENDDO

      IF (ANS.ne.0d0) THEN
        SUMHEL=0d0
        DO I=1,NCOMB
          SUMHEL=SUMHEL+DABS(TS(I))/ANS
          IF(RHEL.LT.SUMHEL)THEN
            IHEL = NHEL(0,I)    !  this returns the id of the helicity before helicity recycling
C           WRITE(HEL_BUFF,'(20i5)')(NHEL(II,I),II=1,NEXTERNAL)
C           Set right sign for ANS, based on sign of chosen helicity
            ANS=DSIGN(ANS,TS(I))
            GOTO 10
          ENDIF
        ENDDO
 10     CONTINUE   
      ENDIF
      IF (MULTI_CHANNEL) THEN
        XTOT=0D0
        DO I=1,LMAXCONFIGS
          J = CONFSUB(1, I)
          if (J.ne.0)then
            if (sde_strat.eq.1)then
              AMP2(J) = AMP2(J) * GET_CHANNEL_CUT(P, I)
            else
              AMP2(J) = GET_CHANNEL_CUT(P, I)
            endif
            XTOT=XTOT+AMP2(J)

          endif
        ENDDO
        IF (XTOT.NE.0D0) THEN
          ANS=ANS*AMP2(channel)/XTOT
        ELSE IF(ANS.ne.0d0) THEN
          write(*,*) 'Problem in the multi-channeling. All amp2 are'
     $     //' zero but not the total matrix-element'
          stop 1
        ENDIF
      ENDIF
      ANS=ANS/DBLE(IDEN)

      call select_color(rcol, jamp2, iconfig,1,  icol)

      END


      Subroutine  MATRIX1(P,IC, TS, AMP2, JAMP2, IVEC)
C     
C     Generated by MadGraph5_aMC@NLO v. 3.6.3, 2025-06-12
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: c c~ > z WEIGHTED<=2 @1
C     *   Decay: z > e- w+ ve~ NP<=1 NPceW<=1
C     *     Decay: w+ > mu+ vm WEIGHTED<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=43) 
      include 'genps.inc'
      include 'nexternal.inc'
      include 'maxamps.inc'
      INTEGER    NWAVEFUNCS,     NCOLOR
      PARAMETER (NWAVEFUNCS=178, NCOLOR=1) 
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      LOGICAL CHOSEN_SO_CONFIGS(NSQAMPSO)
      DATA CHOSEN_SO_CONFIGS/.TRUE./
      SAVE CHOSEN_SO_CONFIGS
      INTEGER                 NCOMB         
      PARAMETER (             NCOMB=8)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
      REAL*8 TS(NCOMB)
      INTEGER IVEC
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,M,N,K
      COMPLEX*16 ZTEMP,TMP_JAMP(0)
      COMPLEX*16 TMP(6)
      INTEGER CF(NCOLOR*(NCOLOR+1))
      INTEGER DENOM, CF_INDEX
      COMPLEX*16 AMP(NCOMB,NGRAPHS), JAMP(NCOLOR,NAMPSO)
      COMPLEX*16 W(6,NWAVEFUNCS)
C     Needed for v4 models
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0d0, 0d0), (1d0, 0d0)/

      double precision fk_mdl_WW1 
      double precision fk_mdl_WZ 
      double precision fk_mdl_WW 
      double precision fk_ZERO 
      save fk_mdl_WW1 
      save fk_mdl_WZ 
      save fk_mdl_WW 
      save fk_ZERO 

      logical first
      data first /.true./
      save first
C     
C     FUNCTION
C     
      INTEGER SQSOINDEX1

C     
C     GLOBAL VARIABLES
C     
      include '../../Source/vector.inc'    !  defines VECSIZE_MEMMAX
      Double Precision amp2(maxamps), jamp2(0:maxflow)
      include 'coupl.inc'    !  needs VECSIZE_MEMMAX (defined in vector.inc)

      double precision tmin_for_channel
      integer sde_strat    !  1 means standard single diagram enhancement strategy,
C     2 means approximation by the	denominator of the propagator
      common/TO_CHANNEL_STRAT/tmin_for_channel,	sde_strat

      double precision small_width_treatment
      common/narrow_width/small_width_treatment
C     
C     COLOR DATA
C     
      DATA Denom/1/
      DATA (CF(i),i=  1,  1) /3/
C     1 T(2,1)
C     ----------
C     BEGIN CODE
C     ----------
      if (first) then
        first=.false.
        fk_zero = 0d0
        IF(mdl_WW.ne.0d0) then 
          fk_mdl_WW = SIGN(MAX(ABS(mdl_WW), ABS(mdl_MW
     $     *small_width_treatment)), mdl_WW) 
        else 
          fk_mdl_WW = 0d0
        endif

        IF(mdl_WW1.ne.0d0) then 
          fk_mdl_WW1 = SIGN(MAX(ABS(mdl_WW1), ABS(mdl_MW1
     $     *small_width_treatment)), mdl_WW1) 
        else 
          fk_mdl_WW1 = 0d0
        endif

        IF(mdl_WZ.ne.0d0) then 
          fk_mdl_WZ = SIGN(MAX(ABS(mdl_WZ), ABS(mdl_MZ
     $     *small_width_treatment)), mdl_WZ) 
        else 
          fk_mdl_WZ = 0d0
        endif

      endif
      AMP(:,:) = (0d0,0d0)
            CALL IXXXXX(P(0,1),MDL_MC,+1,+1*IC(1),W(1,1))  !  count 172
      CALL IXXXXX(P(0,1),MDL_MC,-1,+1*IC(1),W(1,2))  !  count 172
      CALL OXXXXX(P(0,2),MDL_MC,+1,-1*IC(2),W(1,3))  !  count 172
      CALL OXXXXX(P(0,2),MDL_MC,-1,-1*IC(2),W(1,4))  !  count 172
      CALL OXXXXX(P(0,3),MDL_ME,+1,+1*IC(3),W(1,5))  !  count 31
      CALL OXXXXX(P(0,3),MDL_ME,-1,+1*IC(3),W(1,6))  !  count 56
      CALL IXXXXX(P(0,4),MDL_MMU,+1,-1*IC(4),W(1,7))  !  count 1
      CALL IXXXXX(P(0,4),MDL_MMU,-1,-1*IC(4),W(1,8))  !  count 1
      CALL OXXXXX(P(0,5),ZERO,-1,+1*IC(5),W(1,9))  !  count 2
      CALL FFV3_3(W(1,7),W(1,9),GC_5899,MDL_MW,FK_MDL_WW,W(1,10))  !  count 47
      CALL FFV3_3(W(1,8),W(1,9),GC_5899,MDL_MW,FK_MDL_WW,W(1,11))  !  count 26
      CALL IXXXXX(P(0,6),ZERO,+1,-1*IC(6),W(1,12))  !  count 55
      CALL FFV4_1(W(1,5),W(1,10),GC_6447,ZERO,FK_ZERO,W(1,13))  !  count 1
      CALL FFV4_1(W(1,6),W(1,10),GC_6447,ZERO,FK_ZERO,W(1,14))  !  count 1
      CALL FFV4_1(W(1,6),W(1,11),GC_6447,ZERO,FK_ZERO,W(1,15))  !  count 1
      CALL FFV3_3(W(1,12),W(1,13),GC_5909,MDL_MZ,FK_MDL_WZ,W(1,16))  !  count 2
      CALL FFV3_3(W(1,12),W(1,14),GC_5909,MDL_MZ,FK_MDL_WZ,W(1,17))  !  count 4
      CALL FFV3_3(W(1,12),W(1,15),GC_5909,MDL_MZ,FK_MDL_WZ,W(1,18))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,17),GC_6186,GC_5909,AMP(4,1))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/16,17,18/),
     & TMP, W, AMP(1,1))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/16,17,18/),
     & TMP, W, AMP(1,1))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,17),GC_6186,GC_5909,AMP(5,1))  !  count 1
      CALL FFV3_1(W(1,5),W(1,10),GC_5899,ZERO,FK_ZERO,W(1,19))  !  count 5
      CALL FFV3_1(W(1,6),W(1,10),GC_5899,ZERO,FK_ZERO,W(1,20))  !  count 5
      CALL FFV3_1(W(1,6),W(1,11),GC_5899,ZERO,FK_ZERO,W(1,21))  !  count 5
      CALL FFV3_3(W(1,12),W(1,19),GC_5909,MDL_MZ,FK_MDL_WZ,W(1,22))  !  count 2
      CALL FFV3_3(W(1,12),W(1,20),GC_5909,MDL_MZ,FK_MDL_WZ,W(1,23))  !  count 4
      CALL FFV3_3(W(1,12),W(1,21),GC_5909,MDL_MZ,FK_MDL_WZ,W(1,24))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,23),GC_6186,GC_5909,AMP(4,2))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/22,23,24/),
     & TMP, W, AMP(1,2))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/22,23,24/),
     & TMP, W, AMP(1,2))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,23),GC_6186,GC_5909,AMP(5,2))  !  count 1
      CALL FFV3_3(W(1,12),W(1,19),GC_7235,MDL_MZ,FK_MDL_WZ,W(1,25))  !  count 2
      CALL FFV3_3(W(1,12),W(1,20),GC_7235,MDL_MZ,FK_MDL_WZ,W(1,26))  !  count 4
      CALL FFV3_3(W(1,12),W(1,21),GC_7235,MDL_MZ,FK_MDL_WZ,W(1,27))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,26),GC_6186,GC_5909,AMP(4,3))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/25,26,27/),
     & TMP, W, AMP(1,3))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/25,26,27/),
     & TMP, W, AMP(1,3))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,26),GC_6186,GC_5909,AMP(5,3))  !  count 1
      CALL FFV3_3(W(1,12),W(1,19),GC_7268,MDL_MZ,FK_MDL_WZ,W(1,28))  !  count 2
      CALL FFV3_3(W(1,12),W(1,20),GC_7268,MDL_MZ,FK_MDL_WZ,W(1,29))  !  count 4
      CALL FFV3_3(W(1,12),W(1,21),GC_7268,MDL_MZ,FK_MDL_WZ,W(1,30))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,29),GC_6186,GC_5909,AMP(4,4))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/28,29,30/),
     & TMP, W, AMP(1,4))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/28,29,30/),
     & TMP, W, AMP(1,4))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,29),GC_6186,GC_5909,AMP(5,4))  !  count 1
      CALL FFV3_3(W(1,12),W(1,19),GC_7676,MDL_MZ,FK_MDL_WZ,W(1,31))  !  count 2
      CALL FFV3_3(W(1,12),W(1,20),GC_7676,MDL_MZ,FK_MDL_WZ,W(1,32))  !  count 4
      CALL FFV3_3(W(1,12),W(1,21),GC_7676,MDL_MZ,FK_MDL_WZ,W(1,33))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,32),GC_6186,GC_5909,AMP(4,5))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/31,32,33/),
     & TMP, W, AMP(1,5))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/31,32,33/),
     & TMP, W, AMP(1,5))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,32),GC_6186,GC_5909,AMP(5,5))  !  count 1
      CALL FFV3_3(W(1,12),W(1,19),GC_7322,MDL_MZ,FK_MDL_WZ,W(1,34))  !  count 2
      CALL FFV3_3(W(1,12),W(1,20),GC_7322,MDL_MZ,FK_MDL_WZ,W(1,35))  !  count 4
      CALL FFV3_3(W(1,12),W(1,21),GC_7322,MDL_MZ,FK_MDL_WZ,W(1,36))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,35),GC_6186,GC_5909,AMP(4,6))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/34,35,36/),
     & TMP, W, AMP(1,6))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/34,35,36/),
     & TMP, W, AMP(1,6))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,35),GC_6186,GC_5909,AMP(5,6))  !  count 1
      CALL FFV4_1(W(1,5),W(1,10),GC_6464,ZERO,FK_ZERO,W(1,37))  !  count 1
      CALL FFV4_1(W(1,6),W(1,10),GC_6464,ZERO,FK_ZERO,W(1,38))  !  count 1
      CALL FFV4_1(W(1,6),W(1,11),GC_6464,ZERO,FK_ZERO,W(1,39))  !  count 1
      CALL FFV3_3(W(1,12),W(1,37),GC_5909,MDL_MZ,FK_MDL_WZ,W(1,40))  !  count 2
      CALL FFV3_3(W(1,12),W(1,38),GC_5909,MDL_MZ,FK_MDL_WZ,W(1,41))  !  count 4
      CALL FFV3_3(W(1,12),W(1,39),GC_5909,MDL_MZ,FK_MDL_WZ,W(1,42))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,41),GC_6186,GC_5909,AMP(4,7))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/40,41,42/),
     & TMP, W, AMP(1,7))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/40,41,42/),
     & TMP, W, AMP(1,7))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,41),GC_6186,GC_5909,AMP(5,7))  !  count 1
      CALL FFV3_1(W(1,5),W(1,10),GC_7640,ZERO,FK_ZERO,W(1,43))  !  count 1
      CALL FFV3_1(W(1,6),W(1,10),GC_7640,ZERO,FK_ZERO,W(1,44))  !  count 1
      CALL FFV3_1(W(1,6),W(1,11),GC_7640,ZERO,FK_ZERO,W(1,45))  !  count 1
      CALL FFV3_3(W(1,12),W(1,43),GC_5909,MDL_MZ,FK_MDL_WZ,W(1,46))  !  count 2
      CALL FFV3_3(W(1,12),W(1,44),GC_5909,MDL_MZ,FK_MDL_WZ,W(1,47))  !  count 4
      CALL FFV3_3(W(1,12),W(1,45),GC_5909,MDL_MZ,FK_MDL_WZ,W(1,48))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,47),GC_6186,GC_5909,AMP(4,8))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/46,47,48/),
     & TMP, W, AMP(1,8))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/46,47,48/),
     & TMP, W, AMP(1,8))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,47),GC_6186,GC_5909,AMP(5,8))  !  count 1
      CALL FFV3_1(W(1,5),W(1,10),GC_7224,ZERO,FK_ZERO,W(1,49))  !  count 1
      CALL FFV3_1(W(1,6),W(1,10),GC_7224,ZERO,FK_ZERO,W(1,50))  !  count 1
      CALL FFV3_1(W(1,6),W(1,11),GC_7224,ZERO,FK_ZERO,W(1,51))  !  count 1
      CALL FFV3_3(W(1,12),W(1,49),GC_5909,MDL_MZ,FK_MDL_WZ,W(1,52))  !  count 2
      CALL FFV3_3(W(1,12),W(1,50),GC_5909,MDL_MZ,FK_MDL_WZ,W(1,53))  !  count 4
      CALL FFV3_3(W(1,12),W(1,51),GC_5909,MDL_MZ,FK_MDL_WZ,W(1,54))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,53),GC_6186,GC_5909,AMP(4,9))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/52,53,54/),
     & TMP, W, AMP(1,9))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/52,53,54/),
     & TMP, W, AMP(1,9))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,53),GC_6186,GC_5909,AMP(5,9))  !  count 1
      CALL FFV4_3(W(1,12),W(1,5),GC_6447,MDL_MW,FK_MDL_WW,W(1,55))  !  count 1
      CALL FFV4_3(W(1,12),W(1,6),GC_6447,MDL_MW,FK_MDL_WW,W(1,56))  !  count 2
      CALL VVV5_3(W(1,55),W(1,10),GC_5911,MDL_MZ,FK_MDL_WZ,W(1,57))  !  count 2
      CALL VVV5_3(W(1,56),W(1,10),GC_5911,MDL_MZ,FK_MDL_WZ,W(1,58))  !  count 4
      CALL VVV5_3(W(1,56),W(1,11),GC_5911,MDL_MZ,FK_MDL_WZ,W(1,59))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,58),GC_6186,GC_5909,AMP(4,10))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/57,58,59/),
     & TMP, W, AMP(1,10))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/57,58,59/),
     & TMP, W, AMP(1,10))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,58),GC_6186,GC_5909,AMP(5,10))  !  count 1
      CALL FFV3_3(W(1,12),W(1,5),GC_5899,MDL_MW,FK_MDL_WW,W(1,60))  !  count 9
      CALL FFV3_3(W(1,12),W(1,6),GC_5899,MDL_MW,FK_MDL_WW,W(1,61))  !  count 18
      CALL VVV3_3(W(1,60),W(1,10),GC_7329,MDL_MZ,FK_MDL_WZ,W(1,62))  !  count 2
      CALL VVV3_3(W(1,61),W(1,10),GC_7329,MDL_MZ,FK_MDL_WZ,W(1,63))  !  count 4
      CALL VVV3_3(W(1,61),W(1,11),GC_7329,MDL_MZ,FK_MDL_WZ,W(1,64))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,63),GC_6186,GC_5909,AMP(4,11))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/62,63,64/),
     & TMP, W, AMP(1,11))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/62,63,64/),
     & TMP, W, AMP(1,11))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,63),GC_6186,GC_5909,AMP(5,11))  !  count 1
      CALL VVV2_3(W(1,60),W(1,10),GC_7163,MDL_MZ,FK_MDL_WZ,W(1,65))  !  count 2
      CALL VVV2_3(W(1,61),W(1,10),GC_7163,MDL_MZ,FK_MDL_WZ,W(1,66))  !  count 4
      CALL VVV2_3(W(1,61),W(1,11),GC_7163,MDL_MZ,FK_MDL_WZ,W(1,67))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,66),GC_6186,GC_5909,AMP(4,12))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/65,66,67/),
     & TMP, W, AMP(1,12))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/65,66,67/),
     & TMP, W, AMP(1,12))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,66),GC_6186,GC_5909,AMP(5,12))  !  count 1
      CALL VVV9_3(W(1,60),W(1,10),GC_5679,MDL_MZ,FK_MDL_WZ,W(1,68))  !  count 2
      CALL VVV9_3(W(1,61),W(1,10),GC_5679,MDL_MZ,FK_MDL_WZ,W(1,69))  !  count 4
      CALL VVV9_3(W(1,61),W(1,11),GC_5679,MDL_MZ,FK_MDL_WZ,W(1,70))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,69),GC_6186,GC_5909,AMP(4,13))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/68,69,70/),
     & TMP, W, AMP(1,13))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/68,69,70/),
     & TMP, W, AMP(1,13))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,69),GC_6186,GC_5909,AMP(5,13))  !  count 1
      CALL VVV7_3(W(1,60),W(1,10),GC_5678,MDL_MZ,FK_MDL_WZ,W(1,71))  !  count 2
      CALL VVV7_3(W(1,61),W(1,10),GC_5678,MDL_MZ,FK_MDL_WZ,W(1,72))  !  count 4
      CALL VVV7_3(W(1,61),W(1,11),GC_5678,MDL_MZ,FK_MDL_WZ,W(1,73))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,72),GC_6186,GC_5909,AMP(4,14))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/71,72,73/),
     & TMP, W, AMP(1,14))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/71,72,73/),
     & TMP, W, AMP(1,14))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,72),GC_6186,GC_5909,AMP(5,14))  !  count 1
      CALL VVV5_3(W(1,60),W(1,10),GC_5911,MDL_MZ,FK_MDL_WZ,W(1,74))  !  count 2
      CALL VVV5_3(W(1,61),W(1,10),GC_5911,MDL_MZ,FK_MDL_WZ,W(1,75))  !  count 4
      CALL VVV5_3(W(1,61),W(1,11),GC_5911,MDL_MZ,FK_MDL_WZ,W(1,76))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,75),GC_6186,GC_5909,AMP(4,15))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/74,75,76/),
     & TMP, W, AMP(1,15))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/74,75,76/),
     & TMP, W, AMP(1,15))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,75),GC_6186,GC_5909,AMP(5,15))  !  count 1
      CALL VVV4_3(W(1,60),W(1,10),GC_7161,MDL_MZ,FK_MDL_WZ,W(1,77))  !  count 2
      CALL VVV4_3(W(1,61),W(1,10),GC_7161,MDL_MZ,FK_MDL_WZ,W(1,78))  !  count 4
      CALL VVV4_3(W(1,61),W(1,11),GC_7161,MDL_MZ,FK_MDL_WZ,W(1,79))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,78),GC_6186,GC_5909,AMP(4,16))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/77,78,79/),
     & TMP, W, AMP(1,16))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/77,78,79/),
     & TMP, W, AMP(1,16))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,78),GC_6186,GC_5909,AMP(5,16))  !  count 1
      CALL VVV5_3(W(1,60),W(1,10),GC_7324,MDL_MZ,FK_MDL_WZ,W(1,80))  !  count 2
      CALL VVV5_3(W(1,61),W(1,10),GC_7324,MDL_MZ,FK_MDL_WZ,W(1,81))  !  count 4
      CALL VVV5_3(W(1,61),W(1,11),GC_7324,MDL_MZ,FK_MDL_WZ,W(1,82))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,81),GC_6186,GC_5909,AMP(4,17))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/80,81,82/),
     & TMP, W, AMP(1,17))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/80,81,82/),
     & TMP, W, AMP(1,17))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,81),GC_6186,GC_5909,AMP(5,17))  !  count 1
      CALL VVV5_3(W(1,60),W(1,10),GC_7690,MDL_MZ,FK_MDL_WZ,W(1,83))  !  count 2
      CALL VVV5_3(W(1,61),W(1,10),GC_7690,MDL_MZ,FK_MDL_WZ,W(1,84))  !  count 4
      CALL VVV5_3(W(1,61),W(1,11),GC_7690,MDL_MZ,FK_MDL_WZ,W(1,85))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,84),GC_6186,GC_5909,AMP(4,18))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/83,84,85/),
     & TMP, W, AMP(1,18))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/83,84,85/),
     & TMP, W, AMP(1,18))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,84),GC_6186,GC_5909,AMP(5,18))  !  count 1
      CALL VVV5_3(W(1,60),W(1,10),GC_7330,MDL_MZ,FK_MDL_WZ,W(1,86))  !  count 2
      CALL VVV5_3(W(1,61),W(1,10),GC_7330,MDL_MZ,FK_MDL_WZ,W(1,87))  !  count 4
      CALL VVV5_3(W(1,61),W(1,11),GC_7330,MDL_MZ,FK_MDL_WZ,W(1,88))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,87),GC_6186,GC_5909,AMP(4,19))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/86,87,88/),
     & TMP, W, AMP(1,19))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/86,87,88/),
     & TMP, W, AMP(1,19))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,87),GC_6186,GC_5909,AMP(5,19))  !  count 1
      CALL FFV4_3(W(1,12),W(1,5),GC_6464,MDL_MW,FK_MDL_WW,W(1,89))  !  count 1
      CALL FFV4_3(W(1,12),W(1,6),GC_6464,MDL_MW,FK_MDL_WW,W(1,90))  !  count 2
      CALL VVV5_3(W(1,89),W(1,10),GC_5911,MDL_MZ,FK_MDL_WZ,W(1,91))  !  count 2
      CALL VVV5_3(W(1,90),W(1,10),GC_5911,MDL_MZ,FK_MDL_WZ,W(1,92))  !  count 4
      CALL VVV5_3(W(1,90),W(1,11),GC_5911,MDL_MZ,FK_MDL_WZ,W(1,93))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,92),GC_6186,GC_5909,AMP(4,20))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/91,92,93/),
     & TMP, W, AMP(1,20))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/91,92,93/),
     & TMP, W, AMP(1,20))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,92),GC_6186,GC_5909,AMP(5,20))  !  count 1
      CALL FFV3_3(W(1,12),W(1,5),GC_7640,MDL_MW,FK_MDL_WW,W(1,94))  !  count 1
      CALL FFV3_3(W(1,12),W(1,6),GC_7640,MDL_MW,FK_MDL_WW,W(1,95))  !  count 2
      CALL VVV5_3(W(1,94),W(1,10),GC_5911,MDL_MZ,FK_MDL_WZ,W(1,96))  !  count 2
      CALL VVV5_3(W(1,95),W(1,10),GC_5911,MDL_MZ,FK_MDL_WZ,W(1,97))  !  count 4
      CALL VVV5_3(W(1,95),W(1,11),GC_5911,MDL_MZ,FK_MDL_WZ,W(1,98))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,97),GC_6186,GC_5909,AMP(4,21))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/96,97,98/),
     & TMP, W, AMP(1,21))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/96,97,98/),
     & TMP, W, AMP(1,21))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,97),GC_6186,GC_5909,AMP(5,21))  !  count 1
      CALL FFV3_3(W(1,12),W(1,5),GC_7224,MDL_MW,FK_MDL_WW,W(1,99))  !  count 1
      CALL FFV3_3(W(1,12),W(1,6),GC_7224,MDL_MW,FK_MDL_WW,W(1,100))  !  count 2
      CALL VVV5_3(W(1,99),W(1,10),GC_5911,MDL_MZ,FK_MDL_WZ,W(1,101))  !  count 2
      CALL VVV5_3(W(1,100),W(1,10),GC_5911,MDL_MZ,FK_MDL_WZ,W(1,102))  !  count 4
      CALL VVV5_3(W(1,100),W(1,11),GC_5911,MDL_MZ,FK_MDL_WZ,W(1,103))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,102),GC_6186,GC_5909,AMP(4,22))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/101,102,103/),
     & TMP, W, AMP(1,22))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/101,102,103/),
     & TMP, W, AMP(1,22))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,102),GC_6186,GC_5909,AMP(5,22))  !  count 1
      CALL FFV3PW1_3(W(1,12),W(1,5),GC_6162,MDL_MW1,FK_MDL_WW1,W(1,104))
     $  !  count 1
      CALL FFV3PW1_3(W(1,12),W(1,6),GC_6162,MDL_MW1,FK_MDL_WW1,W(1,105))
     $  !  count 2
      CALL VVV5_3(W(1,104),W(1,10),GC_6174,MDL_MZ,FK_MDL_WZ,W(1,106))  !  count 2
      CALL VVV5_3(W(1,105),W(1,10),GC_6174,MDL_MZ,FK_MDL_WZ,W(1,107))  !  count 4
      CALL VVV5_3(W(1,105),W(1,11),GC_6174,MDL_MZ,FK_MDL_WZ,W(1,108))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,107),GC_6186,GC_5909,AMP(4,23))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/106,107,108/),
     & TMP, W, AMP(1,23))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/106,107,108/),
     & TMP, W, AMP(1,23))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,107),GC_6186,GC_5909,AMP(5,23))  !  count 1
      CALL FFV4_2(W(1,12),W(1,10),GC_6447,MDL_ME,FK_ZERO,W(1,109))  !  count 2
      CALL FFV4_2(W(1,12),W(1,11),GC_6447,MDL_ME,FK_ZERO,W(1,110))  !  count 1
      CALL FFV1_3_3(W(1,109),W(1,5),GC_6187,GC_5910,MDL_MZ,FK_MDL_WZ,W(1
     $,111))  !  count 2
      CALL FFV1_3_3(W(1,109),W(1,6),GC_6187,GC_5910,MDL_MZ,FK_MDL_WZ,W(1
     $,112))  !  count 4
      CALL FFV1_3_3(W(1,110),W(1,6),GC_6187,GC_5910,MDL_MZ,FK_MDL_WZ,W(1
     $,113))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,112),GC_6186,GC_5909,AMP(4,24))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/111,112,113/),
     & TMP, W, AMP(1,24))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/111,112,113/),
     & TMP, W, AMP(1,24))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,112),GC_6186,GC_5909,AMP(5,24))  !  count 1
      CALL FFV3_2(W(1,12),W(1,10),GC_5899,MDL_ME,FK_ZERO,W(1,114))  !  count 28
      CALL FFV3_2(W(1,12),W(1,11),GC_5899,MDL_ME,FK_ZERO,W(1,115))  !  count 14
      CALL FFV1_3_3(W(1,114),W(1,5),GC_6187,GC_5910,MDL_MZ,FK_MDL_WZ,W(1
     $,116))  !  count 2
      CALL FFV1_3_3(W(1,114),W(1,6),GC_6187,GC_5910,MDL_MZ,FK_MDL_WZ,W(1
     $,117))  !  count 4
      CALL FFV1_3_3(W(1,115),W(1,6),GC_6187,GC_5910,MDL_MZ,FK_MDL_WZ,W(1
     $,118))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,117),GC_6186,GC_5909,AMP(4,25))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/116,117,118/),
     & TMP, W, AMP(1,25))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/116,117,118/),
     & TMP, W, AMP(1,25))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,117),GC_6186,GC_5909,AMP(5,25))  !  count 1
      CALL FFV7_3(W(1,114),W(1,5),GC_7237,MDL_MZ,FK_MDL_WZ,W(1,119))  !  count 2
      CALL FFV7_3(W(1,114),W(1,6),GC_7237,MDL_MZ,FK_MDL_WZ,W(1,120))  !  count 4
      CALL FFV7_3(W(1,115),W(1,6),GC_7237,MDL_MZ,FK_MDL_WZ,W(1,121))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,120),GC_6186,GC_5909,AMP(4,26))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/119,120,121/),
     & TMP, W, AMP(1,26))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/119,120,121/),
     & TMP, W, AMP(1,26))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,120),GC_6186,GC_5909,AMP(5,26))  !  count 1
      CALL FFV6_3(W(1,114),W(1,5),GC_7256,MDL_MZ,FK_MDL_WZ,W(1,122))  !  count 2
      CALL FFV6_3(W(1,114),W(1,6),GC_7256,MDL_MZ,FK_MDL_WZ,W(1,123))  !  count 4
      CALL FFV6_3(W(1,115),W(1,6),GC_7256,MDL_MZ,FK_MDL_WZ,W(1,124))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,123),GC_6186,GC_5909,AMP(4,27))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/122,123,124/),
     & TMP, W, AMP(1,27))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/122,123,124/),
     & TMP, W, AMP(1,27))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,123),GC_6186,GC_5909,AMP(5,27))  !  count 1
      CALL FFV10_3(W(1,114),W(1,5),GC_6527,MDL_MZ,FK_MDL_WZ,W(1,125))  !  count 2
      CALL FFV10_3(W(1,114),W(1,6),GC_6527,MDL_MZ,FK_MDL_WZ,W(1,126))  !  count 4
      CALL FFV10_3(W(1,115),W(1,6),GC_6527,MDL_MZ,FK_MDL_WZ,W(1,127))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,126),GC_6186,GC_5909,AMP(4,28))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/125,126,127/),
     & TMP, W, AMP(1,28))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/125,126,127/),
     & TMP, W, AMP(1,28))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,126),GC_6186,GC_5909,AMP(5,28))  !  count 1
      CALL FFV2_3(W(1,114),W(1,5),GC_6512,MDL_MZ,FK_MDL_WZ,W(1,128))  !  count 2
      CALL FFV2_3(W(1,114),W(1,6),GC_6512,MDL_MZ,FK_MDL_WZ,W(1,129))  !  count 4
      CALL FFV2_3(W(1,115),W(1,6),GC_6512,MDL_MZ,FK_MDL_WZ,W(1,130))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,129),GC_6186,GC_5909,AMP(4,29))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/128,129,130/),
     & TMP, W, AMP(1,29))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/128,129,130/),
     & TMP, W, AMP(1,29))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,129),GC_6186,GC_5909,AMP(5,29))  !  count 1
      CALL FFV1_3(W(1,114),W(1,5),GC_7162,MDL_MZ,FK_MDL_WZ,W(1,131))  !  count 2
      CALL FFV1_3(W(1,114),W(1,6),GC_7162,MDL_MZ,FK_MDL_WZ,W(1,132))  !  count 4
      CALL FFV1_3(W(1,115),W(1,6),GC_7162,MDL_MZ,FK_MDL_WZ,W(1,133))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,132),GC_6186,GC_5909,AMP(4,30))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/131,132,133/),
     & TMP, W, AMP(1,30))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/131,132,133/),
     & TMP, W, AMP(1,30))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,132),GC_6186,GC_5909,AMP(5,30))  !  count 1
      CALL FFV3_3(W(1,114),W(1,5),GC_7268,MDL_MZ,FK_MDL_WZ,W(1,134))  !  count 2
      CALL FFV3_3(W(1,114),W(1,6),GC_7268,MDL_MZ,FK_MDL_WZ,W(1,135))  !  count 4
      CALL FFV3_3(W(1,115),W(1,6),GC_7268,MDL_MZ,FK_MDL_WZ,W(1,136))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,135),GC_6186,GC_5909,AMP(4,31))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/134,135,136/),
     & TMP, W, AMP(1,31))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/134,135,136/),
     & TMP, W, AMP(1,31))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,135),GC_6186,GC_5909,AMP(5,31))  !  count 1
      CALL FFV10_3(W(1,114),W(1,5),GC_7004,MDL_MZ,FK_MDL_WZ,W(1,137))  !  count 2
      CALL FFV10_3(W(1,114),W(1,6),GC_7004,MDL_MZ,FK_MDL_WZ,W(1,138))  !  count 4
      CALL FFV10_3(W(1,115),W(1,6),GC_7004,MDL_MZ,FK_MDL_WZ,W(1,139))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,138),GC_6186,GC_5909,AMP(4,32))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/137,138,139/),
     & TMP, W, AMP(1,32))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/137,138,139/),
     & TMP, W, AMP(1,32))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,138),GC_6186,GC_5909,AMP(5,32))  !  count 1
      CALL FFV2_3(W(1,114),W(1,5),GC_6989,MDL_MZ,FK_MDL_WZ,W(1,140))  !  count 2
      CALL FFV2_3(W(1,114),W(1,6),GC_6989,MDL_MZ,FK_MDL_WZ,W(1,141))  !  count 4
      CALL FFV2_3(W(1,115),W(1,6),GC_6989,MDL_MZ,FK_MDL_WZ,W(1,142))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,141),GC_6186,GC_5909,AMP(4,33))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/140,141,142/),
     & TMP, W, AMP(1,33))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/140,141,142/),
     & TMP, W, AMP(1,33))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,141),GC_6186,GC_5909,AMP(5,33))  !  count 1
      CALL FFV1_3(W(1,114),W(1,5),GC_7336,MDL_MZ,FK_MDL_WZ,W(1,143))  !  count 2
      CALL FFV1_3(W(1,114),W(1,6),GC_7336,MDL_MZ,FK_MDL_WZ,W(1,144))  !  count 4
      CALL FFV1_3(W(1,115),W(1,6),GC_7336,MDL_MZ,FK_MDL_WZ,W(1,145))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,144),GC_6186,GC_5909,AMP(4,34))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/143,144,145/),
     & TMP, W, AMP(1,34))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/143,144,145/),
     & TMP, W, AMP(1,34))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,144),GC_6186,GC_5909,AMP(5,34))  !  count 1
      CALL FFV3_3(W(1,114),W(1,5),GC_7675,MDL_MZ,FK_MDL_WZ,W(1,146))  !  count 2
      CALL FFV3_3(W(1,114),W(1,6),GC_7675,MDL_MZ,FK_MDL_WZ,W(1,147))  !  count 4
      CALL FFV3_3(W(1,115),W(1,6),GC_7675,MDL_MZ,FK_MDL_WZ,W(1,148))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,147),GC_6186,GC_5909,AMP(4,35))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/146,147,148/),
     & TMP, W, AMP(1,35))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/146,147,148/),
     & TMP, W, AMP(1,35))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,147),GC_6186,GC_5909,AMP(5,35))  !  count 1
      CALL FFV1_3(W(1,114),W(1,5),GC_7695,MDL_MZ,FK_MDL_WZ,W(1,149))  !  count 2
      CALL FFV1_3(W(1,114),W(1,6),GC_7695,MDL_MZ,FK_MDL_WZ,W(1,150))  !  count 4
      CALL FFV1_3(W(1,115),W(1,6),GC_7695,MDL_MZ,FK_MDL_WZ,W(1,151))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,150),GC_6186,GC_5909,AMP(4,36))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/149,150,151/),
     & TMP, W, AMP(1,36))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/149,150,151/),
     & TMP, W, AMP(1,36))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,150),GC_6186,GC_5909,AMP(5,36))  !  count 1
      CALL FFV3_3(W(1,114),W(1,5),GC_7323,MDL_MZ,FK_MDL_WZ,W(1,152))  !  count 2
      CALL FFV3_3(W(1,114),W(1,6),GC_7323,MDL_MZ,FK_MDL_WZ,W(1,153))  !  count 4
      CALL FFV3_3(W(1,115),W(1,6),GC_7323,MDL_MZ,FK_MDL_WZ,W(1,154))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,153),GC_6186,GC_5909,AMP(4,37))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/152,153,154/),
     & TMP, W, AMP(1,37))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/152,153,154/),
     & TMP, W, AMP(1,37))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,153),GC_6186,GC_5909,AMP(5,37))  !  count 1
      CALL FFV1_3(W(1,114),W(1,5),GC_7339,MDL_MZ,FK_MDL_WZ,W(1,155))  !  count 2
      CALL FFV1_3(W(1,114),W(1,6),GC_7339,MDL_MZ,FK_MDL_WZ,W(1,156))  !  count 4
      CALL FFV1_3(W(1,115),W(1,6),GC_7339,MDL_MZ,FK_MDL_WZ,W(1,157))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,156),GC_6186,GC_5909,AMP(4,38))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/155,156,157/),
     & TMP, W, AMP(1,38))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/155,156,157/),
     & TMP, W, AMP(1,38))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,156),GC_6186,GC_5909,AMP(5,38))  !  count 1
      CALL FFV4_2(W(1,12),W(1,10),GC_6464,MDL_ME,FK_ZERO,W(1,158))  !  count 2
      CALL FFV4_2(W(1,12),W(1,11),GC_6464,MDL_ME,FK_ZERO,W(1,159))  !  count 1
      CALL FFV1_3_3(W(1,158),W(1,5),GC_6187,GC_5910,MDL_MZ,FK_MDL_WZ,W(1
     $,160))  !  count 2
      CALL FFV1_3_3(W(1,158),W(1,6),GC_6187,GC_5910,MDL_MZ,FK_MDL_WZ,W(1
     $,161))  !  count 4
      CALL FFV1_3_3(W(1,159),W(1,6),GC_6187,GC_5910,MDL_MZ,FK_MDL_WZ,W(1
     $,162))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,161),GC_6186,GC_5909,AMP(4,39))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/160,161,162/),
     & TMP, W, AMP(1,39))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/160,161,162/),
     & TMP, W, AMP(1,39))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,161),GC_6186,GC_5909,AMP(5,39))  !  count 1
      CALL FFV3_2(W(1,12),W(1,10),GC_7640,MDL_ME,FK_ZERO,W(1,163))  !  count 2
      CALL FFV3_2(W(1,12),W(1,11),GC_7640,MDL_ME,FK_ZERO,W(1,164))  !  count 1
      CALL FFV1_3_3(W(1,163),W(1,5),GC_6187,GC_5910,MDL_MZ,FK_MDL_WZ,W(1
     $,165))  !  count 2
      CALL FFV1_3_3(W(1,163),W(1,6),GC_6187,GC_5910,MDL_MZ,FK_MDL_WZ,W(1
     $,166))  !  count 4
      CALL FFV1_3_3(W(1,164),W(1,6),GC_6187,GC_5910,MDL_MZ,FK_MDL_WZ,W(1
     $,167))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,166),GC_6186,GC_5909,AMP(4,40))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/165,166,167/),
     & TMP, W, AMP(1,40))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/165,166,167/),
     & TMP, W, AMP(1,40))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,166),GC_6186,GC_5909,AMP(5,40))  !  count 1
      CALL FFV3_2(W(1,12),W(1,10),GC_7224,MDL_ME,FK_ZERO,W(1,168))  !  count 2
      CALL FFV3_2(W(1,12),W(1,11),GC_7224,MDL_ME,FK_ZERO,W(1,169))  !  count 1
      CALL FFV1_3_3(W(1,168),W(1,5),GC_6187,GC_5910,MDL_MZ,FK_MDL_WZ,W(1
     $,170))  !  count 2
      CALL FFV1_3_3(W(1,168),W(1,6),GC_6187,GC_5910,MDL_MZ,FK_MDL_WZ,W(1
     $,171))  !  count 4
      CALL FFV1_3_3(W(1,169),W(1,6),GC_6187,GC_5910,MDL_MZ,FK_MDL_WZ,W(1
     $,172))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,171),GC_6186,GC_5909,AMP(4,41))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/170,171,172/),
     & TMP, W, AMP(1,41))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/170,171,172/),
     & TMP, W, AMP(1,41))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,171),GC_6186,GC_5909,AMP(5,41))  !  count 1
      CALL FFVV2_4(W(1,12),W(1,5),W(1,10),GC_6932,MDL_MZ,FK_MDL_WZ,W(1,1
     $73))  !  count 2
      CALL FFVV2_4(W(1,12),W(1,6),W(1,10),GC_6932,MDL_MZ,FK_MDL_WZ,W(1,1
     $74))  !  count 4
      CALL FFVV2_4(W(1,12),W(1,6),W(1,11),GC_6932,MDL_MZ,FK_MDL_WZ,W(1,1
     $75))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,174),GC_6186,GC_5909,AMP(4,42))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/173,174,175/),
     & TMP, W, AMP(1,42))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/173,174,175/),
     & TMP, W, AMP(1,42))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,174),GC_6186,GC_5909,AMP(5,42))  !  count 1
      CALL FFVV2_4(W(1,12),W(1,5),W(1,10),GC_6942,MDL_MZ,FK_MDL_WZ,W(1,1
     $76))  !  count 2
      CALL FFVV2_4(W(1,12),W(1,6),W(1,10),GC_6942,MDL_MZ,FK_MDL_WZ,W(1,1
     $77))  !  count 4
      CALL FFVV2_4(W(1,12),W(1,6),W(1,11),GC_6942,MDL_MZ,FK_MDL_WZ,W(1,1
     $78))  !  count 2
      CALL FFV1_3_0(W(1,1),W(1,3),W(1,177),GC_6186,GC_5909,AMP(4,43))
      CALL FFV1_3P1N_3(W(1,1), W(1,4), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/3,1,2/), 
     & (/176,177,178/),
     & TMP, W, AMP(1,43))
      CALL FFV1_3P1N_3(W(1,2), W(1,3), GC_6186, GC_5909, TMP(1))
      call CombineAmp(3,
     & (/8,6,7/), 
     & (/176,177,178/),
     & TMP, W, AMP(1,43))
      CALL FFV1_3_0(W(1,2),W(1,4),W(1,177),GC_6186,GC_5909,AMP(5,43))  !  count 1

      JAMP(:,:)  = (0d0,0d0)
      DO K = 1, NCOMB
        
        JAMP(:,:) = (0D0,0D0)
C       JAMPs contributing to orders ALL_ORDERS=1
        JAMP(1,1) = (-1.000000000000000D+00)*AMP( K,1)+(-1.0000000000000
     $  00D +00)*AMP( K,2)+(-1.000000000000000D+00)*AMP( K,3)+( -1.0000000000000
     $  00D+00)*AMP( K,4)+(-1.000000000000000D+00)*AMP( K,5) +(-1.00000000000000
     $  0D+00)*AMP( K,6)+(-1.000000000000000D+00)*AMP( K,7) +(-1.000000000000000
     $  D+00)*AMP( K,8)+(-1.000000000000000D+00)*AMP( K,9) +(-1.000000000000000D
     $  +00)*AMP( K,10)+(-1.000000000000000D+00) *AMP( K,11)+(-1.000000000000000
     $  D+00)*AMP( K,12)+(-1.000000000000000D +00)*AMP( K,13)+(-1.00000000000000
     $  0D+00)*AMP( K,14)+( -1.000000000000000D+00)*AMP( K,15)+(-1.0000000000000
     $  00D+00)*AMP( K,16) +(-1.000000000000000D+00)*AMP( K,17)+(-1.000000000000
     $  000D+00) *AMP( K,18)+(-1.000000000000000D+00)*AMP( K,19)+(-1.00000000000
     $  0000D +00)*AMP( K,20)+(-1.000000000000000D+00)*AMP( K,21)+( -1.000000000
     $  000000D+00)*AMP( K,22)+(-1.000000000000000D+00)*AMP( K,23) +(-1.00000000
     $  0000000D+00)*AMP( K,24)+(-1.000000000000000D+00) *AMP( K,25)+(-1.0000000
     $  00000000D+00)*AMP( K,26)+(-1.000000000000000D +00)*AMP( K,27)+(-1.000000
     $  000000000D+00)*AMP( K,28)+( -1.000000000000000D+00)*AMP( K,29)+(-1.00000
     $  0000000000D+00)*AMP( K,30) +(-1.000000000000000D+00)*AMP( K,31)+(-1.0000
     $  00000000000D+00) *AMP( K,32)+(-1.000000000000000D+00)*AMP( K,33)+(-1.000
     $  000000000000D +00)*AMP( K,34)+(-1.000000000000000D+00)*AMP( K,35)+( -1.0
     $  00000000000000D+00)*AMP( K,36)+(-1.000000000000000D+00)*AMP( K,37) +(-1.
     $  000000000000000D+00)*AMP( K,38)+(-1.000000000000000D+00) *AMP( K,39)+(-1
     $  .000000000000000D+00)*AMP( K,40)+(-1.000000000000000D +00)*AMP( K,41)+(-
     $  1.000000000000000D+00)*AMP( K,42)+( -1.000000000000000D+00)*AMP( K,43)

        TS(K) = 0.D0 
        DO M = 1, NAMPSO
          CF_INDEX = 0
          DO I = 1, NCOLOR
            ZTEMP = (0.D0,0.D0)
            DO J = I, NCOLOR
              CF_INDEX = CF_INDEX + 1
              ZTEMP = ZTEMP + CF(CF_INDEX)*JAMP(J,M)
            ENDDO    !  J
            DO N = 1, NAMPSO

              TS(K) = TS(K) + REAL(ZTEMP*DCONJG(JAMP(I,N)))

            ENDDO    !  N
          ENDDO    !  I
        ENDDO    !  M
        TS(K) = TS(K) / DENOM
        if(sde_strat.eq.1) then
        
        IF(SDE_STRAT.EQ.1)THEN
          AMP2(1)=AMP2(1)+(AMP( K,1)+AMP( K,2)+AMP( K,3)+AMP( K,4)+AMP( 
     $    K,5)+AMP( K,6)   +AMP( K,7)+AMP( K,8)+AMP( K,9))*DCONJG(AMP( K,1)+AMP( K
     $    ,2)+AMP( K,3)+AMP( K,4)   +AMP( K,5)+AMP( K,6)+AMP( K,7)+AMP( K,8)+AMP( 
     $    K,9))
          AMP2(10)=AMP2(10)+(AMP( K,10)+AMP( K,11)+AMP( K,12)+AMP( K,13)
     $    +AMP( K,14)   +AMP( K,15)+AMP( K,16)+AMP( K,17)+AMP( K,18)+AMP( K,19)+AM
     $    P( K,20)+AMP( K,21)   +AMP( K,22))*DCONJG(AMP( K,10)+AMP( K,11)+AMP( K,1
     $    2)+AMP( K,13)+AMP( K,14)   +AMP( K,15)+AMP( K,16)+AMP( K,17)+AMP( K,18)+
     $    AMP( K,19)+AMP( K,20)+AMP( K,21)   +AMP( K,22))
          AMP2(23)=AMP2(23)+AMP( K,23)*DCONJG(AMP( K,23))
          AMP2(24)=AMP2(24)+(AMP( K,24)+AMP( K,25)+AMP( K,26)+AMP( K,27)
     $    +AMP( K,28)   +AMP( K,29)+AMP( K,30)+AMP( K,31)+AMP( K,32)+AMP( K,33)+AM
     $    P( K,34)+AMP( K,35)   +AMP( K,36)+AMP( K,37)+AMP( K,38)+AMP( K,39)+AMP( 
     $    K,40)+AMP( K,41))   *DCONJG(AMP( K,24)+AMP( K,25)+AMP( K,26)+AMP( K,27)+
     $    AMP( K,28)+AMP( K,29)   +AMP( K,30)+AMP( K,31)+AMP( K,32)+AMP( K,33)+AMP
     $    ( K,34)+AMP( K,35)+AMP( K,36)   +AMP( K,37)+AMP( K,38)+AMP( K,39)+AMP( K
     $    ,40)+AMP( K,41))
        ENDIF

        endif
        Do I = 1, NCOLOR
          DO M = 1, NAMPSO
            DO N = 1, NAMPSO

              Jamp2(i)=Jamp2(i)+DABS(DBLE(Jamp(i,m)*dconjg(Jamp(i,n))))

            enddo
          enddo
        Enddo
      ENDDO    !  K

      END


      SUBROUTINE PRINT_ZERO_AMP_1()

      integer i
      i =1
      return
      end

C     Set of functions to handle the array indices of the split orders


      INTEGER FUNCTION SQSOINDEX1(ORDERINDEXA, ORDERINDEXB)
C     
C     This functions plays the role of the interference matrix. It can
C      be hardcoded or 
C     made more elegant using hashtables if its execution speed ever
C      becomes a relevant
C     factor. From two split order indices, it return the
C      corresponding index in the squared 
C     order canonical ordering.
C     
C     CONSTANTS
C     

      INTEGER    NSO, NSQUAREDSO, NAMPSO
      PARAMETER (NSO=1, NSQUAREDSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERINDEXA, ORDERINDEXB
C     
C     LOCAL VARIABLES
C     
      INTEGER I, SQORDERS(NSO)
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      DATA (AMPSPLITORDERS(  1,i),i=  1,  1) /    1/
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     FUNCTION
C     
      INTEGER SOINDEX_FOR_SQUARED_ORDERS1
C     
C     BEGIN CODE
C     
      DO I=1,NSO
        SQORDERS(I)=AMPSPLITORDERS(ORDERINDEXA,I)
     $   +AMPSPLITORDERS(ORDERINDEXB,I)
      ENDDO
      SQSOINDEX1=SOINDEX_FOR_SQUARED_ORDERS1(SQORDERS)
      END

      INTEGER FUNCTION SOINDEX_FOR_SQUARED_ORDERS1(ORDERS)
C     
C     This functions returns the integer index identifying the squared
C      split orders list passed in argument which corresponds to the
C      values of the following list of couplings (and in this order).
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO, NAMPSO
      PARAMETER (NSO=1, NSQSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER SQSPLITORDERS(NSQSO,NSO)
      DATA (SQSPLITORDERS(  1,i),i=  1,  1) /    2/
      COMMON/SQPLITORDERS1/SQPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSQSO
        DO J=1,NSO
          IF (ORDERS(J).NE.SQSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_SQUARED_ORDERS1 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping in function' 
      WRITE(*,*) 'SOINDEX_FOR_SQUARED_ORDERS1'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

      SUBROUTINE GET_NSQSO_BORN1(NSQSO)
C     
C     Simple subroutine returning the number of squared split order
C     contributions returned when calling smatrix_split_orders 
C     

      INTEGER    NSQUAREDSO
      PARAMETER  (NSQUAREDSO=1)

      INTEGER NSQSO

      NSQSO=NSQUAREDSO

      END

C     This is the inverse subroutine of SOINDEX_FOR_SQUARED_ORDERS.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_SQUARED_ORDERS_FOR_SOINDEX1(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the squared
C      split order index in argument. Order values correspond to
C      following list of couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO
      PARAMETER (NSO=1, NSQSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER SQPLITORDERS(NSQSO,NSO)
      COMMON/SQPLITORDERS1/SQPLITORDERS	  
C     
C     BEGIN CODE
C     
      IF (SOINDEX.gt.0.and.SOINDEX.le.NSQSO) THEN
        DO I=1,NSO
          ORDERS(I) =  SQPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function'
     $ //' GET_SQUARED_ORDERS_FOR_SOINDEX1'
      WRITE(*,*) 'Could not find squared orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This is the inverse subroutine of getting amplitude SO orders.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_ORDERS_FOR_AMPSOINDEX1(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the split order
C      index in argument. Order values correspond to following list of
C      couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.gt.0.and.SOINDEX.le.NAMPSO) THEN
        DO I=1,NSO
          ORDERS(I) =  AMPSPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function GET_ORDERS_FOR_AMPSOINDEX1'
      WRITE(*,*) 'Could not find amplitude split orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This function is not directly useful, but included for
C      completeness
      INTEGER FUNCTION SOINDEX_FOR_AMPORDERS1(ORDERS)
C     
C     This functions returns the integer index identifying the
C      amplitude split orders passed in argument which correspond to
C      the values of the following list of couplings (and in this
C      order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NAMPSO
        DO J=1,NSO
          IF (ORDERS(J).NE.AMPSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_AMPORDERS1 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping function SOINDEX_FOR_AMPORDERS1'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

