      SUBROUTINE SMATRIX1(P, RHEL, RCOL, CHANNEL, IVEC, ANS, IHEL,
     $  ICOL)
C     
C     Generated by MadGraph5_aMC@NLO v. 3.6.3, 2025-06-12
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO for Madevent Version
C     
C     Returns amplitude squared -- no average over initial
C      state/symmetry factor
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: c c~ > z WEIGHTED<=2 @1
C     *   Decay: z > e- w+ ve~ NP<=1 NPceW<=1
C     *     Decay: w+ > mu+ vm WEIGHTED<=2
C     
      USE DISCRETESAMPLER
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'genps.inc'
      INCLUDE 'maxconfigs.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      INCLUDE '../../Source/vector.inc'  ! defines VECSIZE_MEMMAX
      INCLUDE 'run.inc'
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=64)
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=43)
      INTEGER    NDIAGS
      PARAMETER (NDIAGS=43)
      INTEGER    THEL
      PARAMETER (THEL=2*NCOMB)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      DOUBLE PRECISION RHEL  ! random number for selecting helicity
      DOUBLE PRECISION RCOL  ! random number for selecting helicity
      INTEGER CHANNEL  ! channel to keep for the multi-channel
      INTEGER IVEC  ! for using the correct coupling
C     
C     output argument
C     
      INTEGER IHEL, ICOL
C     
C     global (due to reading writting) 
C     
      LOGICAL GOODHEL(NCOMB, MAXSPROC)
      INTEGER NTRY(MAXSPROC)
      COMMON/BLOCK_GOODHEL/NTRY,GOODHEL

C     
C     LOCAL VARIABLES 
C     
      INTEGER CONFSUB(MAXSPROC,LMAXCONFIGS)
      INCLUDE 'config_subproc_map.inc'
      INTEGER NHEL(NEXTERNAL,NCOMB)
      INTEGER ISHEL
      REAL*8 T,MATRIX1
      REAL*8 R,SUMHEL,TS(NCOMB)
      INTEGER I,IDEN
      INTEGER JC(NEXTERNAL),II
      REAL*8 HWGT, XTOT, XTRY, XREJ, XR, YFRAC(0:NCOMB)
      INTEGER NGOOD
      INTEGER J, JJ
      INTEGER NB_FAIL
      SAVE NB_FAIL
      DATA NB_FAIL /0/
      DOUBLE PRECISION GET_CHANNEL_CUT
      EXTERNAL GET_CHANNEL_CUT

C     
C     This is just to temporarily store the reference grid for
C      helicity of the DiscreteSampler so as to obtain its number of
C      entries with ref_helicity_grid%n_tot_entries
      TYPE(SAMPLEDDIMENSION) REF_HELICITY_GRID
C     
C     GLOBAL VARIABLES
C     
      LOGICAL INIT_MODE
      COMMON /TO_DETERMINE_ZERO_HEL/INIT_MODE
      DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)


      INTEGER NB_SPIN_STATE_IN(2)
      COMMON /NB_HEL_STATE/ NB_SPIN_STATE_IN

      INTEGER IMIRROR, IPROC
      COMMON/TO_MIRROR/ IMIRROR,IPROC

C     included vi run.inc    
C     double precision tmin_for_channel	
C     integer sde_strat ! 1 means standard single diagram enhancement
C      strategy,
C     2 means approximation by the	denominator of the propagator
C     common/TO_CHANNEL_STRAT/tmin_for_channel,	sde_strat

      REAL*8 POL(2)
      COMMON/TO_POLARIZATION/ POL

      INTEGER          ISUM_HEL
      LOGICAL                    MULTI_CHANNEL
      COMMON/TO_MATRIX/ISUM_HEL, MULTI_CHANNEL
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      COMMON/TO_MCONFIGS/MAPCONFIG, ICONFIG
      DATA XTRY, XREJ /0,0/
      DATA NGOOD /0/
      DATA ISHEL/0/
      SAVE YFRAC
      DATA (NHEL(I,   1),I=1,6) / 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,   2),I=1,6) / 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,   3),I=1,6) / 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,   4),I=1,6) / 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,   5),I=1,6) / 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,   6),I=1,6) / 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,   7),I=1,6) / 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,   8),I=1,6) / 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,   9),I=1,6) / 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  10),I=1,6) / 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  11),I=1,6) / 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  12),I=1,6) / 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  13),I=1,6) / 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  14),I=1,6) / 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  15),I=1,6) / 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  16),I=1,6) / 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  17),I=1,6) / 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  18),I=1,6) / 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  19),I=1,6) / 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  20),I=1,6) / 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  21),I=1,6) / 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  22),I=1,6) / 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  23),I=1,6) / 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  24),I=1,6) / 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  25),I=1,6) / 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  26),I=1,6) / 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  27),I=1,6) / 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  28),I=1,6) / 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  29),I=1,6) / 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  30),I=1,6) / 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  31),I=1,6) / 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  32),I=1,6) / 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  33),I=1,6) /-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  34),I=1,6) /-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  35),I=1,6) /-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  36),I=1,6) /-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  37),I=1,6) /-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  38),I=1,6) /-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  39),I=1,6) /-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  40),I=1,6) /-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  41),I=1,6) /-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  42),I=1,6) /-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  43),I=1,6) /-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  44),I=1,6) /-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  45),I=1,6) /-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  46),I=1,6) /-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  47),I=1,6) /-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  48),I=1,6) /-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  49),I=1,6) /-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  50),I=1,6) /-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  51),I=1,6) /-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  52),I=1,6) /-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  53),I=1,6) /-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  54),I=1,6) /-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  55),I=1,6) /-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  56),I=1,6) /-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  57),I=1,6) /-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  58),I=1,6) /-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  59),I=1,6) /-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  60),I=1,6) /-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  61),I=1,6) /-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  62),I=1,6) /-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  63),I=1,6) /-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  64),I=1,6) /-1, 1, 1,-1, 1,-1/
      DATA IDEN/36/

C     To be able to control when the matrix<i> subroutine can add
C      entries to the grid for the MC over helicity configuration
      LOGICAL ALLOW_HELICITY_GRID_ENTRIES
      COMMON/TO_ALLOW_HELICITY_GRID_ENTRIES/ALLOW_HELICITY_GRID_ENTRIES

C     ----------
C     BEGIN CODE
C     ----------

      NTRY(1)=NTRY(1)+1
      DO I=1,NEXTERNAL
        JC(I) = +1
      ENDDO

      IF (MULTI_CHANNEL) THEN
        DO I=1,NDIAGS
          AMP2(I)=0D0
        ENDDO
      ENDIF
      JAMP2(0)=1
      DO I=1,INT(JAMP2(0))
        JAMP2(I)=0D0
      ENDDO
      ANS = 0D0
      DO I=1,NCOMB
        TS(I)=0D0
      ENDDO

C     If the helicity grid status is 0, this means that it is not yet
C      initialized.
C     If HEL_PICKED==-1, this means that calls to other matrix<i>
C      where in initialization mode as well for the helicity.
      IF ((ISHEL.EQ.0.AND.ISUM_HEL.EQ.0)
     $ .OR.(DS_GET_DIM_STATUS('Helicity').EQ.0).OR.(HEL_PICKED.EQ.-1))
     $  THEN
        DO I=1,NCOMB
          IF (GOODHEL(I,1) .OR. NTRY(1).LE.MAXTRIES.OR.(ISUM_HEL.NE.0))
     $      THEN
            T=MATRIX1(P ,NHEL(1,I),JC(1),I,AMP2, JAMP2, IVEC)

            DO JJ=1,NINCOMING
              IF(POL(JJ).NE.1D0.AND.NHEL(JJ,I).EQ.INT(SIGN(1D0,POL(JJ))
     $         )) THEN
                T=T*ABS(POL(JJ))
              ELSE IF(POL(JJ).NE.1D0)THEN
                T=T*(2D0-ABS(POL(JJ)))
              ENDIF
            ENDDO

            IF (ISUM_HEL.NE.0.AND.DS_GET_DIM_STATUS('Helicity')
     $       .EQ.0.AND.ALLOW_HELICITY_GRID_ENTRIES) THEN
              CALL DS_ADD_ENTRY('Helicity',I,T)
            ENDIF
            ANS=ANS+DABS(T)
            TS(I)=T
          ENDIF
        ENDDO
        IF(NTRY(1).EQ.(MAXTRIES+1).AND.DS_GET_DIM_STATUS('Helicity')
     $   .NE.-1) THEN
          CALL RESET_CUMULATIVE_VARIABLE()  ! avoid biais of the initialization
        ENDIF
        IF (ISUM_HEL.NE.0) THEN
C         We set HEL_PICKED to -1 here so that later on, the call to
C          DS_add_point in dsample.f does not add anything to the grid
C          since it was already done here.
          HEL_PICKED = -1
C         For safety, hardset the helicity sampling jacobian to 0.0d0
C          to make sure it is not .
          HEL_JACOBIAN   = 1.0D0
C         We don't want to re-update the helicity grid if it was
C          already updated by another matrix<i>, so we make sure that
C          the reference grid is empty.
          REF_HELICITY_GRID = DS_GET_DIMENSION(REF_GRID,'Helicity')
          IF((DS_GET_DIM_STATUS('Helicity').EQ.1)
     $     .AND.(REF_HELICITY_GRID%N_TOT_ENTRIES.EQ.0)) THEN
C           If we finished the initialization we can update the grid
C            so as to start sampling over it.
C           However the grid will now be filled by dsample with
C            different kind of weights (including pdf, flux, etc...)
C            so by setting the grid_mode of the reference grid to
C            'initialization' we make sure it will be overwritten (as
C            opposed to 'combined') by the running grid at the next
C            update.
            CALL DS_UPDATE_GRID('Helicity')
            CALL DS_SET_GRID_MODE('Helicity','init')
          ENDIF
        ELSE
          IF(NTRY(1).LE.MAXTRIES)THEN
            DO I=1,NCOMB
              IF(INIT_MODE) THEN
                IF (DABS(TS(I)).GT.ANS*LIMHEL/NCOMB) THEN
                  PRINT *, 'Matrix Element/Good Helicity: 1 ', I,
     $              'IMIRROR', IMIRROR
                ENDIF
              ELSE IF (.NOT.GOODHEL(I,1) .AND. (DABS(TS(I)).GT.ANS
     $         *LIMHEL/NCOMB)) THEN
                GOODHEL(I,1)=.TRUE.
                NGOOD = NGOOD +1
                PRINT *,'Added good helicity ',I, 'for process 1',TS(I)
     $           *NCOMB/ANS,' in event ',NTRY(1)
              ENDIF
            ENDDO
          ENDIF
          IF(NTRY(1).EQ.MAXTRIES)THEN
            ISHEL=MIN(ISUM_HEL,NGOOD)
          ENDIF
        ENDIF
      ELSE IF (.NOT.INIT_MODE) THEN  ! random helicity 
C       The helicity configuration was chosen already by genps and put
C        in a common block defined in genps.inc.
        I = HEL_PICKED

        T=MATRIX1(P ,NHEL(1,I),JC(1),I,AMP2, JAMP2, IVEC)


        DO JJ=1,NINCOMING
          IF(POL(JJ).NE.1D0.AND.NHEL(JJ,I).EQ.INT(SIGN(1D0,POL(JJ))))
     $      THEN
            T=T*ABS(POL(JJ))
          ELSE IF(POL(JJ).NE.1D0)THEN
            T=T*(2D0-ABS(POL(JJ)))
          ENDIF
        ENDDO

C       Always one helicity at a time
        ANS = T
C       Include the Jacobian from helicity sampling
        ANS = ANS * HEL_JACOBIAN
        IHEL = HEL_PICKED
      ELSE
        ANS = 1D0
        RETURN
      ENDIF
      IF (ANS.NE.0D0.AND.(ISUM_HEL .NE. 1.OR.HEL_PICKED.EQ.-1)) THEN
C       CALL RANMAR(R) ! rhel passed as input
        SUMHEL=0D0
        DO I=1,NCOMB
          SUMHEL=SUMHEL+DABS(TS(I))/ANS
          IF(RHEL.LT.SUMHEL)THEN
            IHEL = I
C           Set right sign for ANS, based on sign of chosen helicity
            ANS=DSIGN(ANS,TS(I))
            GOTO 10
          ENDIF
        ENDDO
 10     CONTINUE
      ENDIF
      IF (MULTI_CHANNEL) THEN
        XTOT=0D0
        DO I=1,LMAXCONFIGS
          J = CONFSUB(1, I)
          IF (J.NE.0) THEN
            IF(SDE_STRAT.EQ.1) THEN
              AMP2(J) = AMP2(J) * GET_CHANNEL_CUT(P, I)
              XTOT=XTOT+AMP2(J)
            ELSE
              AMP2(J) = GET_CHANNEL_CUT(P, I)
              XTOT=XTOT+AMP2(J)
            ENDIF
          ENDIF
        ENDDO
        IF (XTOT.NE.0D0) THEN
          ANS=ANS*AMP2(CHANNEL)/XTOT
        ELSE IF(ANS.NE.0D0) THEN
          IF(NB_FAIL.GE.10)THEN
            WRITE(*,*) 'Problem in the multi-channeling. All amp2 are'
     $       //' zero but not the total matrix-element'

            STOP 1
          ELSE
            NB_FAIL = NB_FAIL +1
          ENDIF
        ENDIF
      ENDIF
      ANS=ANS/DBLE(IDEN)

      CALL SELECT_COLOR(RCOL, JAMP2, ICONFIG,1,  ICOL)

      END


      REAL*8 FUNCTION MATRIX1(P,NHEL,IC, IHEL,AMP2, JAMP2, IVEC)
C     
C     Generated by MadGraph5_aMC@NLO v. 3.6.3, 2025-06-12
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: c c~ > z WEIGHTED<=2 @1
C     *   Decay: z > e- w+ ve~ NP<=1 NPceW<=1
C     *     Decay: w+ > mu+ vm WEIGHTED<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=43)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=64)
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      INTEGER    NWAVEFUNCS,     NCOLOR
      PARAMETER (NWAVEFUNCS=7, NCOLOR=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      LOGICAL CHOSEN_SO_CONFIGS(NSQAMPSO)
      DATA CHOSEN_SO_CONFIGS/.TRUE./
      SAVE CHOSEN_SO_CONFIGS
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
      INTEGER IHEL
      INTEGER IVEC
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,M,N
      COMPLEX*16 ZTEMP, TMP_JAMP(0)
      INTEGER CF(NCOLOR*(NCOLOR+1)/2)
      INTEGER DENOM, CF_INDEX
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR,NAMPSO)
      COMPLEX*16 W(6,NWAVEFUNCS)
C     Needed for v4 models
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/

      DOUBLE PRECISION FK_MDL_WW1
      DOUBLE PRECISION FK_MDL_WZ
      DOUBLE PRECISION FK_MDL_WW
      DOUBLE PRECISION FK_ZERO
      SAVE FK_MDL_WW1
      SAVE FK_MDL_WZ
      SAVE FK_MDL_WW
      SAVE FK_ZERO

      LOGICAL FIRST
      DATA FIRST /.TRUE./
      SAVE FIRST
C     
C     FUNCTION
C     
      INTEGER SQSOINDEX1
C     
C     GLOBAL VARIABLES
C     
      INCLUDE '../../Source/vector.inc'  ! defines VECSIZE_MEMMAX
      DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)
      INCLUDE 'coupl.inc'  ! needs VECSIZE_MEMMAX (defined in vector.inc)

      DOUBLE PRECISION SMALL_WIDTH_TREATMENT
      COMMON/NARROW_WIDTH/SMALL_WIDTH_TREATMENT

      LOGICAL INIT_MODE
      COMMON/TO_DETERMINE_ZERO_HEL/INIT_MODE

      LOGICAL ZEROAMP_1(NCOMB,NGRAPHS)
      COMMON/TO_ZEROAMP_1/ZEROAMP_1

      DOUBLE PRECISION TMIN_FOR_CHANNEL
      INTEGER SDE_STRAT  ! 1 means standard single diagram enhancement strategy,
C     2 means approximation by the	denominator of the propagator
      COMMON/TO_CHANNEL_STRAT/TMIN_FOR_CHANNEL,	SDE_STRAT

C     
C     COLOR DATA
C     
      DATA DENOM/1/
      DATA (CF(I),I=  1,  1) /3/
C     1 T(2,1)
C     ----------
C     BEGIN CODE
C     ----------
      IF (FIRST) THEN
        FIRST=.FALSE.
        FK_ZERO = 0D0
        IF(MDL_WW.NE.0D0) THEN
          FK_MDL_WW = SIGN(MAX(ABS(MDL_WW), ABS(MDL_MW
     $     *SMALL_WIDTH_TREATMENT)), MDL_WW)
        ELSE
          FK_MDL_WW = 0D0
        ENDIF

        IF(MDL_WW1.NE.0D0) THEN
          FK_MDL_WW1 = SIGN(MAX(ABS(MDL_WW1), ABS(MDL_MW1
     $     *SMALL_WIDTH_TREATMENT)), MDL_WW1)
        ELSE
          FK_MDL_WW1 = 0D0
        ENDIF

        IF(MDL_WZ.NE.0D0) THEN
          FK_MDL_WZ = SIGN(MAX(ABS(MDL_WZ), ABS(MDL_MZ
     $     *SMALL_WIDTH_TREATMENT)), MDL_WZ)
        ELSE
          FK_MDL_WZ = 0D0
        ENDIF


        IF(INIT_MODE) THEN
          ZEROAMP_1(:,:) = .TRUE.
        ENDIF
      ENDIF


      CALL IXXXXX(P(0,1),MDL_MC,NHEL(1),+1*IC(1),W(1,1))
      CALL OXXXXX(P(0,2),MDL_MC,NHEL(2),-1*IC(2),W(1,2))
      CALL OXXXXX(P(0,3),MDL_ME,NHEL(3),+1*IC(3),W(1,3))
      CALL IXXXXX(P(0,4),MDL_MMU,NHEL(4),-1*IC(4),W(1,4))
      CALL OXXXXX(P(0,5),ZERO,NHEL(5),+1*IC(5),W(1,5))
      CALL FFV3_3(W(1,4),W(1,5),GC_5899,MDL_MW, FK_MDL_WW,W(1,6))
      CALL IXXXXX(P(0,6),ZERO,NHEL(6),-1*IC(6),W(1,5))
      CALL FFV4_1(W(1,3),W(1,6),GC_6447,ZERO, FK_ZERO,W(1,4))
      CALL FFV3_3(W(1,5),W(1,4),GC_5909,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 1
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(1))
      CALL FFV3_1(W(1,3),W(1,6),GC_5899,ZERO, FK_ZERO,W(1,7))
      CALL FFV3_3(W(1,5),W(1,7),GC_5909,MDL_MZ, FK_MDL_WZ,W(1,4))
C     Amplitude(s) for diagram number 2
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,4),GC_6186,GC_5909,AMP(2))
      CALL FFV3_3(W(1,5),W(1,7),GC_7235,MDL_MZ, FK_MDL_WZ,W(1,4))
C     Amplitude(s) for diagram number 3
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,4),GC_6186,GC_5909,AMP(3))
      CALL FFV3_3(W(1,5),W(1,7),GC_7268,MDL_MZ, FK_MDL_WZ,W(1,4))
C     Amplitude(s) for diagram number 4
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,4),GC_6186,GC_5909,AMP(4))
      CALL FFV3_3(W(1,5),W(1,7),GC_7676,MDL_MZ, FK_MDL_WZ,W(1,4))
C     Amplitude(s) for diagram number 5
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,4),GC_6186,GC_5909,AMP(5))
      CALL FFV3_3(W(1,5),W(1,7),GC_7322,MDL_MZ, FK_MDL_WZ,W(1,4))
C     Amplitude(s) for diagram number 6
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,4),GC_6186,GC_5909,AMP(6))
      CALL FFV4_1(W(1,3),W(1,6),GC_6464,ZERO, FK_ZERO,W(1,4))
      CALL FFV3_3(W(1,5),W(1,4),GC_5909,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 7
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(7))
      CALL FFV3_1(W(1,3),W(1,6),GC_7640,ZERO, FK_ZERO,W(1,7))
      CALL FFV3_3(W(1,5),W(1,7),GC_5909,MDL_MZ, FK_MDL_WZ,W(1,4))
C     Amplitude(s) for diagram number 8
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,4),GC_6186,GC_5909,AMP(8))
      CALL FFV3_1(W(1,3),W(1,6),GC_7224,ZERO, FK_ZERO,W(1,4))
      CALL FFV3_3(W(1,5),W(1,4),GC_5909,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 9
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(9))
      CALL FFV4_3(W(1,5),W(1,3),GC_6447,MDL_MW, FK_MDL_WW,W(1,7))
      CALL VVV5_3(W(1,7),W(1,6),GC_5911,MDL_MZ, FK_MDL_WZ,W(1,4))
C     Amplitude(s) for diagram number 10
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,4),GC_6186,GC_5909,AMP(10))
      CALL FFV3_3(W(1,5),W(1,3),GC_5899,MDL_MW, FK_MDL_WW,W(1,4))
      CALL VVV3_3(W(1,4),W(1,6),GC_7329,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 11
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(11))
      CALL VVV2_3(W(1,4),W(1,6),GC_7163,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 12
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(12))
      CALL VVV9_3(W(1,4),W(1,6),GC_5679,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 13
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(13))
      CALL VVV7_3(W(1,4),W(1,6),GC_5678,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 14
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(14))
      CALL VVV5_3(W(1,4),W(1,6),GC_5911,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 15
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(15))
      CALL VVV4_3(W(1,4),W(1,6),GC_7161,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 16
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(16))
      CALL VVV5_3(W(1,4),W(1,6),GC_7324,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 17
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(17))
      CALL VVV5_3(W(1,4),W(1,6),GC_7690,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 18
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(18))
      CALL VVV5_3(W(1,4),W(1,6),GC_7330,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 19
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(19))
      CALL FFV4_3(W(1,5),W(1,3),GC_6464,MDL_MW, FK_MDL_WW,W(1,7))
      CALL VVV5_3(W(1,7),W(1,6),GC_5911,MDL_MZ, FK_MDL_WZ,W(1,4))
C     Amplitude(s) for diagram number 20
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,4),GC_6186,GC_5909,AMP(20))
      CALL FFV3_3(W(1,5),W(1,3),GC_7640,MDL_MW, FK_MDL_WW,W(1,4))
      CALL VVV5_3(W(1,4),W(1,6),GC_5911,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 21
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(21))
      CALL FFV3_3(W(1,5),W(1,3),GC_7224,MDL_MW, FK_MDL_WW,W(1,7))
      CALL VVV5_3(W(1,7),W(1,6),GC_5911,MDL_MZ, FK_MDL_WZ,W(1,4))
C     Amplitude(s) for diagram number 22
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,4),GC_6186,GC_5909,AMP(22))
      CALL FFV3PW1_3(W(1,5),W(1,3),GC_6162,MDL_MW1, FK_MDL_WW1,W(1,4))
      CALL VVV5_3(W(1,4),W(1,6),GC_6174,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 23
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(23))
      CALL FFV4_2(W(1,5),W(1,6),GC_6447,MDL_ME, FK_ZERO,W(1,7))
      CALL FFV1_3_3(W(1,7),W(1,3),GC_6187,GC_5910,MDL_MZ, FK_MDL_WZ
     $ ,W(1,4))
C     Amplitude(s) for diagram number 24
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,4),GC_6186,GC_5909,AMP(24))
      CALL FFV3_2(W(1,5),W(1,6),GC_5899,MDL_ME, FK_ZERO,W(1,4))
      CALL FFV1_3_3(W(1,4),W(1,3),GC_6187,GC_5910,MDL_MZ, FK_MDL_WZ
     $ ,W(1,7))
C     Amplitude(s) for diagram number 25
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(25))
      CALL FFV7_3(W(1,4),W(1,3),GC_7237,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 26
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(26))
      CALL FFV6_3(W(1,4),W(1,3),GC_7256,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 27
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(27))
      CALL FFV10_3(W(1,4),W(1,3),GC_6527,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 28
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(28))
      CALL FFV2_3(W(1,4),W(1,3),GC_6512,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 29
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(29))
      CALL FFV1_3(W(1,4),W(1,3),GC_7162,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 30
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(30))
      CALL FFV3_3(W(1,4),W(1,3),GC_7268,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 31
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(31))
      CALL FFV10_3(W(1,4),W(1,3),GC_7004,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 32
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(32))
      CALL FFV2_3(W(1,4),W(1,3),GC_6989,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 33
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(33))
      CALL FFV1_3(W(1,4),W(1,3),GC_7336,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 34
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(34))
      CALL FFV3_3(W(1,4),W(1,3),GC_7675,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 35
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(35))
      CALL FFV1_3(W(1,4),W(1,3),GC_7695,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 36
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(36))
      CALL FFV3_3(W(1,4),W(1,3),GC_7323,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 37
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(37))
      CALL FFV1_3(W(1,4),W(1,3),GC_7339,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 38
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(38))
      CALL FFV4_2(W(1,5),W(1,6),GC_6464,MDL_ME, FK_ZERO,W(1,7))
      CALL FFV1_3_3(W(1,7),W(1,3),GC_6187,GC_5910,MDL_MZ, FK_MDL_WZ
     $ ,W(1,4))
C     Amplitude(s) for diagram number 39
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,4),GC_6186,GC_5909,AMP(39))
      CALL FFV3_2(W(1,5),W(1,6),GC_7640,MDL_ME, FK_ZERO,W(1,4))
      CALL FFV1_3_3(W(1,4),W(1,3),GC_6187,GC_5910,MDL_MZ, FK_MDL_WZ
     $ ,W(1,7))
C     Amplitude(s) for diagram number 40
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,7),GC_6186,GC_5909,AMP(40))
      CALL FFV3_2(W(1,5),W(1,6),GC_7224,MDL_ME, FK_ZERO,W(1,7))
      CALL FFV1_3_3(W(1,7),W(1,3),GC_6187,GC_5910,MDL_MZ, FK_MDL_WZ
     $ ,W(1,4))
C     Amplitude(s) for diagram number 41
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,4),GC_6186,GC_5909,AMP(41))
      CALL FFVV2_4(W(1,5),W(1,3),W(1,6),GC_6932,MDL_MZ, FK_MDL_WZ,W(1
     $ ,4))
C     Amplitude(s) for diagram number 42
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,4),GC_6186,GC_5909,AMP(42))
      CALL FFVV2_4(W(1,5),W(1,3),W(1,6),GC_6942,MDL_MZ, FK_MDL_WZ,W(1
     $ ,4))
C     Amplitude(s) for diagram number 43
      CALL FFV1_3_0(W(1,1),W(1,2),W(1,4),GC_6186,GC_5909,AMP(43))

      JAMP(:,:) = (0D0,0D0)
C     JAMPs contributing to orders ALL_ORDERS=1
      JAMP(1,1) = (-1.000000000000000D+00)*AMP(1)+(-1.000000000000000D
     $ +00)*AMP(2)+(-1.000000000000000D+00)*AMP(3)+(
     $ -1.000000000000000D+00)*AMP(4)+(-1.000000000000000D+00)*AMP(5)
     $ +(-1.000000000000000D+00)*AMP(6)+(-1.000000000000000D+00)*AMP(7)
     $ +(-1.000000000000000D+00)*AMP(8)+(-1.000000000000000D+00)*AMP(9)
     $ +(-1.000000000000000D+00)*AMP(10)+(-1.000000000000000D+00)
     $ *AMP(11)+(-1.000000000000000D+00)*AMP(12)+(-1.000000000000000D
     $ +00)*AMP(13)+(-1.000000000000000D+00)*AMP(14)+(
     $ -1.000000000000000D+00)*AMP(15)+(-1.000000000000000D+00)*AMP(16)
     $ +(-1.000000000000000D+00)*AMP(17)+(-1.000000000000000D+00)
     $ *AMP(18)+(-1.000000000000000D+00)*AMP(19)+(-1.000000000000000D
     $ +00)*AMP(20)+(-1.000000000000000D+00)*AMP(21)+(
     $ -1.000000000000000D+00)*AMP(22)+(-1.000000000000000D+00)*AMP(23)
     $ +(-1.000000000000000D+00)*AMP(24)+(-1.000000000000000D+00)
     $ *AMP(25)+(-1.000000000000000D+00)*AMP(26)+(-1.000000000000000D
     $ +00)*AMP(27)+(-1.000000000000000D+00)*AMP(28)+(
     $ -1.000000000000000D+00)*AMP(29)+(-1.000000000000000D+00)*AMP(30)
     $ +(-1.000000000000000D+00)*AMP(31)+(-1.000000000000000D+00)
     $ *AMP(32)+(-1.000000000000000D+00)*AMP(33)+(-1.000000000000000D
     $ +00)*AMP(34)+(-1.000000000000000D+00)*AMP(35)+(
     $ -1.000000000000000D+00)*AMP(36)+(-1.000000000000000D+00)*AMP(37)
     $ +(-1.000000000000000D+00)*AMP(38)+(-1.000000000000000D+00)
     $ *AMP(39)+(-1.000000000000000D+00)*AMP(40)+(-1.000000000000000D
     $ +00)*AMP(41)+(-1.000000000000000D+00)*AMP(42)+(
     $ -1.000000000000000D+00)*AMP(43)

      IF(INIT_MODE)THEN
        DO I=1, NGRAPHS
          IF (AMP(I).NE.0) THEN
            ZEROAMP_1(IHEL,I) = .FALSE.
          ENDIF
        ENDDO
      ENDIF

      MATRIX1 = 0.D0
      DO M = 1, NAMPSO
        CF_INDEX = 0
        DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = I, NCOLOR
            CF_INDEX = CF_INDEX + 1
            ZTEMP = ZTEMP + CF(CF_INDEX)*JAMP(J,M)
          ENDDO
          DO N = 1, NAMPSO

            MATRIX1 = MATRIX1 + ZTEMP*DCONJG(JAMP(I,N))

          ENDDO
        ENDDO
      ENDDO
      MATRIX1 = MATRIX1/DENOM

      IF(SDE_STRAT.EQ.1)THEN
        AMP2(1)=AMP2(1)+(AMP(1)+AMP(2)+AMP(3)+AMP(4)+AMP(5)+AMP(6)
     $   +AMP(7)+AMP(8)+AMP(9))*DCONJG(AMP(1)+AMP(2)+AMP(3)+AMP(4)
     $   +AMP(5)+AMP(6)+AMP(7)+AMP(8)+AMP(9))
        AMP2(10)=AMP2(10)+(AMP(10)+AMP(11)+AMP(12)+AMP(13)+AMP(14)
     $   +AMP(15)+AMP(16)+AMP(17)+AMP(18)+AMP(19)+AMP(20)+AMP(21)
     $   +AMP(22))*DCONJG(AMP(10)+AMP(11)+AMP(12)+AMP(13)+AMP(14)
     $   +AMP(15)+AMP(16)+AMP(17)+AMP(18)+AMP(19)+AMP(20)+AMP(21)
     $   +AMP(22))
        AMP2(23)=AMP2(23)+AMP(23)*DCONJG(AMP(23))
        AMP2(24)=AMP2(24)+(AMP(24)+AMP(25)+AMP(26)+AMP(27)+AMP(28)
     $   +AMP(29)+AMP(30)+AMP(31)+AMP(32)+AMP(33)+AMP(34)+AMP(35)
     $   +AMP(36)+AMP(37)+AMP(38)+AMP(39)+AMP(40)+AMP(41))
     $   *DCONJG(AMP(24)+AMP(25)+AMP(26)+AMP(27)+AMP(28)+AMP(29)
     $   +AMP(30)+AMP(31)+AMP(32)+AMP(33)+AMP(34)+AMP(35)+AMP(36)
     $   +AMP(37)+AMP(38)+AMP(39)+AMP(40)+AMP(41))
      ENDIF

      DO I = 1, NCOLOR
        DO M = 1, NAMPSO
          DO N = 1, NAMPSO

            JAMP2(I)=JAMP2(I)+DABS(DBLE(JAMP(I,M)*DCONJG(JAMP(I,N))))

          ENDDO
        ENDDO
      ENDDO

      END

      SUBROUTINE PRINT_ZERO_AMP_1()

      IMPLICIT NONE
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=43)

      INTEGER    NCOMB
      PARAMETER (NCOMB=64)

      LOGICAL ZEROAMP_1(NCOMB, NGRAPHS)
      COMMON/TO_ZEROAMP_1/ZEROAMP_1

      INTEGER I,J
      LOGICAL ALL_FALSE

      DO I=1, NGRAPHS
        ALL_FALSE = .TRUE.
        DO J=1,NCOMB
          IF (.NOT.ZEROAMP_1(J, I)) THEN
            ALL_FALSE = .FALSE.
            EXIT
          ENDIF
        ENDDO
        IF (ALL_FALSE) THEN
          WRITE(*,*) 'Amplitude/ZEROAMP:', 1, I
        ELSE
          DO J=1,NCOMB
            IF (ZEROAMP_1(J, I)) THEN
              WRITE(*,*) 'HEL/ZEROAMP:', 1, J  , I
            ENDIF
          ENDDO
        ENDIF
      ENDDO

      RETURN
      END

C     Set of functions to handle the array indices of the split orders


      INTEGER FUNCTION SQSOINDEX1(ORDERINDEXA, ORDERINDEXB)
C     
C     This functions plays the role of the interference matrix. It can
C      be hardcoded or 
C     made more elegant using hashtables if its execution speed ever
C      becomes a relevant
C     factor. From two split order indices, it return the
C      corresponding index in the squared 
C     order canonical ordering.
C     
C     CONSTANTS
C     

      INTEGER    NSO, NSQUAREDSO, NAMPSO
      PARAMETER (NSO=1, NSQUAREDSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERINDEXA, ORDERINDEXB
C     
C     LOCAL VARIABLES
C     
      INTEGER I, SQORDERS(NSO)
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      DATA (AMPSPLITORDERS(  1,I),I=  1,  1) /    1/
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     FUNCTION
C     
      INTEGER SOINDEX_FOR_SQUARED_ORDERS1
C     
C     BEGIN CODE
C     
      DO I=1,NSO
        SQORDERS(I)=AMPSPLITORDERS(ORDERINDEXA,I)
     $   +AMPSPLITORDERS(ORDERINDEXB,I)
      ENDDO
      SQSOINDEX1=SOINDEX_FOR_SQUARED_ORDERS1(SQORDERS)
      END

      INTEGER FUNCTION SOINDEX_FOR_SQUARED_ORDERS1(ORDERS)
C     
C     This functions returns the integer index identifying the squared
C      split orders list passed in argument which corresponds to the
C      values of the following list of couplings (and in this order).
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO, NAMPSO
      PARAMETER (NSO=1, NSQSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER SQSPLITORDERS(NSQSO,NSO)
      DATA (SQSPLITORDERS(  1,I),I=  1,  1) /    2/
      COMMON/SQPLITORDERS1/SQPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSQSO
        DO J=1,NSO
          IF (ORDERS(J).NE.SQSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_SQUARED_ORDERS1 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping in function'
      WRITE(*,*) 'SOINDEX_FOR_SQUARED_ORDERS1'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

      SUBROUTINE GET_NSQSO_BORN1(NSQSO)
C     
C     Simple subroutine returning the number of squared split order
C     contributions returned when calling smatrix_split_orders 
C     

      INTEGER    NSQUAREDSO
      PARAMETER  (NSQUAREDSO=1)

      INTEGER NSQSO

      NSQSO=NSQUAREDSO

      END

C     This is the inverse subroutine of SOINDEX_FOR_SQUARED_ORDERS.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_SQUARED_ORDERS_FOR_SOINDEX1(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the squared
C      split order index in argument. Order values correspond to
C      following list of couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO
      PARAMETER (NSO=1, NSQSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER SQPLITORDERS(NSQSO,NSO)
      COMMON/SQPLITORDERS1/SQPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NSQSO) THEN
        DO I=1,NSO
          ORDERS(I) =  SQPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function'
     $ //' GET_SQUARED_ORDERS_FOR_SOINDEX1'
      WRITE(*,*) 'Could not find squared orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This is the inverse subroutine of getting amplitude SO orders.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_ORDERS_FOR_AMPSOINDEX1(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the split order
C      index in argument. Order values correspond to following list of
C      couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NAMPSO) THEN
        DO I=1,NSO
          ORDERS(I) =  AMPSPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function GET_ORDERS_FOR_AMPSOINDEX1'
      WRITE(*,*) 'Could not find amplitude split orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This function is not directly useful, but included for
C      completeness
      INTEGER FUNCTION SOINDEX_FOR_AMPORDERS1(ORDERS)
C     
C     This functions returns the integer index identifying the
C      amplitude split orders passed in argument which correspond to
C      the values of the following list of couplings (and in this
C      order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NAMPSO
        DO J=1,NSO
          IF (ORDERS(J).NE.AMPSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_AMPORDERS1 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping function SOINDEX_FOR_AMPORDERS1'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

