ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_general_MwScheme_UFO-zfac'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_6361 = ', GC_6361
      WRITE(*,2) 'GC_6532 = ', GC_6532
      WRITE(*,2) 'GC_6534 = ', GC_6534
      WRITE(*,2) 'GC_6738 = ', GC_6738
      WRITE(*,2) 'GC_7033 = ', GC_7033
      WRITE(*,2) 'GC_7035 = ', GC_7035
      WRITE(*,2) 'GC_7743 = ', GC_7743
      WRITE(*,2) 'GC_5268 = ', GC_5268
      WRITE(*,2) 'GC_5270 = ', GC_5270
